### ISSUE TITLE
SelectFields not showing all fields

### ISSUE THREAD

**Issue by DiederikvandenB** [rebing/graphql-laravel#104]
I justed bumped in to the following issue: `SelectFields` does not show all fields that are provided in the query. See the screenshot. The fields ending on `_graph` are omitted from `SelectFields`, as is `recent_redeems`. The reason why they are not included in the relations section is because these are fields that resolve to types not related to a model.

My guess is that because the graph fields have sub-fields `x` and `y`, `SelectFields` discards them, thinking they are relations, and the relations method understands they're not, because their types don't have models.

I hope my explanation is clear. If not, let me know!

![image](https://user-images.githubusercontent.com/6132723/40673831-3d2a45ba-6373-11e8-97d1-8c3c121454e0.png)

**Comment by rebing** [comment]
Did you specify `'selectable' => false` for these fields? https://github.com/rebing/graphql-laravel#creating-a-query

**Comment by DiederikvandenB** [comment]
Yes, I did, but that did not work unfortunately.

**Comment by rebing** [comment]
I'm not sure what the problem is then. You could check for the problem inside SelectFields class.

**Comment by illambo** [comment]
I encountered a similar problem, i attach a simple example:

The scenario is user with relation belongsToMany with customers,
in Customer eloquent model I add a simple test method that take in example some “elaborated” data from db:

```
[...]

/**
 * @return mixed
 */
public function test()
{
    return $this->attributes['name'];
}

/**
 * @return \Illuminate\Database\Query\Builder|static
 */
public function customers()
{
    return $this->belongsToMany(Customer::class, 'user_customer');
}

[...]
```

Add GraphQL types:  

```
class UserTestType extends GraphQLType
{
    protected $attributes = [
        'name' => 'UserTest',
        'description' => 'A user test',
        'model' => User::class,
    ];

    public function fields()
    {
        return [
            'customers' => [
                'type'  => Type::listOf(GraphQL::type('Customer')),
                'description'  => 'The user customers',
            ],
            'but_customers' => [
                'type' => Type::listOf(GraphQL::type('Customer')),
                'description' => 'The user customers',
		'selectable' => false,
                'resolve' => function ($user) {
                    return $user->customers()->get();
                }
            ],
        ];
    }
}
```

```
class CustomerTestType extends GraphQLType
{
    protected $attributes = [
        'name' => 'CustomerTest',
        'description' => 'A customer test',
        'model' => Customer::class,
    ];

    public function fields()
    {
        return [
            'test' => [
                'type' => Type::string(),
                'description' => 'Test',
                'selectable' => false,
                'resolve' => function ($customer) {
                    return $customer->test();
                }
            ],
            'name' => [
                'type' =>  Type::string(),
                'description' => 'The name of the customer',
            ],
        ];
    }
}
```

Add a GraphQL test query:

```
/**
 * Class TestQuery
 * @package App\GraphQL\Query
 */
class TestQuery extends Query
{
    /**
     * @var array
     */
    protected $attributes = [
        'name' => 'UsersTest query',
        'description' => 'A query of users test'
    ];

    /**
     * @return \GraphQL\Type\Definition\ListOfType
     */
    public function type()
    {
        return Type::listOf(GraphQL::type('UserTest'));
    }

    /**
     * @return array
     */
    public function args()
    {
        return [];
    }

    public function resolve($root, $args, SelectFields $fields)
    {
        // Eager loading relationships
        //dd($info, $fields, $with = $fields->getRelations());
        $items = User::with($fields->getRelations())->get();

        return $items;
    }
}

```
Run query (test 1):  

```
query getUsersTest {
	getUsersTest {
		customers {
			test
		}
		but_customers {
			test
		},
	}
}
```

```
{
	"data": {
		"getUsersTest": [
			{
				"customers": [
					{
						"test": null
					}
				],
				"but_customers": [
					{
						"test": "A"
					}
				]
			}
		]
	},
	"errors": [
		{
			"message": "Undefined index: name",
			"code": 0,
			"locations": [
				{
					"line": 4,
					"column": 4
				}
			]
		}
	]
}
```

So seems interesting results for catch the problem, with “but_customers” we loose the “Eager loading relationships” ability but we get the aspected results.

Another interesting test (test 2):

```
query getTest {
	getTest {
		customers {
			test
			name
		}
	}
}
```

```
{
	"data": {
		"getTest": [
			{
				"customers": [
					{
						"test": "A",
						"name": "A"
					}
				]
			}
		]
	}
}
``` 
In that case it work.

Another thing, if I change the test query without eager loading relationships it works (but we loose the “Eager loading relationships” ability).
```
[…]
public function resolve($root, $args, SelectFields $fields)
{
        // Eager loading relationships
        //dd($info, $fields, $with = $fields->getRelations());
        //$items = User::with($fields->getRelations())->get();
	$items = User::all();

        return $items;
 }
[…]
```

I'm try diggin' it.

**Comment by illambo** [comment]
Ok, I did't read the documentation well about that, is possibile use ["always"](https://github.com/rebing/graphql-laravel/blob/c7b1fbc2bb2545321eba6b52f296da313d0325f6/docs/advanced.md#eager-loading-relationships) property for that case.
With this I solve my problem (sorry if it was not relevant to the discussion).
