### ISSUE TITLE
How would testing go?

### ISSUE THREAD

**Issue by dragonfire1119** [rebing/graphql-laravel#106]
How could you test the Queries & Mutations in Laravel? Thanks!

**Comment by lahed** [comment]
You can use extension for chrome 
https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij

Endpoint: yourweb.com/graphql

**Comment by dragonfire1119** [comment]
@lahed I was meaning unit tests. Also I added the chrome extension but didn't try it out that much. I found GraphiQL https://github.com/graphql/graphiql. Thanks!

**Comment by dragonfire1119** [comment]
@illambo Thank you very much works perfect!

**Comment by dragonfire1119** [comment]
@illambo Thank you very much! It works perfect!
