### ISSUE TITLE
How to add query, type or mutation dynamically?

### ISSUE THREAD

**Issue by UrosHCS** [rebing/graphql-laravel#108]
I've added a query to schema and added a type to types in graphql.php config file like this:

`app('config')->set('graphql.schemas.default.query.queries_executed', SomeQuery::class);
app('config')->set('graphql.types.query_executed', SomeType::class);`

I've dumped the config like this:

`dd(config('graphql.schemas.default.query'));`

and the `queries_executed` is there, but when I try to make a query with GraphiQL it says:

`"message": "Cannot query field \"queries_executed\" on type \"Query\"."`

How can I add a query, type or mutation dynamically?

**Comment by fvaldes33** [comment]
@UrosHCS I was able to get this to work for me... Not the prettiest but it works.

```
/**
 * Bootstrap services.
 *
 * @return void
 */
public function boot()
{
    /**
     * Add graphql type
     */
    GraphQL::addType('App\Modules\Workout\WorkoutType', 'workouts');

    /**
     * Add graphql queries and mutations
     */
    $defaultSchema = GraphQL::getSchemas()['default'];

    $defaultSchema['query']['workouts'] = WorkoutQuery::class;
    $defaultSchema['mutation']['updateOrCreateWorkout'] = UpdateOrCreateWorkout::class;
    $defaultSchema['mutation']['deleteWorkout'] = DeleteWorkout::class;
    
    GraphQL::addSchema('default', $defaultSchema);
}
```

**Comment by UrosHCS** [comment]
@fvaldes33 thanks a lot, looks like a solution! I'll try it when I get the chance.
