### ISSUE TITLE
GraphiQL editor "page not found"

### ISSUE THREAD

**Issue by albertcito** [rebing/graphql-laravel#109]
I'm migrating from [Folklore's laravel-graphql](https://github.com/Folkloreatelier/laravel-graphql). I installed the library, I'm not able to see this url: http://127.0.0.1:8000/graphiql/ 

How can I enable the visual editor of GraphQL?

![GraphiQL](https://s3.amazonaws.com/dev.assets.neo4j.com/wp-content/uploads/20170524035049/neo4j-graphql.png)

**Comment by rebing** [comment]
GraphiQL has not been implemented for this package. You can add it by manually creating a route that returns graphiql's index file. Or you can port it from Folklore's package to this one and create a PR.

**Comment by albertcito** [comment]
I created the code in your library. How can I push my branch in your code?

I tried but it displays the following message:  `remote: Permission to rebing/graphql-laravel.git denied to albertcito.`

**Comment by rebing** [comment]
You have to fork my library and then create a pull request from your fork to here

https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by albertcito** [comment]
This feature was added in the pull request [#110](https://github.com/rebing/graphql-laravel/pull/110)

**Comment by e200** [comment]
It keeps not displaying on Lumen.
