### ISSUE TITLE
Adding unit tests

### ISSUE THREAD

**Issue by anolek** [rebing/graphql-laravel#112]
Hi,

What do you think about adding more unit tests in your repository ?

Since the core code it's from another repository, we can simply port them to this repository and adapt it, Then, we can add more unit tests for all the features available in this repository that the other repository doesn't have.

If you want, i can make a PR :)

**Comment by rebing** [comment]
Definitely, go for it! I remember that it was difficult to get Phpunit to work on the package, which is why I didn't create many tests in the beginning, but I regret it now.

**Comment by anolek** [comment]
Hi, is it possible to add Travis @rebing and execute tests automatically ? :)

**Comment by rebing** [comment]
Thanks a bunch @mfn @MrGekko !! 🎉 
#222
