### ISSUE TITLE
Pagination returning a list of null values

### ISSUE THREAD

**Issue by nigeldgreen** [rebing/graphql-laravel#117]
Hi,

I am having an issue with retrieving paginated results. I have a query file and type set up that are working just fine to get all results, but when I make the change to try and retrieve a paginated list, I get all the fields back I asked for, with 'null' against them.

My query file is:

    class ActivitiesQuery extends Query
    {
        [ ... ]
        public function type()
        {
            return GraphQL::paginate('activities');
        }

        [ ... ]

        public function resolve($root, $args, SelectFields $fields)
        {
            if (isset($args['user_id'])) {
                return (new Activity)
                ->with($fields->getRelations())
                ->select($fields->getSelect())
                [ ... some 'where's and 'when's to filter results ... ]
                ->paginate();
            } else {
                return [];
            }
        }

And the type file is:

    class ActivitiesType extends GraphQLType
    {
        [ ... attributes, fields and resolvers ... ]
    }

And I have declared them in my main config:

    <?php

    return [
        [ ... ]
        'schemas' => [
            'default' => [
                'query' => [
                    'activities' => \App\GraphQL\Query\ActivitiesQuery::class,
                ]
            ],
        ],
        'types' => [
            'activities_pagination' => \App\GraphQL\Type\ActivitiesType::class,
        ],
        [ ... ]

I'm calling the query in one of my unit tests as:

    {activities(user_id:"------"){title field1{id} field2{id}}}

I've tried tracing through the execution of the query and the tipping point seems to be that it gets back the array of null values as the result of the call to $this->completeValueWithLocatedError in the completeValueCatchingError method.

It was all working perfectly with a ListOf type and a final ->get() on the main query, but switching over to pagination as shown in the docs has caused it to fail. I would be very grateful for any pointers!

**Comment by rebing** [comment]
Hi, I think you have to put the fields inside a `data` object like so:

```
data {
  title
  field1 {id}
  field2 {id}
}
```
You can check out an example here https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#pagination

**Comment by nigeldgreen** [comment]
Thanks for the reply! I've read through that page a few times now but I just hadn't spotted that extra bit of syntax on the query - will try it out first thing tomorrow.

Thanks for the extension - it's been a real joy to use!

**Comment by rebing** [comment]
Glad to hear :)
