### ISSUE TITLE
Is there a way to add a middleware in only one query?

### ISSUE THREAD

**Issue by Arkanius** [rebing/graphql-laravel#119]
Hello, I'm currently applying middlewares in my schemas successfully; but, now I've got a problem: I need a *after* middleware in some specifyc queries. This one will be responsable to hide some data of my type, eg: My userType shows info of my users. In some cases, I need to show every data of user (if my logged user is an admin) and in other cases I need to show some personal data of my user (if my logged user hasn't admin permission), so, basically, I 'd like to add the middleware directly in my query, or even set the middleware at this specifyc query on my config/graphql.

I already know that I can call the middleware in one specifyc schema, but create a schema for only be responsable for this is not a good option.

Is there a way to do this ? If not, maybe I could make a PR to solve it

**Comment by rebing** [comment]
Perhaps Privacy is what you are looking for? https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#privacy

**Comment by Arkanius** [comment]
I know about the privacy, but, with privacy I should apply it on all my schemas that use this type isn'it ? I need to apply this on only one schema, at only one "query" of this schema.

**Comment by rebing** [comment]
I think you need to do it in the `resolve` method in that case, if you just need to do it once.

**Comment by Arkanius** [comment]
Thanks, I've been searching about it and I still don't know the best solution for this. I guess I'll use the `resolve` anyway
