### ISSUE TITLE
Query on pagination type with relations returns column not found

### ISSUE THREAD

**Issue by ragasubekti** [rebing/graphql-laravel#120]
I was simply trying to get one of the relation data but it always [return column not found on relation](https://imgur.com/a/7SLn7Wi) , but without pagination and select, it was working fine is it because of my query? (i use almost the same query on the example), 

```
    public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {
        $select = $fields->getSelect();

        $pegawai = Pegawai::with('unitKerja')
            ->select($select)
            ->when(strlen($args['search']), function ($query) use ($args) {
                $query->where(function ($q) use ($args) {
                    $q
                        ->where('nip', 'like', '%' . $args['search'] . '%')
                        ->orWhere('nama', 'like', '%' . $args['search'] . '%');
                });
            })->paginate($args['limit'], ['*'], 'page', $args['page']);
        return $pegawai;
    }
```

**Comment by ragasubekti** [comment]
Removing `->select($select)` make it works, but ofcourse i cant use alias anymore, is there any solution like laravel resource where you can customize the data?

**Comment by rebing** [comment]
Could you show the exact query? And make sure the returned `type` is `return GraphQL::paginate(...)`
