### ISSUE TITLE
Consider changing 'params_key' default value

### ISSUE THREAD

**Issue by rwinzhang** [rebing/graphql-laravel#124]
https://github.com/rebing/graphql-laravel/blob/732ddfe4915f58ca8e64e2bdb7f25886599ef3fd/src/config/config.php#L137

It is better to change the default value of `params_key` to `variables` instead of `params` as `Graphiql` default variables key is `variables`.
Just to avoid confusion when starting up and have no idea what's wrong when making the mutation with variables

**Comment by rebing** [comment]
a624fdfe896e6b172517f00e3bdea1bd5c8d4634

**Comment by rwinzhang** [comment]
@rebing thanks
