### ISSUE TITLE
Error in UploadFiles, UploadType in multiple mutation

### ISSUE THREAD

**Issue by DevMakoto** [rebing/graphql-laravel#125]
Use two mutation CreateUser and CreateBook, use UploadType in two mutation
generate error `Schema must contain unique named types but contains multiple types named \"Upload\" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).`

but use UploadType  only mutation no view error

**Comment by rebing** [comment]
#126 Added a name attribute to UploadType constructor
