### ISSUE TITLE
anyway to output binary instead of json?

### ISSUE THREAD

**Issue by crissi** [rebing/graphql-laravel#131]
I am wanting to ouput binary, like an excel document, anyone succeeded in that?

The closes I got was creating an new type, but always end up with "Malformed UTF-8 characters, possibly incorrectly encoded" in "/var/www/ordrestyring-api/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php",

**Comment by diegomengarda** [comment]
To get files, binaries and things there or not json use REST, graphql isn't use to show files and similars responses.
