### ISSUE TITLE
How to config laravel-cors?

### ISSUE THREAD

**Issue by zwl1619** [rebing/graphql-laravel#134]
The docs of [laravel-cors](https://github.com/barryvdh/laravel-cors) said:

> To allow CORS for all your routes, add the HandleCors middleware in the $middleware property of app/Http/Kernel.php class:
```
protected $middleware = [
    // ...
    \Barryvdh\Cors\HandleCors::class,
];
```

In `config/app.php` file of [laravel-graphql](https://github.com/Folkloreatelier/laravel-graphql),there is a item `middleware_schema`,I add `the HandleCors middleware` in `middleware_schema` array.

```
    /**
     * Any middleware for a specific 'graphql' schema
     */
    'middleware_schema' => [
        'default' => [
            \Barryvdh\Cors\HandleCors::class,
        ],
    ],
```
**Question:**      
There is no `middleware_schema` array in `config/app.php` file of `rebing/graphql-laravel`,so where should I put `the HandleCors middleware`?

**Comment by knightazura** [comment]
I can achieve this with simple steps, you can choose it
1. Add CORS on global middleware in `app\http\Kernel.php`, on `protected $middleware` variable like on `laravel-cors` doc, or
2. If you want specific for graphql, add it in graphql config file, there's `middleware` key and add `HandleCors` there. Or if you don't want apply it globally, you can put in every schemas. There's also `middleware` key that you can inject `HandleCors`. Don't forget to run `artisan config:cache`. I don't know why every times I modify config file, I should run that command. If I'm using `folklore/graphql`, I don't need this step.
