### ISSUE TITLE
What does the parameters of resolve($root, $args, SelectFields $fields, ResolveInfo $info) method?

### ISSUE THREAD

**Issue by zwl1619** [rebing/graphql-laravel#135]
What does the parameters of resolve($root, $args, SelectFields $fields, ResolveInfo $info) method mean?
```
    public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {
        $select = $fields->getSelect();
        $with = $fields->getRelations();

        return [];
    }
```
as follow:
1、$root
2、$args
3、SelectFields $fields
4、ResolveInfo $info

**Comment by crissi** [comment]
good question

- $root I don't know...

- $args are the arguments given to the mutation or query

- SelectFields is a class that helps ease the building of efficient eloquent queries by constructing the select and relation to be used in eloquent select- and with-methods from looking at the query/mutation's fields selected

- ResolveInfo can be used to get selected fields using the method getFieldSelection, useful if you need to output something that does not fit a eloquent query or have more control

the SelectFields is specifically for this package, where the other params origin is from the dependency: webonyx/graphql-php

**Comment by diegomengarda** [comment]
https://www.apollographql.com/docs/graphql-tools/resolvers#Resolver-function-signature
