### ISSUE TITLE
Cannot mark custom nested type as NonNull

### ISSUE THREAD

**Issue by refuse** [rebing/graphql-laravel#148]
We encountered some problems with nested queries with fields marked as NonNull. For example a Post having an Author which is NonNullable field of User type. We think that this problem only occurs for fields which are custom types - objects or array of objects.

The exact part of the code which is failing is located here:
https://github.com/rebing/graphql-laravel/blob/v1.15.6/src/Rebing/GraphQL/Support/SelectFields.php#L130

Error: Call to undefined method GraphQL\\Type\\Definition\\NonNull::getField()

```php
try {
    if ($parentType instanceof \GraphQL\Type\Definition\ListOfType) {
        continue;
    } elseif ($parentType instanceof \GraphQL\Type\Definition\UnionType) {
        continue;
    }
    else {
        $fieldObject = $parentType->getField($key);
    }
} catch (InvariantViolation $e) {
    continue;
}
```
We don't know why this problem does not apply to regular fields but only to custom ones.
Maybe, there's a need to handle one more case (solution by intuition):

```php
try {
    if ($parentType instanceof \GraphQL\Type\Definition\ListOfType) {
        continue;
    } elseif ($parentType instanceof \GraphQL\Type\Definition\UnionType) {
        continue;
    } elseif ($parentType instanceof \GraphQL\Type\Definition\NonNull) {
        continue;
    }
    else {
        $fieldObject = $parentType->getField($key);
    }
} catch (InvariantViolation $e) {
    continue;
}
```

**Comment by rebing** [comment]
4be2acb This should fix the issue
