### ISSUE TITLE
php 7 syntax in /src/Rebing/GraphQL/routes.php (line 116)

### ISSUE THREAD

**Issue by McPan68** [rebing/graphql-laravel#154]
In file /src/Rebing/GraphQL/routes.php (line 116) you are using the Null-Coalescing-Operator, which is php > 7.* syntax.
Please change project dependencies to php 7.* or change code to
`$graphiqlController = config('graphql.graphiql.controller', \Rebing\GraphQL\GraphQLController::class . '@graphiql');`
which would be php 5 compatible. Thx!

**Comment by rebing** [comment]
1b7b3f2
