### ISSUE TITLE
Builder error when the attribute is requested twice

### ISSUE THREAD

**Issue by mustorze** [rebing/graphql-laravel#155]
Hello, really like this package and using in all my projects, yeah, i've liked =)

But today i´am getting a error, i´ve unconsciously i typed by an attribute twice.

The query is: 
```
company(id: $id) {
    id
    url
    name
    logo
    status
    config {
      email_after_activation
      support_link
      logout_url
    }
    logo
```
and the returning error is `Method Illuminate\\Database\\Query\\Builder::logo does not exist.`

i know it's my fault, but anyone can use my GraphQL endpoint can faceit and it's a realy bad response to user.

There is a way to treat this error or get it fixed?

Thanks in advance,

Henrique.

**Comment by rebing** [comment]
Hi, I'm glad you like the repo.

Unfortunately this is an error on the requester side and there is not much to do to improve it. I don't think the problem is very common either. However, you can always propose a solution and create a PR.

**Comment by mustorze** [comment]
Okay, i will see in the oficial docs how work in this case and then i do a PR to fix.

Thanks!
