### ISSUE TITLE
Custom pagination is not working

### ISSUE THREAD

**Issue by Jabirr** [rebing/graphql-laravel#159]
Hi,

So i followed the tutorial and made a custom pagination for my project.
The pagination needs to count all the stars and return them. (same as tutorial)
 Pagination code:
![image](https://user-images.githubusercontent.com/31471200/49949709-9c26d280-fef6-11e8-9918-826a796ff1bd.png)

config/graphql.php
`  'custom_paginators' => [
    'review_pagination' =>  \App\GraphQL\Pagination\CountReview::class,
  ],`

Query im doing
`{
  getReviews(id: "1", limit: "5", page: "1") {
    data {
      stars
    }
    total_reviews {
      stars
    }
  }
}
`

And this is my result

![image](https://user-images.githubusercontent.com/31471200/49949633-61249f00-fef6-11e8-846d-6de0256892f9.png)

What am i doing wrong, or what do i need to add? Let me know guys :)

Cheers,

Jabir

**Comment by e200** [comment]
Same issue.

**Comment by naex** [comment]
I have extended the PaginationType and in my custom pagination class overrided protected function getPaginationFields() which returns array_merge(parent::getPaginationFields(), ['new_field' => ...].
Afterwards I changed 'pagination_type' in graphql configuration to the new class. And it works. I gues it should be the right way to do it but in the documentation is another way that doesn't work.
