### ISSUE TITLE
Could we using the graphql-php default formatError?

### ISSUE THREAD

**Issue by living42** [rebing/graphql-laravel#161]
After some doc reading about the underlying package `graphql-php`，i realize that by default it would output some field inside of `errors` when execution thrown some exception, like `path`, `category` . And, with some configuration, it will also output some debug message in `trace` field.

I'm woundering why `graphql-laravel` does'nt do that? It would be nice it we have this fields, especially the `trace` field, that will improve development experience. I can propose some PR to do this :)

----

Some comparison:

This query will cause an exception to notice that user with id 2 does not exists

```graphql
query FetchUser {
  user(id: 2) {
    id
    name
  }
}
```

Implemented by `graphql-laravel`

```json
{
  "data": [],
  "errors": [
    {
      "message": "User not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

Implemented by `graphql-php`

```
{
  "data": [],
  "errors": [
    {
      "message": "User not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "category": "business",
      "path": [
        "user"
      ],
      "trace": [
        ...
      ]
    }
  ]
}
```

**Comment by rebing** [comment]
What are the `category` and `path` fields? Also, I'm not sure showing stack trace to the end-user is good practice. The error should be logged separately.

**Comment by living42** [comment]
> The error should be logged separately.

Actually this not easy to do, because grahpql-php catch all exception and never throws it, so exceptions could not catch and report by the laravel error handling mechanism.

**Comment by rebing** [comment]
Ok, you can propose a PR, if you want to.

And I agree that error logging is not as easy and needs a custom implementation currently.
