### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by mikefrancis** [rebing/graphql-laravel#164]
Hi there,

Thanks for making this package!

Are there any plans to support PHP 7.3? I believe this should be just updating the underlying `webonyx/graphql-php` library to the latest version as the current version throws the following warning on PHP 7.3:

```
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```

in this file:

```
vendor/webonyx/graphql-php/src/Validator/Rules/OverlappingFieldsCanBeMerged.php
```

**Comment by rebing** [comment]
81cbeaf
