### ISSUE TITLE
Adding default args values

### ISSUE THREAD

**Issue by PayteR** [rebing/graphql-laravel#170]
Hi, would be nice to have possibility to set default values for args. Example:

        return [
            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'default' => 10,
            ],
            'page' => [
                'name' => 'page',
                'type' => Type::int(),
                'default' => 1,
            ],
        ];

What do you think?  Thx

**Comment by rebing** [comment]
Sure, you can try to solve it and create a PR.

**Comment by crissi** [comment]
Already exists, use defaultValue instead of default

**Comment by albertcito** [comment]
In this way: 

```php
'limit' => [
    'name' => 'limit',
    'type' => Type::int(),
    'description' => 'Limit result.',
    'defaultValue' => 1,
    'rules' => ['integer', 1, 200]
],
```

**Comment by biobii** [comment]
Based on the @albertcito answers above, it doesn't apply to boolean types. how to deal with it? Thank you.
