### ISSUE TITLE
MorphToMany relation not working properly

### ISSUE THREAD

**Issue by PayteR** [rebing/graphql-laravel#173]
Hi, is there any workaround, how to resolve MorphToMany relationships? this code doesn't work for that:
``` 
public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {        
        $select = $fields->getSelect();
        $with = $fields->getRelations();
        
        $users = User::select($select)->with($with);
        
        return $users->get();
    }
```
my query
```
query users {
  users {
    data {
      name,
      email,
      roles {
        name
      }
    }
  }
}
```
`$select` variable have just user table columns, but roles are blank. I use this permissions from this package https://github.com/spatie/laravel-permission and use models and relationships shipped with this packagge. Thx

**Comment by rebing** [comment]
I don't think that query is even correct. Are you using pagination? It should be
```
query users {
    data {
      name
      email
      roles {
        name
      }
    }
}
```

**Comment by PayteR** [comment]
yes im using pagination

**Comment by PayteR** [comment]
```User::select('*')->with($with);``` Works well, but i don't want to retrieve all fields for performance reason.

**Comment by rebing** [comment]
Just select the `user` primary key (`id` probably) for now and it should work. Or create a PR with a fix

**Comment by PayteR** [comment]
Setting primary key for Model

    protected $primaryKey = 'id';

didn't helped. 

I don't know how to fix it, don't even know where to start...

**Comment by rebing** [comment]
Please read, what I just said - **select** the primary key as in:
```
query users {
    data {
      id
      name
      email
      roles {
        name
      }
    }
}
```

**Comment by PayteR** [comment]
Ah this, i already tried that, didn't helped.

**Comment by rebing** [comment]
#175
