### ISSUE TITLE
$fields->getSelect() returns `table.table.column`

### ISSUE THREAD

**Issue by kylekatarnls** [rebing/graphql-laravel#174]
Hello, I get an SQL error due to duplicate table name in qualified foreign key column:

I simplified code to get the root cause, here is my inspection:
```php
public function resolve($root, $args, SelectFields $fields)
{
    return $fields->getSelect();
}
```

It gives me:
```json
[
  "games.id",
  "games.name",
  "games.games.owner_id"
]
```

While I expected:
```json
[
  "games.id",
  "games.name",
  "games.owner_id"
]
```

To get the SQL query working.

Here is what happens inside **SelectFields.php**:

```php
$relation = call_user_func([app($parentType->config['model']), $key]);
// Add the foreign key here, if it's a 'belongsTo'/'belongsToMany' relation
if(method_exists($relation, 'getForeignKey'))
{
    $foreignKey = $relation->getForeignKey();
}
else if(method_exists($relation, 'getQualifiedForeignPivotKeyName'))
{
    $foreignKey = $relation->getQualifiedForeignPivotKeyName();
    // belongsToMany make PHP go there and $foreignKey is games.owner_id, cf getQualifiedForeignPivotKeyName() contents
}
else
{
    $foreignKey = $relation->getQualifiedForeignKeyName();
}

$foreignKey = $parentTable ? ($parentTable . '.' . $foreignKey) : $foreignKey;
// Then it prepend again the table name: games.games.owner_id
```

It seems to me like it should prepent $parentTable only if not getting a qualified name.

**Comment by rebing** [comment]
Can you make a PR please?

**Comment by kylekatarnls** [comment]
#175 is a possible fix. I tried to add a unit test for that. I don't see `SelectFields` occurrence in tests directory so I guess, there is no test yet specific to this particular class. I created the data example with a CarType/DriverType, the models and the belongsTo. How can I now add a test to get the `$fields->getSelect()` result?
