### ISSUE TITLE
File level exceptions cause exception inside GraphQL error reporting

### ISSUE THREAD

**Issue by pushchris** [rebing/graphql-laravel#179]
Previously no errors ever bubbled up to the exception reporting, now things do, which is great, but on occasion things like this come through to our error reporting:

```
Argument 1 passed to App\Exceptions\Handler::report() must be an instance of Exception, instance of Error given, called in /rebing/graphql-laravel/src/Rebing/GraphQL/GraphQL.php on line 304 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Exceptions\\Handler::report() must be an instance of Exception, instance of Error given, called in /rebing/graphql-laravel/src/Rebing/GraphQL/GraphQL.php on line 304 at /app/Exceptions/Handler.php:35)
[stacktrace]
```

Which really doesnt help at all and is kinda perplexing as to what the actual error is. From what I can tell the source of the issue is line 299 of GraphQL.php
https://github.com/rebing/graphql-laravel/blob/739a01aed68d9eeb460f34e09883cf2df97583c4/src/Rebing/GraphQL/GraphQL.php#L293-L305

I believe in addition to the following:
```php
if ($error instanceof \GraphQL\Error\Error) {
    continue;
}
```

You also need to check for ```\Error``` which is what the Exception is coming through as
```php
if ($error instanceof \GraphQL\Error\Error || $error instanceof \Error) {
    continue;
}
```

Any insight into this would be lovely. Not exactly sure how this portion works overall but that tweak caused exceptions to properly be reported.

**Comment by rebing** [comment]
You can specify your own custom ErrorHandler in `config/graphql.php`

**Comment by seandelaney** [comment]
I have the same issue. 

Why was this issue closed without a better answer?

I'm confused to how adding our own custom Error handler will resolve this?

**Comment by pushchris** [comment]
@rebing I agree you could solve this by providing your own error handler, but shouldn't out of the box these types of error be caught? If you are a new user and have a single typo it is going to show that there is an error in this package instead of being helpful about what you did wrong.

@seandelaney what he is mentioning is that instead of it calling the error handler code inside of GraphQL.php you can provide your own in the graphql.php config file. Something like the following:
```php
<?php

namespace App\Exceptions;

use Illuminate\Contracts\Debug\ExceptionHandler;

class ErrorHandler
{
    public static function handleErrors(array $errors, callable $formatter)
    {
        $handler = app()->make(ExceptionHandler::class);
        foreach ($errors as $error) {
            // Try to unwrap exception
            $error = $error->getPrevious() ?: $error;
            if ($error instanceof \GraphQL\Error\Error || $error instanceof \Error) {
                continue;
            }
            $handler->report($error);
        }
        return array_map($formatter, $errors);
    }
}
```

This is exactly what I recommended above and replacing the error handler used with this fixes the issue. 
```php
'errors_handler' => ['\App\Exceptions\ErrorHandler', 'handleErrors'],
```

@seandelaney could you try using the above and see if it resolves your issue?

**Comment by seandelaney** [comment]
> I agree you could solve this by providing your own error handler, but shouldn't out of the box these types of error be caught? If you are a new user and have a single typo it is going to show that there is an error in this package instead of being helpful about what you did wrong.

Exactly. I had a left out a class and spent the bones of 3 hours trying to figure out why things were broken. Went down all rabbit holes without success until I came across this issue.

I manually add ` || $error instanceof \Error` and found my issue and fixed it.

However, I am now going to follow the suggestion of @pushchris and add my own error handler.

Thanks @pushchris !

**Comment by rebing** [comment]
cb7a0a3
I modified the handler to only report `\Exception` class since that is required within the default `ExceptionHandler`

**Comment by pushchris** [comment]
Works great @rebing much appreciated!

**Comment by seandelaney** [comment]
Thanks, @rebing, also much appreciated!! 👍
