### ISSUE TITLE
Eager-loading relationship, selectable and always

### ISSUE THREAD

**Issue by ajanini** [rebing/graphql-laravel#181]
Running Laravel v5.7 and rebing/graphql-laravel v1.17.3.

In my **Eloquent** model class I have

```php
class Handpicked extends BaseModel
{
    public function realtyImage()
    {
        return $this->belongsTo('App\Models\RealtyImage', 'image_id');
    }

    public function getImageAttribute()
    {
        return env('SITE_URL') . $this->realtyImage->url;
    }
}
```

This works in the Tinker Shell as expected: `App\Models\Handpicked::first()->image`.

In the related **GraphQL Type** class I've setup my `fields` as follows:
```php
class HandpickedType extends GraphQLType
{
    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'The id of the highlight',
            ],
            'image' => [
                'type' => Type::string(),
                'description' => 'The complete URL to the image',
                'selectable' => false, // Does not try to query this from the database
            ],
            'realtyImage' => [
                'type' => GraphQL::type('realtyImage'),
                'description' => '',
            ],
        ];
    }
}
```

When I try the following query, it **fails** and I get a `Trying to get property 'url' of non-object` error:
```graphql
query FetchHandpicked {
  handpicked {
    id
    image
  }
}
```

However, the following query **works**, and the `image` attribute is returned as expected:
```graphql
query FetchHandpicked {
  handpicked {
    id
    image
    realtyImage {
      url
    }
  }
}
```

My guess is this is related to eager-loading the relationships. I've that [section in the documentation](https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#eager-loading-relationships) and about the `always` attribute, but I could not figure out how to implement it in this case.

Any pointers are greatly appreciated.

**Comment by ajanini** [comment]
> Yes, unfortunately currently the only way to load the required variable is by selecting it with the query (your 2nd example). I think it also works if you use resolver within the Type like so:
> 
> ```
> 'image' => [
>   'type' => Type::string(),
>   'description' => 'The complete URL to the image',
>   'selectable' => false, // Does not try to query this from the database
>   'resolve' => function ($handpickedType) {
>     return env('SITE_URL') . $handpickedType->realtyImage->url;
>   },
> ],
> ```
> but this does not eager loading the relationships and will make n+1 queries, if you return a list of HandpickedType.

Thank you, but the the `resolve` attribute doesn't seem to work without including `realtyImage` in the query (2nd example in the original post). :-(

**Comment by PayteR** [comment]
Any idea how to fix this? Maybe by always loading columns that are defined in model's `$appends = []` ?

**Comment by mfn** [comment]
PRs are always welcome! I didn't completely get it, but often its answered with tests accompanioning the change, this really helps a lot!

**Comment by mfn** [comment]
@Artem-Schander there's a "slack join" button at the to of the readme. But actually you're on slack and we've had PMs in the past 😅
