### ISSUE TITLE
Default pagination not working

### ISSUE THREAD

**Issue by ajanini** [rebing/graphql-laravel#182]
Running Laravel v5.7 and rebing/graphql-laravel v1.17.3.

This works fine:
```php
class RealtiesQuery extends Query
{
    public function type()
    {
        return Type::listOf(GraphQL::type('realty'));
    }
    // ...
}
```

This does not:

```php
class RealtiesQuery extends Query
{
    public function type()
    {
        return GraphQL::paginate(GraphQL::type('realty'));
    }
    // ...
}
```

The second code fails with an `Illegal offset type in isset or empty` exception.
It seems that the problem happens in [/vendor/rebing/graphql-laravel/src/Rebing/GraphQL/GraphQL.php, line 130](https://github.com/rebing/graphql-laravel/blob/master/src/Rebing/GraphQL/GraphQL.php#L130), when instead of a string, an object is being passed as the first argument.

I added the following just before line 130:
```php
if (! is_string($name)) dd($name, $this->types);
```

In my case, the `RealtyType` *object* is being passed as the first argument, instead of the *string* `realty`, according to the dumps:

**$name:**
<img width="644" alt="name" src="https://user-images.githubusercontent.com/3225794/51750353-00fa4e80-2099-11e9-9ad2-fcca12b01d26.png">

**$this->types:**
<img width="644" alt="types" src="https://user-images.githubusercontent.com/3225794/51750503-69e1c680-2099-11e9-8983-81a35fb755a2.png">

Any pointers?

**Comment by pushchris** [comment]
@ajanini for the pagination type you are just supposed to pass the GraphQL Type name as a string, so in your case it would be ```GraphQL::paginate('realty')```. It's less a wrapper like ```listOf``` and more its own type.

**Comment by ajanini** [comment]
@pushchris Thanks a lot! My mistake!
