### ISSUE TITLE
What happened with V1.17.3? 

### ISSUE THREAD

**Issue by Arkanius** [rebing/graphql-laravel#186]
Hello, I'm using this pack in production and I realised that the new version had some braking changes. The first point is: wasn't it a breaking change ? Before this version, all paginated type had the name with a "_" like "users_pagination", but now, the name changed to "Pagination", I mean, in my mind this should be a breaking change.
I tried to get back to my local version (V1.17.3) and I realised that it does'n exists anymore. Did you delete it?

**Comment by rebing** [comment]
Sorry, I had deleted it by accident. It should be available again
