### ISSUE TITLE
How to validate unique field value

### ISSUE THREAD

**Issue by PayteR** [rebing/graphql-laravel#187]
Hi, how it's possible to validate unique field value on update? For example, i need to update user profile and email field should be unique. That's not a problem while creating an user:

```
// https://laravel.com/docs/5.7/validation#rule-unique
'email' => [
                'name' => 'email',
                'type' => Type::nonNull(Type::string()),
                'rules' => ['required', 'email', 'unique:users,email'],
            ],
```
But, when i want to update user email with same value, this rule will return validation error, due fact, that this email is already in table. It doesn't realise that this email address is tied to this user.

To ignore some ID in validation is possible by adding ID of current user into rules like this ` 'rules' => ['required', 'email', 'unique:users,email,123'],` (https://laracasts.com/discuss/channels/requests/laravel-5-validation-request-how-to-handle-validation-on-update) but i cant get ID in my args() method of my mutation. 

What's the correct way to validate unique value with ignored ID? thx

**Comment by PayteR** [comment]
Ok, i have it already, found solution here https://github.com/Folkloreatelier/laravel-graphql/issues/47. I need to define rule for email field in rules() method.

```
public function args()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'ID of updated user',
                'rules' => ['required'],
            ],
            'name' => [
                'name' => 'name',
                'type' => Type::nonNull(Type::string()),
                'rules' => ['required'],
            ],
            'email' => [
                'name' => 'email',
                'type' => Type::nonNull(Type::string()),
                'rules' => [], // check rules() method
            ],
            'password' => [
                'name' => 'password',
                'type' => Type::string(),
                'rules' => ['sometimes', 'required', 'min:6'],
            ]
        ];
    }

    protected function rules(array $args = [])
    {
        $rules = [];
        $rules['email'] = ['required', 'email', Rule::unique('users')->ignore($args['id'])];
        return $rules;
    }
```

**Comment by smithj0016** [comment]
I used your code for custom validations, but it is giving me error for "Rule class not found". I tried to search the location of Rule class in Rebing but did not get. Can you please mention the location for the class to include in mutation for rebing?

**Comment by smithj0016** [comment]
Ignore above comment. Got it.

**Comment by mnogokotin** [comment]
or like this:
[
    'name' => 'email',
    'type' => Type::string(),
    'rules' => function($args) {
        return [
        'string',
        'min:3',
        'max:191',
        'email:rfc,dns',
        'unique:users,email,' . $args['id'] . ',id'
        ]; 
    }
]
