### ISSUE TITLE
Problem with combining eager loading and custom field resolving

### ISSUE THREAD

**Issue by tricky666** [rebing/graphql-laravel#19]
I am trying to set up a query on a tree-structure of Page type objects:

query{
    pages{
        id,
        sorting,
        children{
            id,
            sorting
        }
    }
}

The table representing pages does not have a nicely named column for sorting, but uses "sub_cat".

I want the field named sorting in the output so I have specified a sorting field in the schema for Page and specified a resolveSortingField($root, $args) function which return $root->sub_cat. for the Page type so that it is output as Sorting and not sub_cat.

This works fine for "flat" queries, however it results in a problem when I eager-load children using ::with($fields->getRelations()) (Rebing\GraphQL\Support\SelectFields)  since this ends up creating an eager load query with a SELECT part using the fields names directly from the query, which of course gives an error:
 
select `sites`.`id`, `sites`.`sorting` from `sites` where `sites`.`id` in (0, 1, 5))

Is there any way of configuring the type or query to get around this problem?

**Comment by rebing** [comment]
If I understand your problem correctly, you should also add a `'selectable' => false` attribute to you `sorting` field:

`
'sorting' => [
    'selectable' => false,
    'type' => ...
]
`

This way the `sorting` field will not be processed by the SelectFields class

**Comment by tricky666** [comment]
Thank you for your reply, that solves my problem.
