### ISSUE TITLE
GraphQLLumenServiceProvider not found

### ISSUE THREAD

**Issue by e200** [rebing/graphql-laravel#193]

**Comment by rebing** [comment]
Lumen is not supported in release yet, please use the master branch for now.

**Comment by e200** [comment]
Thanks for the quick answer!

I'm using "rebing/graphql-laravel": "dev-master", but I still getting the Exception.

**Comment by e200** [comment]
Sorry for the incomplete information.

It is happening on `php artisan graphql:publish`.

**Comment by e200** [comment]
A workaround: https://github.com/laravel/lumen-framework/issues/504#issuecomment-269410657

**Comment by rebing** [comment]
Not an error related to this package
