### ISSUE TITLE
How to pass GraphQL type as query argument?

### ISSUE THREAD

**Issue by e200** [rebing/graphql-laravel#195]
It's possible to pass GraphQL type attributes as query argument?

The idea is to get all users except those that have the role `admin`.

Like:

```php
class UsersQuery extends Query
{
    protected $attributes = [
        'name' => 'users'
    ];

    public function type()
    {
        return Type::listOf(GraphQL::type('User'));
    }

    public function args()
    {
        return [
            'except' => [
                'name' => 'except',
                'type' => GraphQL::type('UserRole')
            ],
        ];
    }

    // ...
}
```
and request it like:

```graphql
{
  users(except: { user_role: "admin" }) {
    id
    name
  }
}
```

But, it not working.
In my case it's given the following error:

`[2019-02-13 08:06:18] local.ERROR: Exception in /home/.../vendor/webonyx/graphql-php/src/Type/Definition/StringType.php:98
Stack trace:`

Any help? Thanks!

**Comment by rebing** [comment]
What does you `UserRoleType` look like?

**Comment by e200** [comment]
```php
class UserRoleType extends GraphQLType
{
    protected $attributes = [
        'name' => 'UserRole',
        'description' => 'A user rola'
    ];

    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'The id'
            ],
            'name' => [
                'type' => Type::string(),
                'description' => 'The name'
            ],
            'value' => [
                'type' => Type::string(),
                'description' => 'The value'
            ],
        ];
    }
}
```

**Comment by rebing** [comment]
You have to use an InputObjectType: https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#input-object

**Comment by e200** [comment]
Thanks, I'll read about that.

**Comment by PayteR** [comment]
> You have to use an InputObjectType: https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#input-object

This link is dead

**Comment by mfn** [comment]
The docs have been restructured recently => https://github.com/rebing/graphql-laravel#input-object
