### ISSUE TITLE
Package is prevent some internal errors from being logged

### ISSUE THREAD

**Issue by e200** [rebing/graphql-laravel#200]
It's becoming hard sometimes to track some errors maybe because their not being passed properly to the Error Handling mechanism.

I get "message": "Internal server error", but the same error isn't being logged to log files.

**Comment by rebing** [comment]
Implement your own custom Error handler and use that perhaps?

**Comment by e200** [comment]
It's not about a custom logger, the logger isn't being called on some internal errors.
