### ISSUE TITLE
Validation for Query Arguments

### ISSUE THREAD

**Issue by hanspagel** [rebing/graphql-laravel#201]
Is there any way to use Laravel Validation for Query arguments?

I tried the two following ways:

```php
class FooQuery extends Query
{
    public function args()
    {
        return [
            'id' => [
                'name' => 'id',
                'type' => Type::string(),
                'rules' => [
                    'required',
                    'uuid',
                ],
            ],
        ];
    }
}
```

and

```php
class FooQuery extends Query
{
    public function rules(array $args = [])
    {
        return [
            'id' => [
                'required',
                'uuid',
            ],
        ];
    }
}
```

Both without success. Is this supported?

**Comment by hanspagel** [comment]
Ah, I tried to dig through the code and found the issue I'm facing:

In `Field.php` *first* you're executing the authorize query and *then* you're validating the input. In my case that throws an error if the argument isn't a correct UUID.

Not sure if you can do something about that. I guess there's no chance your doing the validation first and then the authorization. I'll try if I can work around this.

**Comment by rebing** [comment]
You can work around it by having the authorization inside the Query's `resolve` method.

**Comment by hanspagel** [comment]
Ah, good idea! Thanks!

**Comment by hanspagel** [comment]
This is relevant for all mutations and queries I've build. Another example is when an argument isn't present:

```php
    public function authorize(array $args)
    {
        $post = Post::find($args['id']);

        return request()->user()->can('update', $post);
    }
```

This throws an undefined error for $args['id']. I guess there is a reason you're executing the authorize method before the validation method, isn't there?

What I did is to build a Trait and add a method call to a validation helper inside every authorize method. Doesn't feel great. 😅

**Comment by hanspagel** [comment]
Okay, I took another path: I duplicated the Field classes and changed the behavior. That feels better.
