### ISSUE TITLE
Custom pagination is not working in lumen

### ISSUE THREAD

**Issue by sh4msi** [rebing/graphql-laravel#202]
Hi guys

I use a dev-master version for lumen but Custom pagination does not work
#197  @e200

Pagination code:
```
namespace App\GraphQL\Custom;

use Illuminate\Pagination\LengthAwarePaginator;
use GraphQL\Type\Definition\Type as GraphQLType;

class UserPaginationFields
{
    public static function getPaginationFields()
    {
        return [
            'count' => [
                'type'          => GraphQLType::nonNull(GraphQLType::int()),
                'description'   => 'Number of the current paginated items selected by the query',
                'resolve'       => function(LengthAwarePaginator $data) { return $data->count(); },
                'selectable'    => false,
            ],
            'last_page' => [
                'type'          => GraphQLType::nonNull(GraphQLType::int()),
                'description'   => 'Last page for the cursor',
                'resolve'       => function(LengthAwarePaginator $data) { return $data->lastPage(); },
                'selectable'    => false,
            ],
          // other code ....
          // other code ....
        ];
    }
```

config\graphql.php
```
    'custom_paginators' => [
        'user_pagination' => \App\GraphQL\Custom\UserPaginationFields::class,
    ],
```

Another code is needed to write ?

**Comment by e200** [comment]
Same here.

**Comment by zabaala** [comment]
Try copy Rebing\GraphQL\Support\PaginationType to your project and modify your provider to point to new location. Maybe you can customize your pagination.

**Comment by sh4msi** [comment]
hi

In this case, the fields can not be found ( SelectFields $fields in  Query resolve)

```
    public function resolve($root, $args, SelectFields $fields)
    {
        dd($fields);
```

```
SelectFields {#479 ▼
  -select: []
  -relations: []
}
```



but Anyway, thank you @zabaala

**Comment by mfn** [comment]
The original description talk about `custom_paginators` but there is no configuration option by that name ([anymore](https://github.com/rebing/graphql-laravel/commit/a9212adcda75b870965064c0113bd98b3b55203d)).

As suggested in https://github.com/rebing/graphql-laravel/issues/202#issuecomment-465157587, use `pagination_type`.

(if your `config/graphql.php` is out of date, republish it but make a backup of your existing one you can keep your changes).

I'm not ignoring the [last mention regarding the SelectFields issue](https://github.com/rebing/graphql-laravel/issues/202#issuecomment-465418117), but: there's simply not enough information to reproduce anything here.

I'm therefore going to close this issue.

I'm happy to reopen it if you can provide more information and reproducible code; or if you think it's a different issue from your initial title / description, please feel free to open a new one.
