### ISSUE TITLE
Multiple schema is not working in lumen 

### ISSUE THREAD

**Issue by sh4msi** [rebing/graphql-laravel#204]
hi

req url = http://localhost:8000/api/secret

```
mutation {
  createUser(
    name: "tester"
    email:"123@test.com"
    password:"123"
  ) {
    id,
    email
  }
}
```

error:
`"message": "Schema is not configured for mutations.",`

config:
```
    'schemas' => [
        'default' => [
            'query' => [
                 'login'    => UserLoginQuery::class,
            ],
             'mutation' => [
                //..
            ],
            'method' => ['post'],
        ],
        'secret' => [
            'query' => [
                //..
            ],
            'mutation' => [
                'createUser' => CreateUserMutation::class
            ],
           //  'middleware' => ['auth:api'],
            'method' => ['post'],
        ],
    ],
```

**Comment by sh4msi** [comment]
Hi guys

**[my solution for this problem
](https://github.com/sh4msi/graphql-laravel/commit/bb426dd18bbf51f7b463da7cb78f8ff18c623fa0)**



> Of course, you can, not change the original files and just call the other controller from the config file.

**Comment by MrGekko** [comment]
The controller changed a little bit about 6 days ago. If this is a solution that everyone needs maybe you could create a pull-request?

**Comment by mfn** [comment]
Looks like this is the same as https://github.com/rebing/graphql-laravel/issues/236

**Comment by mfn** [comment]
I've just merged a PR which I believe fixes this problem.

There's no release yet so if you're eager, you need to test with `dev-master`.
Also be aware that the master branch has other changes we may require further adaptions to make it work (types mostly).

If it still doens't work, please create a new issue with details to reproduce it; thank you!
