### ISSUE TITLE
Weird cache problem on production

### ISSUE THREAD

**Issue by mxmtsk** [rebing/graphql-laravel#208]
I have set up a simple API on locally that I have successfully deployed via Laravel Envoyer to a production server. Although I can see the changes applied to the files, when I run the queries they behave like the previous deployment which makes me wonder if t here is some kind of cache that I don't see? Running `php artisan cache:clear` etc did not help.

**Comment by typify** [comment]
If you define new queries/mutations/types in your `config/graphql.php` file you probably need to rebuild the configuration cache: `php artisan config:cache` on your production environment.

**Comment by mfn** [comment]
Hey @mxmtsk ,

there hasn't been any more feedback so far and what you describe looks very much like the config caching issue, as suggested by @typify even though you said you already tried it.

As of now, this library has no caching on its own whatsoever so IMHO it can only be related to this our something else _outside_ the library.

I'm therefore closing this issue. If you can provide more information pointing to a problem in the library, I'm happy to reopen it!
