### ISSUE TITLE
Resolve alias field

### ISSUE THREAD

**Issue by zabaala** [rebing/graphql-laravel#211]
Hi

I'm trying to create somes types and a case sound strange for me. When I try to create a field with a custom name, and I set the correct field name in alias, the aliased value field value is not returned.

The value is returned only if implement resolveCustomFieldResolve() method. It's correct?

Thanks.

**Comment by albertcito** [comment]
This is my `UserType.php` with a custom field called `images`: 

```php
return [
    'idUser' => [
        'type' => Type::nonNull(Type::int()),
        'description' => 'User identification, primary key'
    ],
    'images' => [
        'type' => GraphQL::paginate('ImageType'),
        'description' => 'Images create by the user',
        'args' => $pagination
    ],
]
```

```php
protected function resolveImagesField($root, $args)
{
    $images = $root->images(); 
    return $images->paginate($args['limit'], ['*'], 'page', $args['page']);
}
```

**Comment by zabaala** [comment]
Thanks, @albertcito.

In my case is different. I want understand because the alias is not resolved automatically.

BTW you are passing $pagination to args, to receive him in resolveImagesField($root, $args) method. What does $pagination do?

**Comment by rebing** [comment]
Please elaborate your issue or show an example

**Comment by zabaala** [comment]
@rebing,

Let's say i creating a Customer Type from a model that has a attribute called address_number. Then we would have something similar to this:

```php

<?php

class Subscriber extends Type
{
  // ...
  public function fields()
  {
    'addressNumber' => [
      'type' => Type::int(),
      'alias' => 'address_number'
     ]
  }
}
```

In that case, if I do not implement the resolveAddressNumberResolve() method, the address_number value will not be returned, although the field is being queried in the database. My question is: should not this / could happen automatically, since I am informing the alias?

**Comment by anolek** [comment]
Same issue as #130 if i understand correctly your problem

```php
<?php

class Subscriber extends Type
{
  // ...
  public function fields()
  {
    'addressNumber' => [
      'type' => Type::int(),
      'alias' => 'address_number',
      'resolve' => function ($root) { // As a workaround
               return $root->address_number;
      }
     ]
  }
}
```

**Comment by zabaala** [comment]
@anolek exactly!

My question is: because alias is not resolved automatically as mentioned by @rebing [here?](https://github.com/rebing/graphql-laravel/issues/130#issuecomment-418030430) 

Follow a piece of his comment:

> To be honest, I don't think I've ever used the `alias` field myself, but that doesn't look like the correct behavior. It should be as you said that it automatically resolves to the correct field. So if the alias is `end_period_number`, then it should resolve to `$root->end_period_number` automatically.

**Comment by rebing** [comment]
@zabaala As I mentioned in the other thread, you can look into it and find the problem in `SelectFields` class.

**Comment by mfn** [comment]
@zabaala I believe this was fixed with https://github.com/rebing/graphql-laravel/pull/283 , can you try [the v1.22.0 release](https://github.com/rebing/graphql-laravel/releases/tag/v1.22.0)?

**Comment by anolek** [comment]
After upgrading to v1.22.0, it is, indeed fixed @mfn

**Comment by zabaala** [comment]
I'll try it soon, @mfn.

Thanks.

**Comment by dharkness** [comment]
Aliases work for me as well with v1.22.0.

**Comment by mfn** [comment]
There has been now feedback from OP but given the other feedback and the PR I merged, I'm pretty sure this is fixed.

If not, please simply create a new issue => thanks!
