### ISSUE TITLE
Primary key type array

### ISSUE THREAD

**Issue by yasergh** [rebing/graphql-laravel#215]
i have models define the primary key id array like this 
**protected $primaryKey = array('id_product', 'id_lang');**
so when make relation ship between to model in graphql display error message 
**Array to string conversion** 
so to sole this issue i change class **SelectFields** in line 72 with this code 
```
        if( ! is_null($primaryKey))
        {
            if(is_array($primaryKey)){
                foreach ($primaryKey as $key){
                    $select[] = $parentTable ? ($parentTable . '.' . $key) : $key;
                }
            }else{
                $primaryKey = $parentTable ? ($parentTable . '.' . $primaryKey) : $primaryKey;
                if( ! in_array($primaryKey, $select))
                {
                    $select[] = $primaryKey;
                }
            }
        }
```
to solve issue can you add this code to an original  file

Best regards

**Comment by rebing** [comment]
#216
