### ISSUE TITLE
How can I add a translation for the field name in query or mutation

### ISSUE THREAD

**Issue by albertcito** [rebing/graphql-laravel#226]
I'm trying to set the error message for different languages. Right now the result is the following, the `:attribute` variable is always filled in English:

EN: `The confirm new password and new password must match.`
ES: `El confirm new password y new password deben coincidir.`

My idea is to do this, but it prints an error. How can I do it?

```php
public function args()
{
    return [
        'currentPassword' => [
            'name' => __('user.currenPassword'),
            'type' => Type::string(),
            'rules' => ['required', 'min:6']
        ],
       ...etc
}

```

```graphql
mutation {
  userUpdatePassword(
    idUser:1,
    currentPassword:"123456"
    newPassword:"1234567"
    confirmNewPassword:"1234567"
  ) {
    message
  }
}
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "Unknown argument \"currentPassword\" on field \"userUpdatePassword\" of type \"Mutation\"."
    }
  ]
}
```

**Comment by mfn** [comment]
>  "message": "Unknown argument \"currentPassword\" on field \"userUpdatePassword\" of type \"Mutation\"."

Using translation here is probably a bad idea: you would change the GraphQL API _per locale_.

The way I understand it, you already managed to switch to the correct locale based on the user? So all you need is the correct translation in `/resources/lang/<language>/validation.php`.

**Comment by albertcito** [comment]
Hi @mfn, I created a new file `/resources/lang/es/validation.php` So, for example, this translation rule:

`'same' => 'El :attribute y :other deben coincidir'`

`:attribute` is getting from the query or mutation name, and in the mutation that variable name is in English, but my traduction is in Spanish.

**Comment by mfn** [comment]
> `:attribute` is getting from the query or mutation name, and in the mutation that variable name is in English, but my traduction is in Spanish.

Ah, I see!

Sorry, don't know. Does your "attribute" (i.e. GraphQL field) really change "per locale"? Is the GraphQL API different for each locale?

**Comment by albertcito** [comment]
I created a middleware to set the app language (`\App::setLocale($lang);`) to the lang defined in the user profile. So, all the messages from the GraphQL are in Spanish or English. The errors messages are printed in English or Spanish, but the atributes defined in the `args` function are always in English, because the attibute name is in English: 

 ```php
public function args()
{
    return [
        'currentPassword' => [
            'name' => 'currentPassword',
            'type' => Type::string(),
            'rules' => ['required', 'min:6']
        ],
       ...etc
}
```
So the translation in the file es.php is : `El :attribute es requerido.`, the text is in Spanish but the variable name (:attribute) is in English: 
- 'El **current password**  es requerido'.

**Comment by albertcito** [comment]
I did it. It was my fault (as usually) xD

In the file `/resources/lang/es/validation.php` I filled the `attributes` option

```php 
'attributes' => [
        'newPassword' => 'nueva contraseña'
],
```

And now it works, the message is in Spanish: `El nueva contraseña al menos debe ser 6 caracteres.`
