### ISSUE TITLE
Self reference InputObjectType field infinite recursion

### ISSUE THREAD

**Issue by infinity0n3** [rebing/graphql-laravel#229]
I have ported my code from `folklore/laravel-graphql` library and noticed that some of my filters create a runaway recursion where they did not make those with folklore.

The simplified scenario is here. Queries have filter fields that are defined as InputObjects. The filters follow the structure of the types they are attached to. So my `Repository` model looks something like this

```
type Repository @model {
    id: ID!
    name: String!   
    # parent
    parent: Repository
}

```
The corresponding FilterInput translates to this
```
...
class RepositoryFilterInput extends GraphQLType
{
    protected $inputObject = true;
    
    protected $attributes = [
        'name' => 'RepositoryFilter',
        'description' => 'A type RepositoryFilter',
    ];

    public function fields()
    {
        return [

            'parent' => [
                'type' => GraphQL::type('RepositoryFilter'),
                'description' => 'The parent of RepositoryFilter'
            ],
       ]
   }
...

```

The issue is that in [getInputTypeRules@Fields.php](https://github.com/rebing/graphql-laravel/blob/master/src/Rebing/GraphQL/Support/Field.php#L138) there is a recursive call to create the field rules however it does not have any safety check to stop the recursion in case of self reference.

This unfortunately has catastrophic results by bringing down the php interpreter while shooting to max RAM and CPU usage.

**Comment by infinity0n3** [comment]
I've added a pull request #230, with a simple fix. Have tested it and it does not seem to have any unwanted side effects.

**Comment by rebing** [comment]
#230
