### ISSUE TITLE
Can't query union types

### ISSUE THREAD

**Issue by Roemerb** [rebing/graphql-laravel#232]
Hey all,

I've recently implemented some union types for a project, and they don't seem to be working when I query those fields. In my case, I have a UnionType called `MetaAttachment`, which should be resolved to a `Location` or `File` type and represents metadata associated with an object in the application. Here's the query I run:

```graphql
query {
  person(id: 1) {
    name,
    meta {
      type,
      value,
      attachment { // This is the metafield which is a File or Location. I.e. a profile picture file or work location
        ...on Location {
          name,
          description
        }
        ...on File {
          extension
        }
      }
    }
  }
}
```

This does not generate an error. The response is normal, except for the fact that `attachment` is `null`. Interestingly, the `resolveAttchmentField($root)` function of the `MetaAttachmentType` is being executed and the proper result is returned, however, it does not show up in the response for the query.

`attachment` is defined like this in `MetaAttachmentType`:

```php
'attachment' => [
    'description' => 'A file or location that might be associated with this person',
    'type' => GraphQL::type('MetaAttachment`)
]
```

And this is `MetaAttachmentUnion`:

```php
class MetaAttachmentUnion extends UnionType
{

    // Tried setting this to true as it's not done in the parent UnionType but it made no difference
    protected $unionType = true;

    protected $attributes = [
        'name' => 'MetaAttachment',
        'description' => '.....'
    ];

    public function types() // This is being executed and it returns the correct result
    {
        return [
            GraphQL::type('File'),
            GraphQL::type('Location'),
        ];
    }

    public function resolveType($value) // This function is never reached
    {
        switch(get_class($value))
        {
            case Location::class:
                return GraphQL::type('Location');
                break;
            case File::class:
                return GraphQL::type('File');
                break;
 
        }

        return null;
    }
}
```

As can be seen by the comments, the `types()` function is run during the execution of the query and returns the proper result, but the `resolveType($value)` function is not. It's not like none of the switch cases is hit and it returns the default `null`, but the function is actually never reached. I found this odd as the `resolveAttachmentField()` function in the parent type is actually hit.

When I look at UnionType I can see that it's been implemented in 1 commit and there are no tests. Also, setting `$unionType` is overlooked and doesn't seem to be doing anything. Is it possible that this implementation doesn't actually work? I'll be happy to work on it if I can be pointed in the right direction but currently I don't really know where to look. Let me know if I need to provide any other details.

Thanks for the help in advance

**Comment by Roemerb** [comment]
Never mind, I'm an idiot and forgot a `return` somewhere. It actually works fine. Annoying how something like this can leave one frustrated for many hours. Anyway, the `$unionType` property of `UnionType` still does not seem to be doing anything, so I guess it can be removed or used for the introspection of unions.

**Comment by sowork** [comment]
@Roemerb I have the same problem, can you tell me exactly where to return what？

**Comment by mfn** [comment]
> Anyway, the `$unionType` property of `UnionType` still does not seem to be doing anything, so I guess it can be removed or used for the introspection of unions.

That was actually done in https://github.com/rebing/graphql-laravel/commit/914512ff80d4787d063aeb6ba41f4b8db2ad6241 (but I wasn't ware of your comment though…)

>  I have the same problem, can you tell me exactly where to return what？

Can you provide source code / samples and the error / stack trace you have?
