### ISSUE TITLE
Eloquent mutators

### ISSUE THREAD

**Issue by damcclean** [rebing/graphql-laravel#235]
Hey,

I'm trying to setup this package in one of my Laravel applications. On one of my models I have this mutator which get's the user's gravatar image.
```
public function getGravatarAttribute()
    {
        $hash = md5(strtolower(trim($this->attributes['email'])));
        return "https://www.gravatar.com/avatar/$hash";
    }
```

How can I access what this returns within my query and type?

**Comment by mfn** [comment]
If you define a "field" gravatar, it should automagically work, doesn't it?

Alternatively, depending on your use case, you can add a custom resolver and resolving to `$model->gravatar` yourself.

**Comment by damcclean** [comment]
Thanks for your response!

I'll try it out and let you know if it works :)
