### ISSUE TITLE
Schema is not configured for mutations error occurs while using mutations 

### ISSUE THREAD

**Issue by sooriyan** [rebing/graphql-laravel#237]
Unable to update using mutations due to the error, Although included in Schema
```
'schemas' => [
        'default' => [
            'query' => [
                'articles' => App\GraphQL\Query\ArticlesQuery::class,
            ],
            'mutation' => [
                'updatearticle' => UpdateArticle::class
            ],
            'middleware' => [],
        ],
    ]
```

**Comment by rebing** [comment]
Please specify the error and show the entire `config/graphql.php` file

**Comment by sooriyan** [comment]
Error : 
```
{
  "errors": [
    {
      "message": "Schema is not configured for mutations.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
```

Config/graphql.php:


use example\Mutation\ExampleMutation;
use example\Query\ExampleQuery;
use example\Type\ExampleRelationType;
use example\Type\ExampleType;
use App\GraphQL\Type\Articlestype;

return [
    'prefix' => 'graphql',
    'routes' => '{graphql_schema?}',
    'controllers' => \Rebing\GraphQL\GraphQLController::class . '@query',
    'middleware' => [],
    'route_group_attributes' => [],
    'default_schema' => 'default',
    'schemas' => [
        'default' => [
            'query' => [
                'articles' => App\GraphQL\Query\ArticlesQuery::class,
            ],
            'mutation' => [
                'updatearticle' => App\GraphQL\Mutation\UpdateArticleMutation::class
            ],
            'middleware' => [],
            'method' => ['get', 'post'],
        ],
    ],
    'types' => [
        'articles' => Articlestype::class,
    ],
    'error_formatter' => ['\Rebing\GraphQL\GraphQL', 'formatError'],
    'errors_handler' => ['\Rebing\GraphQL\GraphQL', 'handleErrors'],
    'params_key'    => 'variables',
    'security' => [
        'query_max_complexity' => null,
        'query_max_depth' => null,
        'disable_introspection' => false
    ],
    'pagination_type' => \Rebing\GraphQL\Support\PaginationType::class,
    'graphiql' => [
        'prefix' => '/graphiql/{graphql_schema?}',
        'controller' => \Rebing\GraphQL\GraphQLController::class.'@graphiql',
        'middleware' => [],
        'view' => 'graphql::graphiql',
        'display' => env('ENABLE_GRAPHIQL', true),
    ],
];

**Comment by masih1376** [comment]
yes , i have this problem too @sooriyan 
if you can resolve this problem, tell me please

**Comment by masih1376** [comment]
i cant understand it, i create new laravel project and install this package and copy&paste graphql queries and mutations from my older project , its worked !!!
but in main project it  doesn't work and give me this error 
why ?

**Comment by masih1376** [comment]
@sooriyan i clear my laravel cache and now every things is ok !! 
php artisan config:clear 
php artisan cache:clear

**Comment by sooriyan** [comment]
Thank you brother it worked
