### ISSUE TITLE
Support mongodb in SelectFields

### ISSUE THREAD

**Issue by hoatructhanhlam** [rebing/graphql-laravel#240]
I'm using laravel + mongodb with package laravel-mongodb of jenssegers [https://github.com/jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb)
I am having problems with eager-loading, because of the relation in mongodb other with library of illuminate.
Can this package support further mongodb relations?

**Comment by rebing** [comment]
Please specify your problem

**Comment by hoatructhanhlam** [comment]
```
 public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
 {
        // $info->getFieldSelection($depth = 3);
        
        $select = $fields->getSelect();
        $with = $fields->getRelations();
        
        $users = User::select($select)->with($with);
        
        return $users->get();
}
```
$fields always return null because relation classes in mongodb are diffirent sql which was defined in Illuminate\Databases\Eloquent\Relations\

**Comment by rebing** [comment]
Yes, looking at the Mongodb package it seems that we don't support these types of relations. I'm not sure what the ideal solution would be here

**Comment by WilliamPeralta** [comment]
@rebing the problem are field names, with mongo cannot use the table name in field like post.title , post.description, but need names like (title, description, ecc).

can implement a optional parameter in  $fields->getSelect(); ?? for example

`$fields->getSelect($tablePrefix);`

PD. sorry for my very bad english :D

**Comment by rebing** [comment]
#257
