### ISSUE TITLE
How to define a recursive query

### ISSUE THREAD

**Issue by alive1944** [rebing/graphql-laravel#241]
a `folder` table, with `parent_dir_id` in table, l don't know what depth it is, l define a type like (with only important fields):

```
class Folder extends ExtendType
{
    protected $attributes = [
        'name' => 'Folder',
        'description' => 'A type',
        'model' => \App\Model\Folder::class,
    ];

    public function fields()
    {
        return [
            'folder_id' => [
                'type' => Type::int(),
                'description' => 'ID',
            ],
            'folder_name' => [
                'type' => Type::string(),
                'description' => 'name',
            ],
            'parent_dir_id' => [
                'type' => Type::int(),
                'description' => 'parent id',
            ],
            'parent_folder' => [
                'type' => \Graphql::type('Folder'),
                'description' => 'parent folder',
            ],
        ];
    }
}
```

and l have defined relation in model:

```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children_folder()
    {
        return $this->hasMany(Folder::class, 'parent_dir_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent_folder()
    {
        return $this->belongsTo(Folder::class, 'parent_dir_id');
    }
```

then run it, program broken. did l define type with wrong way?

update:
broken means: always loading at graphiql view

**Comment by rebing** [comment]
You have to define it with the local key, if the primary key is not `id`. As it looks your table has a `folder_id` primary key instead.
```
return $this->hasMany(Folder::class, 'parent_dir_id', 'folder_id');
```

**Comment by alive1944** [comment]
> You have to define it with the local key, if the primary key is not `id`. As it looks your table has a `folder_id` primary key instead.
> 
> ```
> return $this->hasMany(Folder::class, 'parent_dir_id', 'folder_id');
> ```

emmmm... thank you for answer so much, but l have been define the primary key when l create Folder Model.

```
class Folder extends Model
{
    use SoftDeletes;

    const DELETED_AT = 'time_delete';
    protected $dates = ['time_delete'];


    protected $table = 'folder';
    protected $primaryKey='folder_id';

    const CREATED_AT = 'time_create';
    const UPDATED_AT = 'time_update';

    protected $dateFormat = 'U';

    protected $guarded = [];

```
And l tried to define local key, and still broken, the server return me 502 Bad GateWay(the same to before)

![FF406E7C-8DC3-4070-B8D7-D31442365348](https://user-images.githubusercontent.com/21339652/56026740-6cbe9000-5d47-11e9-8050-46827a354430.png)


and if l comment these code
```
'parent_folder' => [
       'type' => \Graphql::type('Folder'),
        'description' => 'parent folder',
],
```

it become work again

**Comment by rebing** [comment]
Check your logs (in `storage/logs` probably) for details

**Comment by alive1944** [comment]
Unfortunately... there were no logs in log path..l was sure that log system is working. it can generate log with error trackback. but when l tried to define recursive construct, then run it and the server return 500/502 status code. there were no any logs generate in log path

**Comment by mfn** [comment]
Hey @alive1944 ,

I'm going to close this, because from what I gather there's no sign yet it's an issue with the library?

My understanding is that you haven't been able to correctly establish the relations between your models which is basically necessary to use them anywhere else => also with this library.

I believe there are better places which can help you with that.

I'm happy to reopen if you can provide more information which relate to a bug in the library!
