### ISSUE TITLE
Generator for types, mutations and queries

### ISSUE THREAD

**Issue by slaxxarn** [rebing/graphql-laravel#242]
Hi!
Since folklore/graphql is no longer maintained, my package has no use (https://github.com/dalnix/laravel-graphql-generator).  It would be nice if you could build in the same functionality in this package. I don't have time updating my package to work with yours right now and I think most people would appreciate to be able to create mutations, types and queries from the CLI instead of manually creating them (saves ALOT of time, specially in larger projects).

If your package is built upon folklore it shouldn't be that much work.

**Comment by rebing** [comment]
Hi, feel free to implement it to this package and create a PR!

**Comment by pxgamer** [comment]
@slaxxarn, is this not the same as the commands that are already in this package?
https://github.com/rebing/graphql-laravel/tree/master/src/Rebing/GraphQL/Console

- `make:graphql:mutation`
- `make:graphql:query`
- `make:graphql:type`

**Comment by slaxxarn** [comment]
@pxgamer Kinda similar, but with my package you can, for example, import all fields in the database directly in the Type when creating a new Type. And while creating a mutation you can import the GraphQL\Types you already created. See this file https://github.com/dalnix/laravel-graphql-generator/blob/master/src/commands/GenerateType.php

@rebing Might do that if time is available in the future :)

**Comment by pxgamer** [comment]
@slaxxarn, oh! That's pretty neat. 👍

**Comment by slaxxarn** [comment]
@pxgamer Also, you don't need to do anything in the scheme (config file), the package makes this in the service provider automagically.

But I close this issue now and if i have time i'll do a PR.
