### ISSUE TITLE
Trim args

### ISSUE THREAD

**Issue by Dream5561** [rebing/graphql-laravel#248]
Can I add a trim method before checking the rules?
Before writing to the database, I pass some arguments through the trim and make a record, and if there are only spaces in the string, an empty string is obtained, and if the string is empty through the resolver, I give an error. It would be nice to add some properties to the arguments that would allow using for example trim before checking validations.

Current code:
```
    public function args()
    {
        return [
            'username' => [
                'type' => Type::nonNull(Type::string()),
                'rules' => ['string', 'min:4', 'max:64'],
            ]
        ];
    }

    public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {
        $username = trim($args['username']);

        if (empty($username)) {
            //validation error
        }
        //...
    }
```

It would be nice if it were like that. 👍 

```
    public function args()
    {
        return [
            'username' => [
                'type' => Type::nonNull(Type::string()),
                'rules' => ['string', 'min:4', 'max:64'],
                'is_trim' => true
            ]
        ];
    }

    public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {
        //code...
    }
```

**Comment by rebing** [comment]
Try to use `'required'` as a rule. If that doesn't help then I think you can trim it by adding a `rules(array $args)` function to the Class (check this https://github.com/rebing/graphql-laravel#adding-validation-to-a-mutation)

**Comment by Dream5561** [comment]
`required ` really works, but there are times when need to add trim to optional arguments, and it would be nice to add this function to the current package.
