### ISSUE TITLE
Resolvers not working for non-scalar properties

### ISSUE THREAD

**Issue by swinyx** [rebing/graphql-laravel#25]
If an object has some properties that have been defined using accessors (inside a model) instead of an eloquent relationship, and those properties do return the expected object class or an expected collection of objects. This GraphQL package is not able to map those objects as it is expecting an eloquent query builder class

**Comment by rebing** [comment]
Have you tried setting the `selectable` property?

https://github.com/rebing/graphql-laravel#creating-a-query

**Comment by swinyx** [comment]
Oh, I have not seen that option. I will definitely check it out.
Thank you so much
