### ISSUE TITLE
Current version doesn't support Laravel 5.2

### ISSUE THREAD

**Issue by whytewolf-ca** [rebing/graphql-laravel#252]
I recently tried migrating from folkloreinc/laravel-graphql and found the most recent version of rebing/graphql-laravel doesn't support versions of Laravel < 5.5; as I'm not in a position to upgrade my Laravel version at the moment, I had to install rebing/graphql-laravel version 1.16 instead (as it still supported illuminate/support of version < 5.5).  For what I'm using it for currently, this seems to be working as expected.

I would suggest noting in the readme the requirement for Laravel 5.5 as currently it only notes Laravel 5.x as a depedency.

**Comment by rebing** [comment]
#256
