### ISSUE TITLE
array_get is deprecated and will be removed in Laravel 5.9

### ISSUE THREAD

**Issue by JakeBooher** [rebing/graphql-laravel#254]
Not sure if this is the only similar issue, but just found this while replacing the validator `Rebing\GraphQL\Support\Field`  with our custom version while attempting to upgrade from the old Folklore extension. All of the array_* helpers have been replaced with the `Illuminate\Support\Arr` util class

**Comment by mfn** [comment]
See https://github.com/rebing/graphql-laravel/pull/263

**Comment by rebing** [comment]
#263
