### ISSUE TITLE
Security issue, looking for contact with the maintainer

### ISSUE THREAD

**Issue by Sobak** [rebing/graphql-laravel#255]
Hello @rebing 

sorry for this rather inconvenient way of contacting you, I'm aware it causes a kind of disclosure which I'd like to avoid. I was trying to contact you using the email (not sure where exactly did I find it, though) but to no avail - maybe the one I found was dead or my message ended up in a spam, I'm not sure.

Nonetheless, I have discovered what I believe to be a security issue in the package. I would be very grateful if you could reach back to me so we could get in touch and talk about it.

Thanks for the understanding!

**Comment by rebing** [comment]
@Sobak Send me an email to mikk_nurges@hotmail.com
