### ISSUE TITLE
Custom context overwritten with SelectFields class

### ISSUE THREAD

**Issue by mfn** [rebing/graphql-laravel#258]
Trying to migrate from Folklore I face the problem that I'm using a custom `Context` being passed as the 3rd argument which is overwritten in `\Rebing\GraphQL\Support\Field::getResolver`.

At this point `$arguments[2]` is my custom Context class I need for the request:
```php
        return function() use ($resolver, $authorize)
        {
            $arguments = func_get_args();
```
but a few lines later, this happens:
```php
            // Replace the context argument with 'selects and relations'
            // $arguments[1] is direct args given with the query
            // $arguments[2] is context (params given with the query)
            // $arguments[3] is ResolveInfo
            if(isset($arguments[3]))
            {
                $fields = new SelectFields($arguments[3], $this->type(), $arguments[1]);
                $arguments[2] = $fields;
            }
```
The comment even mentions the context, but it overwrites it.

I don't mind the `SelectFields` approach and acknowledge it's usefulness, but every (also non-PHP) server-side GraphQL implementation I've seen so far uses the same argument pattern "root, args, context, resolver info", thus overwriting this seems a bit odd.

What is the recommended way to have the context available, too?

Should I override `\Rebing\GraphQL\Support\Field::getResolver`?

**Comment by rebing** [comment]
I agree that it should not be replaced in such a way and SelectFields should instead be the 5th argument. If you can override the `getResolver` then it's probably your best option right now

**Comment by mfn** [comment]
@rebing would you be open to fix this, considering it's a breaking change, for a possible `2.*` release?
