### ISSUE TITLE
Input Object Type (Validation Rules) & Input Object Type name collision

### ISSUE THREAD

**Issue by swinyx** [rebing/graphql-laravel#26]
#FIRST ISSUE

When am creating a mutation that receives the following (where id a the top level is required, while id at the nested object is sometimes required, the top level validation fails unless I renamed the inner object 'id' key to something else.

Also, how to set validation rules for input object type args ?

For example, I am trying to mutate an object with the following 3 properties (1 property is an input object type)
id - required (Int)
name -sometimes required (String)
subjects - sometimes required(InputObjectType), but if present{
 - id (sometimes required)
- name (required)

}

`
{
  "id": 1,
  "name": "Samle Content 1",
  "subjects": [
    {
      "id": : 1,
      "name": "Sample content 2",
    },
    {"name": "Sample Content 3"}
  ]
}`

My args() and rules() function in the mutation looks like the following. However I am not sure where to specify the validation rules for the InputObjectType

`
public function args(){

		return [
					'id' => [
						'name' => 'id',
						'type' => Type::int(),
					],
					'name' => [
						'name' => 'name',
						'type' => Type::string(),
					],
					'subjects' => [
						'name' => 'subjects',
						'type' => Type::listOf(new InputObjectType([
									    'name' => 'UpdateClassroomSubjectInput',
									    'fields' => [
									        'id' => [
									            'type' => Type::int(),
									            'description' => 'The id of the subject'
									        ],
									        'name' => [
									            'type' => Type::string(),
									            'description' => 'The name of the subject'
									        ]
									    ]
									]))
					]

					//'subjects' => Type::listOf( new \App\GraphQL\InputTypes\ClassroomSubjectInputType)

				];
	}`

`	
public function rules(){

		return [
					'id' => [
						'required'
					],
					'name' => [
						'sometimes',
						'required'
					],
					'subjects' => [
						'sometimes',
						'required'
//How to specify the nested object validation rules here ? Or should I simply validate them in the resolver ?

					]
				];
	}
`

#SECOND ISSUE

It doesn't seem there is a way to create a class name for input object types and reuse them in different mutations ( just like the field classes), The config file has no options to provide a list of input object types that can be loaded in the schema ( like the types or mutation list)

**Comment by rebing** [comment]
1. I think it can currently only be done in the resolver. I think it can be solved by passing the $args into the rules($args). Feel free to make a PR, if you create a solution.

2. I've solved it by creating a new class that extends the InputObjectType and passing a unique name every time:

```
class SubjectsInputType extends InputObjectType {

    public function __construct($name)
    {
        parent::__construct([
            'name' => $name . '_custom',
            'fields' => [...],
        ]);
    }

}
```

and call this in the mutation:

```
class SubjectsMutation extends Mutation {

    ...

    'subjects' => [
        'name' => 'subjects',
        'type' => Type::listOf(new SubjectsInputType('subjects'))
    ]

    ....

}
```

**Comment by rebing** [comment]
#35 Should be working now

**Comment by illambo** [comment]
Hello, someone have some example on how validate with rules an _Input Object Type_ ?
Thanks

**Comment by yannick-yeboue-fm** [comment]
@illambo , you can validate those in the rules function. since the data would turn into nested array, try to validate it as an array / nested array. 

Check the laravel documentation about validating arrays here
https://laravel.com/docs/5.6/validation#validating-arrays

For example, let say you have a post and you are passing category ids as well where $post['categories']['ids'] is an array of integers.

```
    public function rules(array $args = [])
    {
        return [
            'id' => [
                'sometimes',
                'numeric',
                'exists:posts,id'
            ],
            'categories.ids.*' => [ //validate each element in a nested array, use dots to traverse the array
                'numeric',
            ]
        ];
    }
```

**Comment by swinyx** [comment]
@illambo , you can validate those in the rules function. since the data would turn into nested array, try to validate it as an array / nested array. 

Check the laravel documentation about validating arrays here
https://laravel.com/docs/5.6/validation#validating-arrays

For example, let say you have a post and you are passing category ids as well where $post['categories']['ids'] is an array of integers.

```
    public function rules(array $args = [])
    {
        return [
            'id' => [
                'sometimes',
                'numeric',
                'exists:posts,id'
            ],
            'categories.ids.*' => [ //validate each element in a nested array, use dots to traverse the array
                'numeric',
            ]
        ];
    }
```

**Comment by illambo** [comment]
This is not my case, for shared I mean that it also shares the rules (for me is usefull for polymorphic relation and other cases).
Interesting, seems folkloreatelier has already [managed](https://github.com/Folkloreatelier/laravel-graphql/blob/develop/src/Folklore/GraphQL/Support/Traits/ShouldValidate.php) that.
I deepen, meanwhile, thank you.

**Comment by swinyx** [comment]
So it does work then?

**Comment by illambo** [comment]
Your suggest work but in my opinion Folkloreatelier repo give a better support about that (maybe later i try to implement a pull request).
