### ISSUE TITLE
Unable to customize default field resolver

### ISSUE THREAD

**Issue by mfn** [rebing/graphql-laravel#260]
Coming from Folklore, I witnesses the following missing feature:

In `config/graphql.php` it's possible to define a custom field resolver:
```php
    /*
     * Overrides the default field resolver
     * Useful to setup default loading of eager relationships
     *
     * Example:
     *
     * 'defaultFieldResolver' => function ($root, $args, $context, $info) {
     *     // take a look at the defaultFieldResolver in
     *     // https://github.com/webonyx/graphql-php/blob/master/src/Executor/Executor.php
     * },
     */
    'defaultFieldResolver' => [Your::class, 'fieldResolver'],
```
This is supported by the following code in `\Folklore\GraphQL\GraphQL::queryAndReturnResult`:
```php
        $defaultFieldResolver = config('graphql.defaultFieldResolver', null);
…
        $result = GraphQLBase::executeQuery($schema, $query, $root, $context, $variables, $operationName, $defaultFieldResolver);
```
I'm not using it for eager loading of relations but use an optimized version which performs less attribute getter calls on Eloquent models.

**Comment by rebing** [comment]
The `SelectFields` class should do that work for you in this package by only selecting the fields that are required

**Comment by mfn** [comment]
I'm aware about that, but the default behaviour for objects _nevertheless_ is to perform:
- __isset (which, for Eloquent, in the end calls `$this->getAttribute(…)`
- __get (which calls `$this->getAttribute(…)`, too)

See default webonxy resolver from `\GraphQL\Executor\Executor::defaultFieldResolver`:
```php
        } elseif (is_object($source)) {
            if (isset($source->{$fieldName})) {
                $property = $source->{$fieldName};
            }
        }
```

This is quite unnecessary for any kind of Eloquent model, merely calling `$source->{$fieldName}` is enough and the equivalent outcome.

Would you be open to accept a PR for this feature?
