### ISSUE TITLE
Testing question

### ISSUE THREAD

**Issue by ZaidBarghouthi** [rebing/graphql-laravel#261]
Whats the proper way to test my types, queries, and mutations?

I just do feature tests but is there a way to unit test the classes?

Thanks.

**Comment by mfn** [comment]
Personally I use integration tests, using existing Laravel testing features to dispatch internal HTTP calls and evaluate the result.

This ensures it goes through the complete stack (middleware, GraphQL, database) but of course makes things slower.

**Comment by ZaidBarghouthi** [comment]
That's what I do as well, is there another way?

**Comment by mfn** [comment]
I keep complex logic of resolvers (query/mutation/sometimes fields) in dedicated repository classes and thus test them on their own.
