### ISSUE TITLE
Option to disable GraphiQL routes (or make it optional in general)

### ISSUE THREAD

**Issue by satyago** [rebing/graphql-laravel#269]
I recently wanted to move from GraphiQL to GraphQL Playground and noticed that the GraphiQL page was still showing; threw me off a bit.

I could of course change the service provider precedence and override the route, but I'd prefer not to.

Are you guys planning on potentially moving away from it being part of this package, or should I help out and add the config options to make it optional?

**Comment by mfn** [comment]
Did you check the following?
 https://github.com/rebing/graphql-laravel/blob/e4141ca0dae6f16d52f733f327a09a345aa59390/src/config/config.php#L168-L174

You should be able to simply disable it with this config or an environment variable. Does this work for you?

**Comment by satyago** [comment]
Oh !
I wish config files would auto-merge …  😞 
Thank you - my bad !
