### ISSUE TITLE
Missing import in GraphQLController

### ISSUE THREAD

**Issue by satyago** [rebing/graphql-laravel#270]
The `Arr` facade import got removed at some point.

https://github.com/rebing/graphql-laravel/commit/0c749d564cb6b5ed7b955659aa23df7671217a2c#r33618736

**Comment by c0necto** [comment]
yup, this import is missing in the current version, which breaks the package completely. 

temporary fix: re-add it in src/Rebing/GraphQL/GraphQLController.php
```
<?php

namespace Rebing\GraphQL;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Arr;
```

**Comment by rebing** [comment]
10169b1
