### ISSUE TITLE
How can I use distinct rule validation 

### ISSUE THREAD

**Issue by albertcito** [rebing/graphql-laravel#279]
[**distinct**](https://laravel.com/docs/5.8/validation#rule-distinct)

When working with arrays, the field under validation must not have any duplicate values.

`'foo.*.id' => 'distinct'`

becuase the validation is in this way: 

`'rules' => ['required', 'array', 'distinct']`

**Comment by mfn** [comment]
I don't think it's possible with validation rules that way.

The input arguments are not per se nested in a structure like you would need for the `distinct` rule, if I understand it correctly.

You could try these things:
1. override `getRules` => do call the parent but append your own logic
2. use custom code/logic in your `resolve` methods => you have access to `$args` and can use it in any way you seem fit to process it

With 1) you add more rules which get passed to the validator used within the library.

With 2) it's up to you how you do it. You can also the validator approach or any other way which fits you.
