### ISSUE TITLE
Alias is not working with me! 

### ISSUE THREAD

**Issue by ZaidBarghouthi** [rebing/graphql-laravel#280]
The following is not working with me. It might be doing something wrong, I am not absolutely certain. I'm getting `null` when querying the field. 

```php
public function fields()
{
    return [
        ...
        'createdAt' => [ 
            'type' => Type::string(),
            'description' => 'The created at timestamp',
            'alias' => 'created_at', 
        ],
        ...
    ];
}
```

but the following is working fine
```php
public function fields()
{
    return [
        ...
        'createdAt' => [ 
            'type' => Type::string(),
            'description' => 'The created at timestamp',
            'resolve' => function($type) { return $type->created_at; }, 
        ],
        ...
    ];
}
```

Am I missing something?

**Comment by EdwinDayot** [comment]
Hi,

Did you try the following ?

```php
public function fields()
{
    return [
        ...
        'createdAt' => [ 
            'type' => Type::string(),
            'description' => 'The created at timestamp',
            'alias' => 'created_at',
            'resolve' => function($type) { return $type->created_at; }, 
        ],
        ...
    ];
}
```

The `alias` is necessary for the query (for instance: `select created_at from ...`), the `resolve`function gets the aliased field from the Eloquent instance.

**Comment by mfn** [comment]
I guess the case could be made that when providing the `alias`, the default behaviour would be to also return it (unless a custom resolver like above is provided)?

**Comment by EdwinDayot** [comment]
Since it can be confusing, it would probably be a good idea

**Comment by ZaidBarghouthi** [comment]
> Hi,
> 
> Did you try the following ?
> 
> ```
> public function fields()
> {
>     return [
>         ...
>         'createdAt' => [ 
>             'type' => Type::string(),
>             'description' => 'The created at timestamp',
>             'alias' => 'created_at',
>             'resolve' => function($type) { return $type->created_at; }, 
>         ],
>         ...
>     ];
> }
> ```
> 
> The `alias` is necessary for the query (for instance: `select created_at from ...`), the `resolve`function gets the aliased field from the Eloquent instance.

Yes. It works, but its works just as well without `alias`!. So I'm not sure what is the proper use for alias!

**Comment by EdwinDayot** [comment]
Are you selecting specific fields in your `Query`? Or are you selecting `*`?

**Comment by ZaidBarghouthi** [comment]
not sure how the following is translated into SQL >>
```gql
{
  userById(id: 17) {
    id
    audits(limit:4){
      data{
        id
        createdAt // here <----
        event
        oldValues
        newValues
        user {
          id
          name
        }
      }
    }
  }
}
```

**Comment by EdwinDayot** [comment]
Depends of your `Query` resolver, I mean your PHP `Query`, the one your registered in `config/graphql.php`

**Comment by ZaidBarghouthi** [comment]
this?

```php
class UserByIdQuery extends Query
{
    protected $attributes = [
        'name' => 'userById',
        'description' => 'Get the user by their ID'
    ];

    public function type()
    {
        return GraphQL::Type('user');
    }

    public function args()
    {
        return [
            'id' => [
                'name' => 'id',
                'type' => Type::nonNull(Type::id()),
            ],
        ];
    }

    public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {
        // $select = $fields->getSelect();
        // $with = $fields->getRelations();

        return User::find($args['id']);
    }
}
```

**Comment by ZaidBarghouthi** [comment]
I see, so when use `->select($selectedFields)` alias should be set correctly. so let me get this straight! In my case I should have `alias` and `resolve`?

**Comment by EdwinDayot** [comment]
Exactly !

**Comment by ZaidBarghouthi** [comment]
Ok, Last question, I saw in `README.md` an example where `'alias' => 'user_id'` for an `id` field without a resolver. where may I have an alias without a resolver?

**Comment by ZaidBarghouthi** [comment]
> I guess the case could be made that when providing the `alias`, the default behaviour would be to also return it (unless a custom resolver like above is provided)?

@mfn I think I understand now, 

perhaps there should be a check [here](https://github.com/rebing/graphql-laravel/blob/74699b56a09ed9407fd4e3cfda90535b4bd7ddb3/src/Rebing/GraphQL/Support/Type.php#L35) to add a resolver 
```php
    protected function getFieldResolver($name, $field)
    {
        if (isset($field['resolve'])) {
            return $field['resolve'];
        }
        $resolveMethod = 'resolve'.Str::studly($name).'Field';
        if (method_exists($this, $resolveMethod)) {
            $resolver = [$this, $resolveMethod];
            return function () use ($resolver) {
                $args = func_get_args();
                return call_user_func_array($resolver, $args);
            };
        }
    }
    public function getFields()
    {
        $fields = $this->fields();
        $allFields = [];
        foreach ($fields as $name => $field) {
            if (is_string($field)) {
                $field = app($field);
                $field->name = $name;
                $allFields[$name] = $field->toArray();
            } elseif ($field instanceof FieldDefinition) {
                $allFields[$field->name] = $field;
            } else {
                $resolver = $this->getFieldResolver($name, $field);
                if ($resolver) {
                    $field['resolve'] = $resolver;
                }
                $allFields[$name] = $field;
            }
        }
        return $allFields;
    }
```

**Comment by mfn** [comment]
PRs appreciated 😄

**Comment by ZaidBarghouthi** [comment]
You got it man, I just understood whats happening :)
