### ISSUE TITLE
Custom fields problem

### ISSUE THREAD

**Issue by vestervang** [rebing/graphql-laravel#29]
I have a problem with custom fields as the title says. I have tried to create a Image field, like in the docs

```php
class ImageField extends Field {
        
  protected $attributes = [
	public function args()
	{
		return [
			'width' => [
				'type' => Type::int(),
				'description' => 'Path to the image',
			],
			'height' => [
				'type' => Type::int(),
				'description' => 'Path to the image',
			]
		];
	}
	
	protected function resolve($root, $args)
	{
		$width = isset($args['width']) ? $args['width']:100;
		$height = isset($args['height']) ? $args['height']:100;

		return 'http://placehold.it/'.$width.'x'.$height;
	}
        
}
```

My problem is; How do i pass arguments to this class? I can't find an example of how this is done in the docs.

Thanks in advance.

**Comment by rebing** [comment]
What do you mean by arguments? I have actually never used the Custom Fields myself, these came from the Folklore package.

**Comment by vestervang** [comment]
Ah yeah i might have been a bit vague. How do i pass something to the $args array in the resolve function.

**Comment by rebing** [comment]
I think these $args are the same as in Query and Mutation? Which means they are passed along with the request. Not sure though, as I've never used the Custom Field

**Comment by vestervang** [comment]
I just tried that and it didn't work, sadly. I have opened an issue at the Folklore package; https://github.com/Folkloreatelier/laravel-graphql/issues/171
