### ISSUE TITLE
Correct repo in packagist and install guide in Readme.md

### ISSUE THREAD

**Issue by myrzz0r** [rebing/graphql-laravel#3]
What is the current version of the repository in https://packagist.org/packages/rebing/graphql-laravel ?
Why at packagist.org written:

> composer require rebing / graphql-laravel

http://take.ms/bv7tD and it works fine..

But in Readme.md of https://github.com/rebing/graphql-laravel :

> {
>    "Require": {
>      "Rebing / graphql": "^ 1.0"
>    }
> }

Composer can not find the package "Rebing / graphql"

**Comment by rebing** [comment]
The Readme was incorrect, I fixed it now. Thanks!

**Comment by myrzz0r** [comment]
About first my question.
When I installed the package, i noticed that some files, like /Rebing/GraphQL/Support/PaginationType.php, are missing from the github repository.
Therefore had to clone the repository from github mannualy.
