### ISSUE TITLE
TypeMakeCommand does not exist

### ISSUE THREAD

**Issue by kasperbisgaard** [rebing/graphql-laravel#30]
When i try to push the configuration with:
php artisan vendor:publish --provider="Rebing\GraphQL\GraphQLServiceProvider"

I get the error:
[ReflectionException]
Class Rebing\GraphQL\Console\TypeMakeCommand does not exist

I'm using laravel framework 5.4

**Comment by vestervang** [comment]
I can't seem to replicate this error. Is it a new Laravel project you try to add this package to?

**Comment by kasperbisgaard** [comment]
It seems to work with a new installation. 
I have no idea how to debug what's wrong.

**Comment by rebing** [comment]
Running `composer dumpautoload` would have probably fixed it

**Comment by smallcar88** [comment]
Hello @rebing , I have experienced the same issue. But neither `composer dumpautoload` or reinstall fix the problem of `Class Rebing\GraphQL\Console\TypeMakeCommand does not exist `. Do you have further suggestions ? Thank you!

**Comment by nc-kab** [comment]
`composer dumpautoload` did not help me either.
I had to create a new project and move all my models and controllers etc into that project.

**Comment by rebing** [comment]
#35 Should be working now
