### ISSUE TITLE
Type nesting occurs for n+1 queries

### ISSUE THREAD

**Issue by sowork** [rebing/graphql-laravel#310]
I query:
```php
{
    "query": "{users{id name email, blogs{id text comments{id desc}}}}"
}
```
UsersQuery.php
```php
    public function resolve($root, $args, SelectFields $fields)
    {
        $where = function ($query) use ($args) {
            if (isset($args['id'])) {
                $query->where('id', $args['id']);
            }

            if (isset($args['email'])) {
                $query->where('email', $args['email']);
            }
        };
        $users = User::with(array_keys($fields->getRelations()))
            ->where($where)
            ->select($fields->getSelect())
            ->get();

        return $users;
    }
```
When I query the comments list through my blog,I found that an n+1 query occurred for commnet

I BlogType.php
```php
class BlogType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Blogs',
        'description' => 'A comment',
        'model' => Blog::class,
    ];

    // define field of type
    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'The id of the comment'
            ],
            'userId' => [
                'type' => Type::int(),
                'description' => 'The userId of comment'
            ],
            'text' => [
                'type' => Type::string(),
                'description' => 'text'
            ],
            'comments' => [
                'type' => Type::listOf(GraphQL::type('comments')),
                'description' => 'The desc of the comment'
            ],
        ];
    }

}
```
This type cannot be preloaded. How can I use it?

This is the SQL that was executed
```sql
select `users`.`id`, `users`.`name`, `users`.`email` from `users` 
select * from `blogs` where `blogs`.`userId` in (1, 2) 
select * from `comments` where `comments`.`blogId` = 1 and `comments`.`blogId` is not null  
select * from `comments` where `comments`.`blogId` = 2 and `comments`.`blogId` is not null
```

**Comment by mfn** [comment]
Can you paste me the output of `(array_keys($fields->getRelations())`, e.g. via `var_dump()`?

**Comment by sowork** [comment]
```
array(1) {
  ["blogs"]=>
  object(Closure)#641 (2) {
    ["static"]=>
    array(3) {
      ["with"]=>
      array(1) {
        ["comments"]=>
        object(Closure)#637 (2) {
          ["static"]=>
          array(3) {
            ["with"]=>
            array(0) {
            }
            ["select"]=>
            array(3) {
              [0]=>
              string(11) "comments.id"
              [1]=>
              string(13) "comments.desc"
              [2]=>
              string(15) "comments.blogId"
            }
            ["customQuery"]=>
            NULL
          }
          ["parameter"]=>
          array(1) {
            ["$query"]=>
            string(10) "<required>"
          }
        }
      }
      ["select"]=>
      array(3) {
        [0]=>
        string(8) "blogs.id"
        [1]=>
        string(10) "blogs.text"
        [2]=>
        string(12) "blogs.userId"
      }
      ["customQuery"]=>
      NULL
    }
    ["parameter"]=>
    array(1) {
      ["$query"]=>
      string(10) "<required>"
    }
  }
}
```

**Comment by sowork** [comment]
i check `Rebing\GraphQL\Support\Type::class  getFieldResolver()`
```
protected function getFieldResolver($name, $field)
    {
        if(isset($field['resolve']))
        {
            return $field['resolve'];
        }

        $resolveMethod = 'resolve'.studly_case($name).'Field';

        if(method_exists($this, $resolveMethod))
        {
            $resolver = array($this, $resolveMethod);
            return function() use ($resolver)
            {
                $args = func_get_args();
                return call_user_func_array($resolver, $args);
            };
        }
        
        return null;
    }
```
Means that if I don't define the resolve method, he will do lazy loading, such as: `$user->blogs`,This leads me to an n+1 problem

however,`Rebing\GraphQL\Support\Field::class getResolver()` Is not consistent with the above return from the getResolve method?  He returned a selectFeild

**Comment by mfn** [comment]
Why are you wrapping `$fields->getRelations()` in `array_keys()` in the `UsersQuery::resolve()` method?

**Comment by sowork** [comment]
Consider the following query
```
{
    "query": "{users(id:1){id name email, blogs(createdAt:\"2019/06/06\"){id text comments{id desc}}}}"
}
```
UsersType.php
```
class UsersType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Users',
        'description' => 'A type',
        'model' => User::class, // define model for users type
    ];

    // define field of type
    public function fields()
    {
        return [
            'id' => [
                'type' => Type::int(),
                'description' => 'The id of the user'
            ],
            'email' => [
                'type' => Type::string(),
                'description' => 'The email of user'
            ],
            'name' => [
                'type' => Type::string(),
                'description' => 'The name of the user'
            ],
            'blogs' => [
                'type' => Type::listOf(GraphQL::type('blogs')),
                'args' => [
                    'id' => [
                        'type' => Type::int()
                    ],
                    'createdAt' => [
                        'type' => Type::string()
                    ]
                ],
                'query' => function ($args, $query) {
                    if (!empty($args['createdAt'])) {
                        return $query->where('createdAt', '2019-06-06 10:13:30');
                    }
                    return $query;
                },
            ]
        ];
    }
}
```
Currently the `blogs` field query query `$args` is empty,query cannot be restricted

`$fields->getRelations()` I can't get enough results at this point 
If you do not use `array keys()`, the SQL is as follows:
```
select `users`.`id`, `users`.`name`, `users`.`email` from `users` where (`id` = 1)
select `blogs`.`id`, `blogs`.`text`, `blogs`.`userId` from `blogs` where `blogs`.`userId` in (1)
select `comments`.`id`, `comments`.`desc`, `comments`.`blogId` from `comments` where `comments`.`blogId` in (1)
```
So I can only preload the first layer of data and customize the `blogs` field `resovle()` method

**Comment by mfn** [comment]
Do you have the n+1 problem if you _not_ use `array_keys` (ignoring the wrong result for now)?

**Comment by sowork** [comment]
Will not appear，The n+1 problem occurs because there is no preloading. It happens that the field name and the association relationship are consistent, which causes the lazy loading to be triggered.

**Comment by mfn** [comment]
> Will not appear

Can you please clarify: do you mean, without `array_keys`, you have a n+1 problem or not?

> it happens that the field name and the association relationship are consistent

I don't understand this sentence, can you please clarify?

Nevertheless:

I've created https://github.com/rebing/graphql-laravel/pull/313 which features an example with the query depth; it features 4 variants but they are currently not all working because they need a fix from https://github.com/rebing/graphql-laravel/pull/292

I'm getting mixed results on local testing. For one, in my current test case, the `'query'` is entirely ignored and have yet to understand why.

Also, I'm not always seeing proper eager loading.

Will investigate further and report back; clarifications appreciated.

**Comment by sowork** [comment]
1. No `array_keys()` will not cause `n+1` problems
2. User.php
```
class UserModel {
    public function blogs()
    {
        return $this->hasMany(Blog::class, 'userId', 'id');
    }
}
```
`UsersType fields()` with `blogs` fields，
If don't use `array_keys()`

I guess he did the following:
```
$user = User::all();
$user->blogs
```

**Comment by mfn** [comment]
Thank you!

**Comment by mfn** [comment]
> Currently the `blogs` field query query `$args` is empty,query cannot be restricted

I someone missed this information the first time!

Not sure if you can qualify it outright as a bug, looking at the SelectFields implementation it's evident that the code never considered `$args` on nested GraphQL type fields.

I don't think this is related to the n+1 issue, thus I created a separate report to track this => https://github.com/rebing/graphql-laravel/issues/314 .

**Comment by mfn** [comment]
Ok, to sum it up why I said:
> I don't think this is related to the n+1 issue

[You wrote:](https://github.com/rebing/graphql-laravel/issues/310#issuecomment-499328244)
>  If you do not use array keys(), the SQL is as follows:
> ```
> select `users`.`id`, `users`.`name`, `users`.`email` from `users` where (`id` = 1)
> select `blogs`.`id`, `blogs`.`text`, `blogs`.`userId` from `blogs` where `blogs`.`userId` in (1)
> sselect `comments`.`id`, `comments`.`desc`, `comments`.`blogId` from `comments` where `comments`.`blogId` in (1)
> ```

That is the crux: eager loading and avoiding the dreaded n+1 problems *works correctly* when you  pass the result of `$selectFields->getRelations()` to `with()`.

But you have another requirement: `'query'` with args on a nested GraphQL types field. And because this doens't work (the $args you received were empty) you started using the `array_keys()` approach.

Not sure why this would fix the query/args issue but this **definitely breaks correct eager loading**.

It was a bit hard to understand this because in your initial report you didn't reveal the query/args information and it only later turned out to be related to this.

For all I saw and tested, SelectFields does correctly eager load nested relations but your attempt to workaround the query/args bug lead to a incorrect use of the eager loading and thus the n+1 issue.

I'm closing this bug because it mostly talks about n+1 issues when in fact this is not the actual problem

=> please follow https://github.com/rebing/graphql-laravel/issues/314 to track the fix for query/args . 

I prefer a new report which focuses on a single piece, it's easier to discuss.

Many thanks for your report!
