### ISSUE TITLE
SelectFields: $args on sub-fields are not considered in custom 'query' configuration

### ISSUE THREAD

**Issue by mfn** [rebing/graphql-laravel#314]
GraphQL query:
```graphql
users {
  posts(flag: true) {
    id
  }
```
UserType:
```php
    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::ID()),
            ],
            'name' => [
                'type' => Type::nonNull(Type::string()),
            ],
            'posts' => [
                'type' => Type::nonNull(Type::listOf(Type::nonNull(GraphQL::type('Post')))),
                'args' => [
                    'flag' => [
                        'type' => Type::boolean(),
                    ],
                ],
                'query' => function ($args, $query) {
                    if (isset($args['flag'])) {
                        $query->where('posts.flag', '=', true);
                    }

                    return $query;
                },
            ],
        ];
    }
```
The `$args` passed to the `'query'` is the $args from the **root** object and thus will always be empty in this case => effectively it's not possible to access this information and adapt the query accordingly.

Currently, SelectFields only stores the args when constructing the class:
```php
    public function __construct(ResolveInfo $info, $parentType, array $args)
    {
        if ($parentType instanceof WrappingType) {
            $parentType = $parentType->getWrappedType(true);
        }

        if (! is_null($info->fieldNodes[0]->selectionSet)) {
            self::$args = $args;

            $fields = self::getSelectableFieldsAndRelations($info->getFieldSelection(5), $parentType, null, true, $args);

            $this->select = $fields[0];
            $this->relations = $fields[1];
        }
    }
```
Due to this, the `self::$args` used everywhere else is only the one from the root type and outright ignores any sub-field `$args`.

The constructor also receives `ResolveInfo $info` which is used like this:
```php
$info->getFieldSelection(5)
```
This returns a nested data structure of all the types/fields/sub-types etc. requested and can look like this:
```php
array (
  'id' => true,
  'name' => true,
  'posts' => 
  array (
    'body' => true,
    'id' => true,
    'title' => true,
    'comments' => 
    array (
      'body' => true,
      'id' => true,
      'title' => true,
    ),
  ),
)
```
The problem at hand: whilst `getFieldSelection` returns the fields, it doesn't return possible arguments.

Without this information, it's not possible to fix this.

**Comment by sowork** [comment]
Can use the regular parsing query statement to get the parameters?

**Comment by mfn** [comment]
I intend to work on a fix for this but the essential solution is to extract the arguments from the `ResolveInfo $info` the resolver receives by traversing the nodes.

That is, the solution is to implement something like `\GraphQL\Type\Definition\ResolveInfo::getFieldSelection` which however not only returns the fields but also the arguments.

This will then be incorporated into SelectFields for the fix.

I don't have a quick fix solution for except to:
- not use SelectFields
- parse the `ResolveInfo $info` yourself like I suggested
- construct the `with` clauses yourself based on the data you retrieve

**Comment by crissi** [comment]
I have already made a fix for this in a project at work, I could make a PR within a couple of days

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Markus Podar <notifications@github.com>
Sendt: Monday, June 10, 2019 9:33:10 PM
Til: rebing/graphql-laravel
Cc: Subscribed
Emne: Re: [rebing/graphql-laravel] SelectFields: $args on sub-fields are not considered in custom 'query' configuration (#314)


I intend to work on a fix for this but the essential solution is to extract the arguments from the ResolveInfo $info the resolver receives by traversing the nodes.

That is, the solution is to implement something like \GraphQL\Type\Definition\ResolveInfo::getFieldSelection which however not only returns the fields but also the arguments.

This will then be incorporated into SelectFields for the fix.

I don't have a quick fix solution for except to:

  *   not use SelectFields
  *   parse the ResolveInfo $info yourself like I suggested
  *   construct the with clauses yourself based on the data you retrieve

**Comment by mfn** [comment]
> I have already made a fix for this in a project at work, I could make a PR within a couple of days

PRs welcome 👍

**Comment by mfn** [comment]
I've added a test `\Rebing\GraphQL\Tests\Database\SelectFields\NestedRelationLoadingTests\NestedRelationLoadingTest::testQuerySelectAndWithAndSubArgs` which is expected to break (read: needs to be adapted) when this bug is fixed. It's expected that the SQL query and obviously the expected result differs.
