### ISSUE TITLE
Laravel 5.4 MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by bboyvlad** [rebing/graphql-laravel#32]
Hi @rebing , please i need some help. i'm getting a "MethodNotAllowedHttpException" when i tried to make a query. i have check over and over the documentation and i can't find the possible mistake that is causing this Exception.

i was able to get GraphQL working this plugin https://github.com/Folkloreatelier/laravel-graphql and with Django+Graphene, but each time i try with this one, i get the same error.

On the file "conf/app.php", i added this on the "providers" array:
Rebing\GraphQL\GraphQLServiceProvider::class,
 and this to the "aliases" array:
'GraphQL' => Rebing\GraphQL\Support\Facades\GraphQL::class,

this is my UsersQuery.php:
`<?php

namespace App\GraphQL\Query;

use App\User;
use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ResolveInfo;
use Rebing\GraphQL\Support\SelectFields;
use Rebing\GraphQL\Support\Query;
use Rebing\GraphQL\Support\Facades\GraphQL;

class UsersQuery extends Query
{
    protected $attributes = [
        'name' => 'UsersQuery',
        'description' => 'A query'
    ];

    public function type()
    {
        return Type::listOf(GraphQL::type('user'));
    }

    public function args()
    {
        return [
            'id' => [
                'name' => 'id',
                'type' => Type::string()
            ],
            'username' => [
                'name' => 'username',
                'type' => Type::string()
            ],
            'email' => [
                'name' => 'email',
                'type' => Type::string()
            ]
        ];
    }

    public function resolve($root, $args, SelectFields $fields, ResolveInfo $info)
    {
        if(isset($args['id']))
        {
            return User::where('id' , $args['id'])->get();
        }
        else if(isset($args['username']))
        {
            return User::where('username', $args['username'])->get();
        }
        else if(isset($args['email']))
        {
            return User::where('email', $args['email'])->get();
        }
        else
        {
            return User::all();
        }
    }
}`

this is my UsersType.php:
`<?php

namespace App\GraphQL\Type;

use App\User;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Facades\GraphQL;
use Folklore\GraphQL\Support\Type as GraphQLType;

class UsersType extends GraphQLType
{
    protected $attributes = [
        'name' => 'UsersType',
        'description' => 'A User type',
		'model' => User::class,
    ];

    public function fields()
    {
        return [
            'id' => [
				'type' => Type::nonNull(Type::string()),
				'description' => 'The id of the user'
			],
			'username' => [
				'type' => Type::string(),
				'description' => 'The username of user'
			],
			'email' => [
				'type' => Type::string(),
				'description' => 'The email of user'
			],
			'first_name' => [
				'type' => Type::string(),
				'description' => 'The first_name of user'
			],
			'last_name' => [
				'type' => Type::string(),
				'description' => 'The last_name of user'
			],
        ];
    }

    // If you want to resolve the field yourself, you can declare a method
	// with the following format resolve[FIELD_NAME]Field()
	protected function resolveEmailField($root, $args)
	{
		return strtolower($root->email);
	}

} `

My graphql configuration is like this:

`<?php

use App\GraphQL\Query\UsersQuery;
use App\GraphQL\Type\UsersType;

return [

    'prefix' => 'graphql',

    'routes' => '{graphql_schema?}',

    'controllers' => \Rebing\GraphQL\GraphQLController::class . '@query',

    'middleware' => [],

    'default_schema' => 'default',

    'schemas' => [
        'default' => [
            'query' => [
                'users' => UsersQuery::class
            ],
            'mutation' => [
            ],
            'middleware' => []
        ],
    ],
    
    'types' => [
        'user' => UsersType::class
    ],
    
    'error_formatter' => ['\Rebing\GraphQL\GraphQL', 'formatError'],

    'params_key'    => 'params',
    
];`

if someone sees somethng wrong please let me know! 

thanks in advance for any help

**Comment by MrJmpl3** [comment]
Send the request to [http://yourdomain/prefix/route] for example mi domain is testgraph

I send request to http://testgraph.dev/graphql

Method POST
Header: Content-Type: application/json
Body: 
{
 "query" : "yourquery"
}

And send .. I can use Graqli or PostMan for testing

**Comment by bboyvlad** [comment]
hi @MrJmpl3 you nailed it, perfect help :+1: . no mention about it in the documentation by the way or at least i missed it.

i end it up fixing a line that referenced other plugin on my UserType definition  :
```
use Folklore\GraphQL\Support\Type as GraphQLType;   -->  
use Rebing\GraphQL\Support\Type as GraphQLType;
```

And I send request to http://test.dev/graphql
Method POST
Header: Content-Type: application/json
Body:
{
"query" : "query FetchUsers{users{id,email}}"
}

and i works just fine!!
