### ISSUE TITLE
Laravel's custom rules are not working on rules function of a mutation.

### ISSUE THREAD

**Issue by ephraimlambarte** [rebing/graphql-laravel#321]
### Versions:
- graphql-laravel Version: 1.22
- Laravel/Lumen Version: 5.8.*
- PHP Version: 7.1.3

### Question:
I created a custom rule for my validation and applying it on rules function of a mutation doesnt work.

code:
```
public function rules(array $args = []) {
        return [
              'name' => [
                    'unique:msp_branches,name,'.$args['id'], 
                    new EmptyStringRule   //custom rule
              ]
        ];
}
```

**Comment by mfn** [comment]
Can you check if the answer in https://github.com/rebing/graphql-laravel/issues/187 helps?

**Comment by ephraimlambarte** [comment]
i dont think it helps, because my custom rule only checks if the value is an empty string or not. 

I also tried using closures but still no luck.

```
 public function rules(array $args = []) {
        return [
            'name' => [
                'unique:msp_branches,name,'.$args['id'], 
                function ($attribute, $value, $fail) {
                    if (!$value) {
                        $fail($attribute.' is invalid.');
                    }
                },
            ]
        ];
    }
```

**Comment by mfn** [comment]
Does the closure / your class get even called, can you debug this?

**Comment by ephraimlambarte** [comment]
I tried using dd() function on the closure and on the 'passes' function of my class, it doesnt get called.

**Comment by mfn** [comment]
I can't reproduce this.

I made https://github.com/rebing/graphql-laravel/pull/322 to specifically test with a closure and a Rule Object, both worked as expected.

Please look at the changes, maybe you can see why it's not working for you _or_ if the tests don't properly reflect _your_ scenario.

Note the change is in `master` which is not the same as the v1 release, but I'm not aware of any changes regarding validation processing.

**Comment by ephraimlambarte** [comment]
I noticed something weird, when i changed the  value of 'name' in my graphql request to fail the first validation: `unique:msp_branches,name,'.$args['id']` it also calls the rule object.

**Comment by mfn** [comment]
Are you saying:
- if `unique` passes, the Role Object is **not** called
- if `unique` fails, the Role Object **is** called

?

**Comment by ephraimlambarte** [comment]
yup, both `unique` and the rule object is called.

**Comment by ephraimlambarte** [comment]
I did some debugging and i think the problem is in the Validator class used in getResolver function of Rebing\Graphql\Support\Field class.

<pre>
protected function getResolver()
    {
        if (! method_exists($this, 'resolve')) {
            return;
        }

        $resolver = [$this, 'resolve'];
        $authorize = [$this, 'authorize'];

        return function () use ($resolver, $authorize) {
            $arguments = func_get_args();

            // Get all given arguments
            if (! is_null($arguments[2]) && is_array($arguments[2])) {
                $arguments[1] = array_merge($arguments[1], $arguments[2]);
            }

            // Authorize
            if (call_user_func($authorize, $arguments[1]) != true) {
                throw with(new AuthorizationError('Unauthorized'));
            }

            // Validate mutation arguments
            if (method_exists($this, 'getRules')) {
                $args = Arr::get($arguments, 1, []);

                $rules = call_user_func_array([$this, 'getRules'], [$args]);

                if (count($rules)) {

                    // allow our error messages to be customised
                    $messages = $this->validationErrorMessages($args);

                    $validator = Validator::make($args, $rules, $messages);
                    
                  //<b> validator->fails() is not failing even when it should fail because of custom rule object</b>
                    
                   if ($validator->fails()) {
                        throw with(new ValidationError('validation'))->setValidator($validator);
                    }
                }
            }

            // Replace the context argument with 'selects and relations'
            // $arguments[1] is direct args given with the query
            // $arguments[2] is context (params given with the query)
            // $arguments[3] is ResolveInfo
            if (isset($arguments[3])) {
                $fields = new SelectFields($arguments[3], $this->type(), $arguments[1]);
                $arguments[2] = $fields;
            }

            return call_user_func_array($resolver, $arguments);
        };
    }
</pre>

**Comment by mfn** [comment]
Thanks, I wrote a couple more tests in https://github.com/rebing/graphql-laravel/pull/322 and saw the problem you described => looks like a bug to me.

If it gets fixed, there are at least two tests which are expected to fail / need adaption.

**Comment by mfn** [comment]
Sorry for the forth and back, I managed to write broken tests at the most important points.

Anyway, I've created three kind of test classes. All test `union` or `in` together with a custom rule object:
- `\Rebing\GraphQL\Tests\Unit\LaravelValidatorTests\LaravelValidatorTest`
  Laravel native validation, just serve as blueprint what is to expected; not really related to this library after all
- `\Rebing\GraphQL\Tests\Unit\MutationValidationInWithCustomRulesTests\MutationValidationInWithCustomRulesTest`
- `\Rebing\GraphQL\Tests\Database\MutationValidationUniqueWithCustomRulesTests\MutationValidationUniqueWithCustomRulesTest`

All of those each contain 4 test methods, variations of this pattern:
1. first rule pass, role object pass
2. first rule pass, role object fail
3. first rule fail, role object pass
4. first rule fail, role object fail

IMHO the result of all of them looks correct. Only 1) returns the mutation, all other the validation errors.

Can you check the tests if I missed something to replicate your problem?

**Comment by ephraimlambarte** [comment]
Hello Sir @mfn , please try adding : 
```
'arg_rule_fail' => [
                'type' => Type::string(),
            ]
```  
as additional argument on MutationWithCustomRuleWithRuleObject.php
with a rule of: 

```
 'arg_rule_fail' => [
                new RuleObjectFail(),
            ],
```
and try creating a mutation with empty string for a test case:

```
    public function testFailRule() {

$graphql = <<<'GRAPHQL'
mutation Mutate($arg_rule_fail: String) {
mutationWithCustomRuleWithRuleObject(arg_rule_fail: $arg_rule_fail)
}
GRAPHQL;

        $this->sqlCounterReset();

        $result = GraphQL::query($graphql, [
        'arg_rule_fail' => '',
        ]);

        $this->assertArrayHasKey('errors', $result);  //result must have errors since there is a RuleObjectFail 
                                                                             //object on rules of `arg_rule_fail
    }
```

**Comment by mfn** [comment]
Thanks for the clarification.

What you're describing is the expected behavior of the Laravel validation.

Custom validations using `Validator::extend` or rule objects implementing `\Illuminate\Contracts\Validation\Rule` are **skipped** for empty attributes.

To still have them applied, you need to use `Validator::extendImplict` or implement the `\Illuminate\Contracts\Validation\ImplicitRule` interface.

Please read up the chapter about [Implicit Extensions](https://laravel.com/docs/5.8/validation):
> By default, when an attribute being validated is not present or contains an empty string, normal validation rules, including custom extensions, are not run.
…
> For a rule to run even when an attribute is empty, the rule must imply that the attribute is required. To create such an "implicit" extension, use the Validator::extendImplicit() 

Unfortunately the docs don't mention that this is also possible/available for rule objects => I've created https://github.com/laravel/docs/pull/5237 to clarify this.

[I've found a source](https://www.google.com/search?hl=en&q=laravel%20rule%20object%20extend%20implicit) which describes this quite practically: https://laravel-news.com/custom-validation-rule-objects (but I understand you have to be even ware this concept exists to notice it).

**Comment by fidele5** [comment]
hi, i am using GraphQL and have created several Types (Type files) and Query (Query files) but the changes I make to them do not work. I am using the Laravel framework. Any help will be of great use to me

**Comment by fidele5** [comment]
> salut, j'utilise GraphQL et j'ai créé plusieurs types (fichiers de type) et requêtes (fichiers de requête) mais les modifications que j'y apporte ne fonctionnent pas. J'utilise le framework Laravel. Toute aide me sera d'une grande utilité

I get this error : 
chema must contain unique named types but contains multiple types named \"Vehicule\" (see http://webonyx.github.io/graphql-php/type-system/#type-registry
