### ISSUE TITLE
How to limit eager loading of Eloquent relations?

### ISSUE THREAD

**Issue by dharkness** [rebing/graphql-laravel#361]
### Versions:

- graphql-laravel Version: 1.22.0
- Laravel Version: 5.5.45
- PHP Version: 7.2.19

### Question:

I have a simple hierarchical model with three levels: makes, models, and years. I originally created types and queries for each level, but that doesn't provide the full benefits of GraphQL—specifically the graph nature. I rebuilt the top-level `MakesQuery` to inspect the `ResolveInfo` object and eager load `models` and `years` as needed, but I cannot figure out how to limit the subqueries.

```graphql
query {
  makes(make: "audi") {
    id
    models(model: "a4") {    # How do I get this arg in MakesQuery::resolve()?
      id
      rating
      yearModels(year: 2016) {    # ...and this one
        id
        rating
      }
    }
  }
}
```
Using `MakeType::resolveModelsField()` doesn't allow eager loading. I tried adding a `query` entry to the relation in `MakeType`, but it doesn't get the correct query parameters (`model: "a4"` above), only the top-level `make` parameter. Also, returning `$query` from it loads the correct data from the database, but the graph returns an empty list.

```php
'models' => [
    'type' => Type::listOf(GraphQL::type('Model')),
    'description' => 'The models belonging to the make',
    'args' => [
        'model' => ['type' => Type::string()],
    ],
    'query' => function (array $args, $query) {
        if (isset($args['model'])) {
            return $query->where('model_name', $args['model']);
        }
        else {
            return $query;
        }
    },
],
```
Now that I've added the Eloquent models to the types, it seems to be partly working. I removed my hand-coded eager loading from `MakesQuery::resolve()`.
```php
public function resolve($root, $args, SelectFields $fields, ResolveInfo $info) {
    $where = function ($query) use ($args) {
        if (isset($args['make'])) {
            return $query->where('make_name', $args['make']);
        }
        else {
            return $query;
        }
    };
    $select = $fields->getSelect();
    $with = $fields->getRelations();
    $makes = Make
        ::with($with)
        ->where($where)
        ->select($select)
        ->get();
    return $makes;
}
```

**Comment by dharkness** [comment]
I think I found my mistake: not specifying the `model` type attributes. My original implementation didn't use Eloquent so I didn't need it, and I didn't think to add it when migrating to Eloquent. I've added them and am trying again.

**Comment by dharkness** [comment]
I've found two issues that I'll report separately now that I have this mostly working.

**Comment by mfn** [comment]
> I think I found my mistake: not specifying the `model` type attributes. My original implementation didn't use Eloquent so I didn't need it, and I didn't think to add it when migrating to Eloquent. I've added them and am trying again.

Thanks for the details!

Do you think there's something in the docs which can be cleared up/improved? Would be happy to receive PRs!

**Comment by dharkness** [comment]
While a more complex Eloquent example would be helpful, I don't see how the docs could have been any more clear about the `model` property. The problem was that I switched to Eloquent after getting the queries and types working without it.

**Comment by dharkness** [comment]
Just in case someone else duplicates my mistake, here's my complete working solution:

```php
use App\Models\Make;
use GraphQL;
use GraphQL\Type\Definition\Type;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Rebing\GraphQL\Support\Type as GraphQLType;

class MakeType extends GraphQLType
{
    protected $attributes = [
        'name'          => 'Make',
        'description'   => 'A vehicle make',
        'model'         => Make::class,
    ];

    public function fields(): array {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'The ID of the make',
            ],
            // ... more fields ...

            'models' => [
                'type' => Type::nonNull(Type::listOf(Type::nonNull(GraphQL::type('Model')))),
                'description' => 'The models belonging to the make',
                'args' => [
                    'id' => ['type' => Type::int()],
                    'slug' => ['type' => Type::string()],
                ],
                'query' => function (array $args, HasMany $query) {
                    if (isset($args['id'])) {
                        return $query->where('id', $args['id']);
                    }
                    elseif (isset($args['slug'])) {
                        return $query->where('slug', $args['slug']);
                    }
                    else {
                        return $query;
                    }
                },
            ],
        ];
    }
}
```
