### ISSUE TITLE
$customQuery in type's fields() config gets wrong $args

### ISSUE THREAD

**Issue by dharkness** [rebing/graphql-laravel#365]
### Versions:

- graphql-laravel Version: 1.22.0
- Laravel Version: 5.5.45
- PHP Version: 7.2.19

### Description:

The `$args` passed to an Eloquent relation closure defined in a type's `fields()` function are those for the top-level query instead of the args on the relation itself in the GraphQL query—the ones passed to the field resolver function.

This is related to #361.

### Steps To Reproduce:

1. Create types and Eloquent models to support this query of a simple parent-child model with a one-to-many relation:

```graphql
query {
    parents(name: "bob") {
        name
        children(minAge: 25) {
            name
        }
    }
}
```

2. Define a `query` for the `children` field on the `Parent` type to get eager loading.

```php
class ParentType extends Type {
    protected $attributes = [
        'name'          => 'Parent',
        'model'         => Parent::class,
    ];
    public function fields() {
        return [
            ...
            'children' => [
                'type' => Type::listOf(GraphQL::type('Child')),
                'args' => [
                    'minAge' => ['type' => Type::int()],
                ],
                'query' => function (array $args, $query) {    // WRONG: $args = ['name' => 'bob']
                    if (isset($args['minAge'])) {
                        return $query->where('age', '>=', $args['minAge']);
                    }
                    else {
                        return $query;    // and so the subquery is not limited, loading too many rows
                    }
                },
            ],
        ];
    }
}
```

### Workaround:

1. Add a custom field resolver for the relation. This may be the intended solution, but it means we end up loading much more data than necessary.

```php
class ParentType extends Type {
    ...
    public function resolveChildrenField($root, $args) {    // RIGHT: $args = ['minAge' => 25]
        if (isset($args['minAge'])) {
            return $root->children->where('age', '>=', $args['minAge']);
        }
        else {
            return $root->children;
        }
    }
}
```

2. Since the data is loaded before calling the field resolver, you are forced to also add `age` to the GraphQL query so it can be used by the `where` call.

```graphql
query {
    parents(name: "bob") {
        name
        children(minAge: 25) {
            name
            age    # required by field resolver
        }
    }
}
```

**Comment by mfn** [comment]
This was fixed with https://github.com/rebing/graphql-laravel/pull/327 recently but only in master which will eventually become v2 of this library (no ETA at this point).

**Comment by dharkness** [comment]
Sweet, it works. Thank you so much!
