### ISSUE TITLE
Could you provide an example of how to pull raw queries instead of Eloquent

### ISSUE THREAD

**Issue by nyalex** [rebing/graphql-laravel#39]
I want to use GraphQL to be layer on top of our existing REST based API. In this setup we have to write raw queries that includes complex business logic. 

Could you provide an example of how I can setup this library to run standard queries using `DB::raw()` (or equivalent)?

**Comment by rebing** [comment]
What do you mean? Just return whatever you want in the Query/Mutation `resolve()` function. It can come from Eloquent or DB or it doesn't even have to interact with the database.

**Comment by nyalex** [comment]
You're saying to do something like this?

```
class ClickQuery extends Query {

...

public function resolve($root, $args)
{
		return DB::table('click')
                 ->select(DB::raw('user_id, count(distinct click.id) as click_count'))
                 ->join('user', 'user.id', '=', 'click.user_id')
                 ->groupBy('user_id')
                 ->get();
}
```

If I do that, how do I relate it to other querys? Please look at this query.

```
{
  "query": "{user{id, email, first_name, clicks{click_count}}}"
}
```

How can it connect into the UserQuery in this? There is no relation since it is outside of Eloquent.

**Comment by nyalex** [comment]
I guess what I am asking is how do I setup relations in the Type file if I am not using Eloquent?

**Comment by rebing** [comment]
If you're not using Eloquent, then just omit the `model` property from the Type's `$attributes`. But this way you obviously cannot create relations to other tables

**Comment by nyalex** [comment]
So there is no way to create the parent/child query in the POST without using Eloquent?

Example: 

```
{
  "query": "{ users {id, email, first_name, profile {id, twitter_url, facebook_url, modified} } }"
}
```

**Comment by rebing** [comment]
It's possible, by just returning an array, for example:

```
return [
    'id' => 1,
    'email' => 'example@ex.com',
    'profile' => [
        'id' => 1,
        ...
    ],
    ...
];
```

But you also have to set `'selectable' => false` for each field

**Comment by nyalex** [comment]
Thanks. So just to confirm, if we were going to query the DB (without Eloquent) we would need to build that multi-dimensional array? Something like this (pseudo-ish code)?

```
$db_rows = DB::table('user')
     ->select(DB::raw('id, twitter_url'))
     ->join('profile', 'profile.id', '=', 'user.profile_id')
     ->get();

$db_rows = $db_rows->toArray();

$response = array();
$n = 0;

foreach ($db_rows as $row) {

     $response[$n]['id'] = $row['id']; // Parent element

     $response[$n]['profile']['twitter_url'] = $row['twitter_id']; // Child element

     $n++;

}

return $response;
```

I just want to confirm that this would be the best practice in this kind of scenario.

**Comment by rebing** [comment]
Yes, this would work (no need for even `$db_rows->toArray()` as you can iterate over a Collection with foreach)

**Comment by nyalex** [comment]
Awesome - thanks so much for your help.
