### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by ephraimlambarte** [rebing/graphql-laravel#395]
### Versions:
- graphql-laravel Version: 1.22
- Laravel/Lumen Version: 5.8
- PHP Version: 7.1.3

### Question:
Im using altair for testing my graphql mutation in file upload but i keep getting this error:

```
   exception: "GraphQL\Error\InvariantViolation"
   file: "/var/www/vendor/rebing/graphql-laravel/src/Rebing/GraphQL/GraphQLUploadMiddleware.php"
   line: 109
   message: "Request is expected to provide parsed body for "multipart/form-data" requests but got empty array"
```

i already set the content-type to: `multipart/form-data`

**Comment by mfn** [comment]
Is the output of `$request->all()` empty?

Can you try in `\Rebing\GraphQL\GraphQLUploadMiddleware::processRequest` disable this call:
```php
$this->validateParsedBody($request);
```
and see if it works?

However, as can be seen in `\Rebing\GraphQL\GraphQLUploadMiddleware::parseUploadedFiles`, it expects some keys:
```php
        $bodyParams = $request->all();
        if (! isset($bodyParams['map'])) {
            throw new RequestError('The request must define a `map`');
        }
```
It seems the request you receive does not conform to the specs, see https://github.com/jaydenseric/graphql-multipart-request-spec#multipart-form-field-structure

> map: A JSON encoded map of where files occurred in the operations. For each file, the key is the file multipart form field name and the value is an array of operations paths.

Can you debug this further?

**Comment by ephraimlambarte** [comment]
This is the payload for my request:

```
------WebKitFormBoundarysoWjOTElbDXT30ds
Content-Disposition: form-data; name="operations"

{"query":"mutation($file: Upload!) { insertCustomer (\n\n            profile_picture:$file\n            ){\n                id, first_name\n}\n}","variables":{"file":null},"operationName":null}
------WebKitFormBoundarysoWjOTElbDXT30ds
Content-Disposition: form-data; name="map"

{"0":["variables.file"]}
------WebKitFormBoundarysoWjOTElbDXT30ds
Content-Disposition: form-data; name="0"; filename="logo.PNG"
Content-Type: image/png


------WebKitFormBoundarysoWjOTElbDXT30ds--
```

I tried commenting this call:
```
$this->validateParsedBody($request);
```

and using dd() on: 
```
$request->all()
```

gives me an empty array

**Comment by mfn** [comment]
From a quick glance the payload request seems to look good and matching the spec 🤷‍♀️

**Comment by mfn** [comment]
I think there's a problem with your middleware configuration.

I tested this with `./artisan server` on a test project using `curl` and also the Altair client, and in both cases I was able to access the file data via `$args['image']->get()`.

This already implies that `$request->all()` is working correctly, which it did; sample output of `var_dump($request->all());exit(1);` inside `\Rebing\GraphQL\GraphQLUploadMiddleware::processRequest`:

```
~/src/graphql-laravel-testbed $ curl http://127.0.0.1:8000/graphql   -F operations='{ "query": "mutation ($file: Upload!) { uploadImage(image: $file) }", "variables": { "file": null } }'   -F map='{ "0": ["variables.file"] }'   -F 0=@image.png
array(3) {
  ["operations"]=>
  string(101) "{ "query": "mutation ($file: Upload!) { uploadImage(image: $file) }", "variables": { "file": null } }"
  ["map"]=>
  string(27) "{ "0": ["variables.file"] }"
  [0]=>
  object(Illuminate\Http\UploadedFile)#188 (7) {
    ["test":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=>
    bool(false)
    ["originalName":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=>
    string(9) "image.png"
    ["mimeType":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=>
    string(24) "application/octet-stream"
    ["error":"Symfony\Component\HttpFoundation\File\UploadedFile":private]=>
    int(0)
    ["hashName":protected]=>
    NULL
    ["pathName":"SplFileInfo":private]=>
    string(66) "/private/var/folders/xj/5m24dz291lv1yjh58n8nskjm0000gn/T/phpujQ4zP"
    ["fileName":"SplFileInfo":private]=>
    string(9) "phpujQ4zP"
  }
}
```
I'm closing this as I don't think there's a bug in the library; I'm happy to re-open if it turns out otherwise.

**Comment by mfn** [comment]
Small note: I used `master` version, not any v1 release. But I'm not aware of any changes in this area.

**Comment by mfn** [comment]
I've added now tests showing how the upload works (not a complete "client replacement" but should be enough to figure out where it breaks on your end) => https://github.com/rebing/graphql-laravel/pull/397/files#diff-a619cb2d801688f2e5dc5ada3d9e3e00

**Comment by ephraimlambarte** [comment]
Hello @mfn, I tried testing my mutation with a vue client using FormData: 

```
 var bodyFormData = new FormData();
      bodyFormData.set('query', `mutation($file: Upload!) { insertCustomer ( profile_picture:$file){id}}`);
      bodyFormData.set('variables', {"file": e.target.files[0]});
      bodyFormData.set('operations', '');
      bodyFormData.set('operationName', null);
      bodyFormData.set('map', JSON.stringify({"file":["variables.file"]}));
      bodyFormData.append('file', e.target.files[0]); 
```

i was able to bypass `GraphQLUploadMiddleware` but my request on `GraphQLController` contains only the file, the query is gone.
 
that is because of the `$request->replace($result);` in `parseUploadedFiles` function on `GraphQLUploadMiddleware`

**Comment by ephraimlambarte** [comment]
Hello @mfn, by doing more investigation i was able to bypass the validations in GraphQLUploadMiddleware and GraphQLController by using this specification in my formdata:

```
var bodyFormData = new FormData();
      bodyFormData.set('operations', JSON.stringify({
        'query':`mutation($file: Upload!) { insertCustomer ( profile_picture:$file){id}}`,
        'variables': {"file": e.target.files[0]}
      }));
      bodyFormData.set('operationName', null);
      bodyFormData.set('map', JSON.stringify({"file":["variables.file"]}));
      bodyFormData.append('file', e.target.files[0]);
```

its weird that my mutation is not working with altair even when i followed the instructions in the documentation.

**Comment by fidele5** [comment]
It is my first time to use QgraphQL with larave and I get this error
GraphQL\Error\InvariantViolation: Must provide name. in file C:\xampp\htdocs\blackmarket\vendor\webonyx\graphql-php\src\Utils\Utils.php on line 319

**Comment by mfn** [comment]
What version of graphql-laravel? Laravel?

Did you read through this conversation and did you check https://github.com/rebing/graphql-laravel/pull/397/files#diff-a619cb2d801688f2e5dc5ada3d9e3e00 ? I suggest to compare your request with the test,

thanks

**Comment by fidele5** [comment]
I forgot to add the right namespace in the config file

Le mer. 15 juil. 2020 à 15:50, Markus Podar <notifications@github.com> a
écrit :

**Comment by mfn** [comment]
Ok 😅 Great to hear though that you fixed it

**Comment by fidele5** [comment]
Thanks for your help

Le ven. 17 juil. 2020 à 13:46, Markus Podar <notifications@github.com> a
écrit :

**Comment by ArtemUpworker** [comment]
can you teach me how to test file upload on altair?
