### ISSUE TITLE
OPTIONS Method Not Allowed

### ISSUE THREAD

**Issue by mohammad76** [rebing/graphql-laravel#396]
### Versions:
- graphql-laravel Version: ^1.22
- Laravel/Lumen Version: 5.7
- PHP Version: 7.2.0

### Description:
Hi thanks for building this package.
I have this problem with your package , I Use All Answer but the problem still here

anyone can help me?

```
OPTIONS http://backend.mabdi.ir/graphql 405 (Method Not Allowed)
Access to XMLHttpRequest at 'http://backend.mabdi.ir/graphql' from origin 'http://mabdi.ir' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by mfn** [comment]
I'm not an expert on this topic, but I think you need an appropriate CORS middleware to respond to such requests.

As in: this needs to happen _before_ the GraphQL endpoint is actually hit (i.e. unrelated to this library).

I suggest to:
- consult https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
- take a look at https://github.com/barryvdh/laravel-cors

Don't think it's a bug in the library.
