### ISSUE TITLE
Error in installing in Laravel 5.4

### ISSUE THREAD

**Issue by pihyper** [rebing/graphql-laravel#4]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/laravel dev-master
    - rebing/graphql-laravel 1.1 requires laravel/laravel ^5.1 -> satisfiable by laravel/laravel[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.0, v5.1.1, v5.1.11, v5.1.3, v5.1.33, v5.1.4, v5.2.0, v5.2.15, v5.2.23, v5.2.24, v5.2.27, v5.2.29, v5.2.31, v5.3.0, v5.3.10, v5.3.16, v5.3.30, v5.4.0, v5.4.15, v5.4.3, v5.4.9].
    - rebing/graphql-laravel 1.1.2 requires laravel/laravel ^5.1 -> satisfiable by laravel/laravel[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.0, v5.1.1, v5.1.11, v5.1.3, v5.1.33, v5.1.4, v5.2.0, v5.2.15, v5.2.23, v5.2.24, v5.2.27, v5.2.29, v5.2.31, v5.3.0, v5.3.10, v5.3.16, v5.3.30, v5.4.0, v5.4.15, v5.4.3, v5.4.9].
    - rebing/graphql-laravel v1.1.1 requires laravel/laravel ^5.1 -> satisfiable by laravel/laravel[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.0, v5.1.1, v5.1.11, v5.1.3, v5.1.33, v5.1.4, v5.2.0, v5.2.15, v5.2.23, v5.2.24, v5.2.27, v5.2.29, v5.2.31, v5.3.0, v5.3.10, v5.3.16, v5.3.30, v5.4.0, v5.4.15, v5.4.3, v5.4.9].
    - Can only install one of: laravel/laravel[dev-master, 5.1.x-dev].
    - Can only install one of: laravel/laravel[dev-master, 5.2.x-dev].
    - Can only install one of: laravel/laravel[dev-master, 5.3.x-dev].
    - Can only install one of: laravel/laravel[v5.1.0, dev-master].
    - Can only install one of: laravel/laravel[v5.1.1, dev-master].
    - Can only install one of: laravel/laravel[v5.1.11, dev-master].
    - Can only install one of: laravel/laravel[v5.1.3, dev-master].
    - Can only install one of: laravel/laravel[v5.1.33, dev-master].
    - Can only install one of: laravel/laravel[v5.1.4, dev-master].
    - Can only install one of: laravel/laravel[v5.2.0, dev-master].
    - Can only install one of: laravel/laravel[v5.2.15, dev-master].
    - Can only install one of: laravel/laravel[v5.2.23, dev-master].
    - Can only install one of: laravel/laravel[v5.2.24, dev-master].
    - Can only install one of: laravel/laravel[v5.2.27, dev-master].
    - Can only install one of: laravel/laravel[v5.2.29, dev-master].
    - Can only install one of: laravel/laravel[v5.2.31, dev-master].
    - Can only install one of: laravel/laravel[v5.3.0, dev-master].
    - Can only install one of: laravel/laravel[v5.3.10, dev-master].
    - Can only install one of: laravel/laravel[v5.3.16, dev-master].
    - Can only install one of: laravel/laravel[v5.3.30, dev-master].
    - Can only install one of: laravel/laravel[v5.4.0, dev-master].
    - Can only install one of: laravel/laravel[v5.4.15, dev-master].
    - Can only install one of: laravel/laravel[v5.4.3, dev-master].
    - Can only install one of: laravel/laravel[v5.4.9, dev-master].
    - Installation request for laravel/laravel dev-master -> satisfiable by laravel/laravel[dev-master].
    - Installation request for rebing/graphql-laravel ^1.1 -> satisfiable by rebing/graphql-laravel[1.1, 1.1.2, v1.1.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by rebing** [comment]
I think you have the wrong version of laravel/laravel installed. It requires laravel/laravel ^5.1

**Comment by pihyper** [comment]
I'm using the latest 5.4 version.

**Comment by rebing** [comment]
Maybe it doesn't work with 5.4, I've only tried up to 5.3. Make sure you have laravel/framework (not laravel/laravel) in your main app

**Comment by pihyper** [comment]
Its  "laravel/framework": "5.4.*" in my composer.json.

**Comment by rebing** [comment]
Sorry, I'm not sure what the problem is then. I haven't tested with 5.4 yet. Try with 5.3 maybe?

**Comment by pihyper** [comment]
Please update when this issue is resolved.

**Comment by rebing** [comment]
I think the problem lies somewhere else. I pushed a new release (v1.2) and tried it with Laravel 5.4 and everything works fine.

Try `composer clear-cache`, require `"rebing/graphql-laravel": "^1.2"` and then `composer install`

**Comment by rebing** [comment]
Should be resolved now
