### ISSUE TITLE
Set default "params_key" to "variables"

### ISSUE THREAD

**Issue by niiapa** [rebing/graphql-laravel#40]
I was stuck for several hours on how to pass in dynamic variables because by default it was set to **params** when the default for most of the applications I know is **variables**.

Why not just leave it as the default which I'm assuming is **variables** considering I came from folklore's library to this and that worked fine.

Such stress. Man.

**Comment by rebing** [comment]
GraphQL Apollo uses **params**, which is why this package uses **params**
