### ISSUE TITLE
Too few arguments to function using example

### ISSUE THREAD

**Issue by jmurphy45** [rebing/graphql-laravel#404]
### Versions:
- graphql-laravel Version: 1.24
- Laravel/Lumen Version: 5.6
- PHP Version: 7.2

### Description:

- Too few arguments to function App\\Query\\UsersQuery::resolve(), 4 passed and exactly 5 expected

- I used the Type and query from the example and I am getting this error.  I used the user example from the docs 

- /graphql?query=query+FetchUsers{users{email}}

### Steps To Reproduce:

- Follow example from the docs.

**Comment by mfn** [comment]
Hi!

You're looking at the docs of the default / master branch which is already prepared for the upcoming 2.0 release: https://github.com/rebing/graphql-laravel/blob/master/Readme.md#creating-a-query

But you're using version 1.x whose documentation is in the `v1` branch => https://github.com/rebing/graphql-laravel/blob/v1/Readme.md#creating-a-query

I recommend going for the 2.0 RC3 (most recent release) which is already stable enough for production => https://github.com/rebing/graphql-laravel/releases/tag/v2.0.0-RC3
=> `composer require rebing/graphql-laravel:v2.0.0-RC3`

If you encounter any problems there with the docs, please open an issue!

Thanks

**Comment by summermick** [comment]
well, i tried v1 docs and it's more broken
` ReflectionException (-1)
Class App\GraphQL\Type\App\GraphQL\Types\UserType does not exist`

**Comment by mfn** [comment]
Why is your class name " App\GraphQL\Type\" and "\App\GraphQL\Types" ? It seems to not be imported correctly or something?

What is the full stacktrace?

Please paste your config and your type.
