### ISSUE TITLE
Args incoming to authorize method have not yet been validated

### ISSUE THREAD

**Issue by Argentum88** [rebing/graphql-laravel#407]
The `Rebing\GraphQL\Support::authorize()` method is called with arguments that have not yet been validated

### For example
I have the following code in my mutation
```php
class FooMutation extends Mutation
{
    public function authorize(array $args)
    {
        return Gate::allows('some-action', $args['bar'])
    }

    public function args()
    {
        return [
            'bar' => [
                'name' => 'bar',
                'type' => Type::nonNull(Type::string()),
                'rules' => [
                    'baz'
                ],
            ],
            //other args definition
        ];
    }

    public function resolve($root, $args)
    {
        if (Gate::allows('some-action', $args['bar'])) {
            //action
        }
    }
}
```

When a mutation will be executed with the invalid argument _bar_, then:
- method _resolve_ will not be called due to validation error (expected behavior)
- method _authorize_  will be called with an invalid _bar_ argument (unexpected behavior)

Why authorization is performed before validation?
It can be seen here https://github.com/rebing/graphql-laravel/blob/v2.0.0-RC3/src/Support/Field.php#L170-L189

**Comment by mfn** [comment]
Thanks for the detail report, this is now fixed in mater and will appear in the next v2 release/RC!
