### ISSUE TITLE
UploadType problem

### ISSUE THREAD

**Issue by drmax24** [rebing/graphql-laravel#409]
**Versions**
rebing/graphql-laraver  "v1.24.0",
Laravel 5.8, php73 (but i don't think that it is related to framework or php version)

We have an error:

Call to undefined method Rebing\GraphQL\Support\UploadType::toType()

If i specify:
```
    'types' => [
        'Upload' => \Rebing\GraphQL\Support\UploadType::class
    ],
```
inside my graphql.php

which is specified in documentation:

> You have to add the \Rebing\GraphQL\Support\UploadType first to your config/graphql schema types definition.

P.S.:
within rebing/graphql-laraver dev-master we have a different error for the same request:
Type Upload not found.

**Comment by mfn** [comment]
The documentation you quoted is from master and **only** applies to the (upcoming) 2.0 release (dev-master).

For `v1` you should use
```php
        return [
            'profilePicture' => [
                'name' => 'profilePicture',
                'type' => UploadType::getInstance(),
                'rules' => ['required', 'image', 'max:1500'],
            ],
        ];
```
as documented at https://github.com/rebing/graphql-laravel/blob/v1/Readme.md#file-uploads

#### As for master
The error is generated from `\Rebing\GraphQL\GraphQL::type` which indicates that the type is **not** added to the `types`, so I'm not sure.

There are tests in `\Rebing\GraphQL\Tests\Unit\UploadTests\UploadTest` indicating how it works, can you take a look?

**Comment by drmax24** [comment]
Thank you for the information about v1.
I think I will stick to version 2.
I have the following error at the moment:
`Variable \"$file\" of type \"Upload!\" used in position expecting type \"upload\`

Will post more info or update this post soon

**Comment by mfn** [comment]
> used in position expecting type \"upload\

That would mean that your mutation args for `file` is maybe wrong.

It's supposed to look like this:
```php
    public function args(): array
    {
        return [
            'file' => [
                'type' => GraphQL::type('Upload'),
            ],
        ];
    }
```
See also `\Rebing\GraphQL\Tests\Unit\UploadTests\UploadSingleFileMutation` used in `\Rebing\GraphQL\Tests\Unit\UploadTests\UploadTest::testSingleFile` for a self-contained example.

**Comment by drmax24** [comment]
I had it like this:
            'file' => [
                'name' => 'file',
                //'type' => GraphQL::type('Upload'),
                'type' => new UploadType('upload'),
                'rules' => ['required', /*'image',*/ 'max:1000'],
            ],

`Variable \"$file\" of type \"Upload!\" used in position expecting type \"upload\`

If i have it like this
            'file' => [
                'type' => GraphQL::type('Upload'),
            ],
 i have an error:
`Type Upload not found.
`

**Comment by mfn** [comment]
> Solved this by declared type Upload globally.
> 'Upload' => \Rebing\GraphQL\Support\UploadType::class

Exactly, this is the correct step: it's also covered in the master branch readme:
> You have to add the `\Rebing\GraphQL\Support\UploadType` first to your `config/graphql` schema types definition.
