### ISSUE TITLE
No easy way to fetch json column

### ISSUE THREAD

**Issue by Argentum88** [rebing/graphql-laravel#416]
### I have following code:

MyType.php
```php
use Rebing\GraphQL\Support\Type as GraphQLType;

class MyType extends GraphQLType
{
    protected $attributes = [
        'name' => 'MyType',
        'description' => 'My Type',
        'model' => Model::class,
    ];

    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'ID'
            ],
            'name' => [
                'type' => Type::string(),
                'description' => 'name'
            ],
            'json_data' => [
                'type' => Type::listOf(GraphQL::type('json_data')),
                'description' => 'Заполнители',
            ],
        ];
    }
}
```

JsonData.php
```php
use Rebing\GraphQL\Support\Type as GraphQLType;

class JsonData extends GraphQLType
{
    protected $attributes = [
        'name' => 'json_data',
        'description' => 'json data',
    ];

    public function fields()
    {
        return [
            'name' => [
                'type' => Type::string(),
                'description' => 'name'
            ],
            'title' => [
                'type' => Type::string(),
                'description' => 'title'
            ],
        ];
    }
}
```

Model.php
```php
use Illuminate\Database\Eloquent\Model as BaseModel;

class Model extends BaseModel
{
    protected $table = 'model';

    protected $casts = [
        'json_data' => 'array'
    ];
}
```

When I try to query MyType, I get error "Call to undefined method Model::json_data()". But json_data is not the eloquent relationship, json_data is just a column of type json.

There is a workaround for fetching column with type of json. It is necessary to configure column json_data as not selectable and handle fetching column by hand. For example adding folowing method to MyType
```php
protected function resolveJsonDataField($root, $args)
{
    return $root->json_data;
}
```

**Comment by mfn** [comment]
Are you using `SelectFields`?

**Comment by Argentum88** [comment]
Yes, of course, but control flow even not passed to the resolve method of query.

**Comment by mfn** [comment]
> When I try to query MyType, I get error "Call to undefined method Model::json_data()".

It would be helpful to have a proper stacktrace.

Anyway, PRs welcome!

**Comment by Argentum88** [comment]
I use v1

here are some of the last trace row
```
{
          "file": "/var/www/app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
          "line": 36,
          "call": "Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('json_data')"
        },
        {
          "file": "/var/www/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
          "line": 1618,
          "call": "Illuminate\\Database\\Eloquent\\Model::forwardCallTo(instance of Illuminate\\Database\\Eloquent\\Builder, 'json_data', array(0))"
        },
        {
          "call": "Illuminate\\Database\\Eloquent\\Model::__call('json_data', array(0))"
        },
        {
          "file": "/var/www/app/vendor/rebing/graphql-laravel/src/Rebing/GraphQL/Support/SelectFields.php",
          "line": 151,
          "function": "call_user_func(array(2))"
        },
        {
          "file": "/var/www/app/vendor/rebing/graphql-laravel/src/Rebing/GraphQL/Support/SelectFields.php",
          "line": 72,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::handleFields(array(2), GraphQLType: MyType, array(1), array(0))"
        },
        {
          "file": "/var/www/app/vendor/rebing/graphql-laravel/src/Rebing/GraphQL/Support/SelectFields.php",
          "line": 46,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::getSelectableFieldsAndRelations(array(2), GraphQLType: MyType)"
        },
        {
          "file": "/var/www/app/vendor/rebing/graphql-laravel/src/Rebing/GraphQL/Support/Field.php",
          "line": 190,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::__construct(instance of GraphQL\\Type\\Definition\\ResolveInfo, GraphQLType: MyType, array(2))"
        },
```

The error is most likely caused by fetching nested field (`Type::listOf(GraphQL::type('json_data'))`), which is considered by the library as eloquent relationship

**Comment by mfn** [comment]
> which is considered by the library as eloquent relationship

Any idea why?

**Comment by Argentum88** [comment]
Probably it was not supposed that in the nested field there could be something other than eloquent relationship.

**Comment by mfn** [comment]
> I use v1

I would really appreciate if you test with the upcoming 2.0 / master; v1 doesn't even have test cases that's why I try to avoid touching that code if possible.

**Comment by Argentum88** [comment]
I'm afraid sqlite (used in tests) does not support json columns.

**Comment by Argentum88** [comment]
Do you have any idea how to reproduce this in tests?

**Comment by mfn** [comment]
🤔

But does it really need to be a `JSON`/`JSONB` column? Simple `TEXT` (or whatever the SQLite equivalent) is with the cast should be enough; that only works in databases not having a dedicated json type.

**Comment by Argentum88** [comment]
Yes, most likely, you are right. All I need is to create a PR with a failed test?

**Comment by mfn** [comment]
Would be great for a start!

**Comment by Argentum88** [comment]
In fact there is no bug, here is the solution - https://github.com/rebing/graphql-laravel#json-columns

**Comment by ext-rgonzalez** [comment]
Hi, I'm busily working on a project with JSON columns, the example works perfect when we know the names of the object's keys, but:

What happens when the object is dynamic?

Here my JSON Object

```
[
  {
    "type_id": 1,
    "name": "atributo 1",
    "json1": {
      "x": 6,
      "y": 7
    },
    "json2": 
      [8,9]
    ,
    "active": 1
  }
]
```

the fields json1 and json2 are the Object's json, but this are dinamic

Thx

**Comment by mfn** [comment]
> What happens when the object is dynamic?

- if you don't know the "shape" (keys, values) => then you simply can't type it GraphQ:
- also, GraphQL does not support the concept of "Maps", i.e. returning arbitrary keys with values

Return (json) string and unserialize it on the client => because in this case, you already decided (i.e. the fact it's "dynamic") that you don't care about the types.
