### ISSUE TITLE
Cannot query field "users" on type "Query"

### ISSUE THREAD

**Issue by nozols** [rebing/graphql-laravel#420]
### Versions:
- graphql-laravel Version: 1.24.0
- Laravel/Lumen Version: 5.8.10
- PHP Version: 7.2.7

### Question:
I followed the docs on creating a query, but I cannot get it working. I keep getting the following error:
```json
{
  "errors": [
    {
      "message": "Cannot query field \"users\" on type \"Query\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

The query:
```graphql
query FetchUser{
  users{
    id
    email
  }
}
```
When i googled this issue it came up multiple times, but most of the time the poster didn't comment anymore or they simply said it was a configuration issue. Does anyone know how to fix this?

### Config
```php
 'schemas' => [
        'default' => [
            'query' => [
                'users' => App\GraphQL\Queries\UsersQuery::Class
            ],
            'mutation' => [
                // 'example_mutation'  => ExampleMutation::class,
            ],
            'middleware' => [],
            'method'     => ['get', 'post'],
        ],
 ],
'types' => [
     'user' => App\GraphQL\Types\UserType::class
],
```

### UserType
```php
<?php

namespace App\GraphQL\Types;

use App\User;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Type as GraphQLType;

class UserType extends GraphQLType
{
    protected $attributes = [
        'name' => 'User',
        'description' => 'A user',
        'model' => User::class,
    ];

    public function fields() : array
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'The id of the user'
            ],
            'email' => [
                'type' => Type::string(),
                'description' => 'The email of the user',
            ],
        ];
    }
}
```

### Query
```php
<?php

namespace App\GraphQL\Queries;

use Closure;
use App\User;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Query;

class UsersQuery extends Query
{
    protected $attributes = [
        'name' => 'Users query'
    ];

    public function type() : Type
    {
        return Type::listOf(GraphQL::type('user'));
    }

    public function args() : array
    {
        return [
            // No aruments
        ];
    }

    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectedFields)
    {
        return Users::all();
    }
}
```

**Comment by mfn** [comment]
>```
>    protected $attributes = [
>        'name' => 'Users query'
>    ];
>```

_That_ `$name` is supposed to be `users` and likely should not contain a space. Try that please and see if it works.

> "Cannot query field \"users\" on type \"Query\"."

I think this gives it away: `Query` is the [GraphQL root object type for queries](https://graphql.github.io/graphql-spec/June2018/#sec-Query) and it says it can't find `users`, ergo the query, although registered, has the wrong name.

**Comment by nozols** [comment]
Nope, sadly that doesn't fix it...

**Comment by mfn** [comment]
Everything I see here is supposed to work (unless I missed some mini detail, but by and large it's correct).

Please post a example repo with the full app which reproduces the issue; preferable with master/v2 (see released) and not v1.

**Comment by nozols** [comment]
I found the issue. It was because of an caching problem. I needed to run `php artisan config:cache` to clear the config cache, so it would be updated correctly.

**Comment by erikkaplun** [comment]
Perhaps the README could point out the necessity of running `php artisan config:cache`?

**Comment by mfn** [comment]
I'm not overly fond of this idea, because the Laravel docs cover this pretty well:
- you should only cache in production
- if you cache in production, you have to do it on deployment

=> https://laravel.com/docs/6.x/deployment

I don't want to sound, uhm…cocky?, but I consider people understanding how Laravel itself works the bare minimum. Also if that procedure on Laravels behalf might change in the future, we would have to think about this etc.

All in all, not something I consider should be part of a "Laravel library", especially the library itself isn't doing anything out of the ordinary in that regard.

**Comment by erikkaplun** [comment]
Alright, fair enough.  I simply landed in a Laravel project and went straight to setting up GraphQL without bothering much with Laravel first.  so my bad I guess.

**Comment by mfn** [comment]
Thanks for your understanding 😄

**Comment by KhizerRehan** [comment]
@mfn i also following this issue the Query Work in other client like https://altair.sirmuel.design/

but when i tries to run the same query in postman with headers same as of given in Altair this results into following output any help would be appreciated. IDK why it is not working on POSTMAN but does in other client.


```json
{
  "errors": [
    {
      "message": "Cannot query field \"learner\" on type \"Query\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by mfn** [comment]
> i also following this issue the Query Work in other client like

Please open a discussion at https://github.com/rebing/graphql-laravel/discussions and provide as much details as possible (actual query, your query definition and types, etc.)

Thank you
