### ISSUE TITLE
Custom query is not called on interface's relation field

### ISSUE THREAD

**Issue by EdwinDayot** [rebing/graphql-laravel#421]
### Versions:
- graphql-laravel Version: 2.0.0-RC4
- Laravel Version: 5.8
- PHP Version: 7.2

### Description:

`src/Rebing/GraphQL/Support/SelectFields.php`
```php
// Line 160
if (isset($parentType->config['model'])) {
```

Because of this line, an `Interface` (and the `Type`s implementing it) cannot have a  field using a `customQuery`.

This is also true for a `Union`.

This `if` statement probably should have an `or` statement for `Interface`s and `Union`s

### Steps To Reproduce:

- Create an interface containing a field with a custom query

**Comment by EdwinDayot** [comment]
After a deeper investigation, adding a `or` statement wouldn't be enough since the `model` itself is required to get the `relation`. Still, our `Type`s implementing the `Interface` have access to the `model` property.

**Comment by mfn** [comment]
You mean there's a clash in case a field has the _literal_ name `customQuery`?

It would be great to get some tests showing this problem!

**Comment by EdwinDayot** [comment]
No, I mean something like this:

```php
class ObjectInterfaceType extends InterfaceType
{
    /**
     * @var array
     */
    protected $attributes = [
        'name' => 'ObjectInterfaceType',
        'description' => 'A type'
    ];

    /**
     * @return array
     */
    public function fields(): array
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::id()),
                'description' => 'The id of the object'
            ],
            'statistics' => [
                'type' => Type::listOf(GraphQL::type('statistic')),
                'args' => [
                    'group' => ['name' => 'group', 'type' => Type::string()]
                ],
                'query' => function (array $args, $query) {
                    // Never reached
                }
            ]
        ];
    }


    /**
     * @param $root
     * @return mixed
     */
    public function resolveType($root)
    {
        if ($root instanceof Entity) {
            return GraphQL::type('someType');
        }
    }
}
```

```php
class SomeType extends GraphQLType
{
    protected $attributes = [
        'name' => 'SomeType',
        'description' => 'A type',
        'model' => Entity::class,
    ];

    public function fields(): array
    {
        $interface = GraphQL::type('objectInterface');
        $result =
            [
                'statistics' => [
                    'type' => Type::listOf(GraphQL::type('someStatisticType')),
                    'query' => function (array $args, $query) {
                        // Never reached
                    }
                ]
            ] + $interface->getFields();;
        return $result;
    }

    public function interfaces(): array
    {
        return [
            GraphQL::type('objectInterface'),
        ];
    }
}
```

**Comment by EdwinDayot** [comment]
Here is an example: https://github.com/EdwinDayot/graphql-laravel-interface-custom-query

**Comment by mfn** [comment]
I know understand what you're describing. No idea of the solution yet, though.

However it would be great if you could add a PR with a test against `master` for this where it's shown that the supposedly effect the `query` should have cannot be observed.
