### ISSUE TITLE
Json type

### ISSUE THREAD

**Issue by websitevirtuoso** [rebing/graphql-laravel#435]
### Summary

We already have json type but don't have dynamic json type.

Some users can try to get json object with 10-20-50 keys. We don't know their names and values.
I found this example
https://github.com/webonyx/graphql-php/issues/129

But I don't know how to use it and implement it in rebing.

I tried to use string type but it cant display it.
```
"debugMessage": "Expected a value of type \"String\" but received: {\"id\":36303754,\"name\":\"homebuzz\",\"url\":\"http:\\/\\/txt.bz\\/V7rxtQj\"}",
      "message": "Expected a value of type \"String\" but received: {\"id\":36303754,\"name\":\"homebuzz\",\"url\":\"http:\\/\\/txt.bz\\/V7rxtQj\"}",
```

That't because in model I have 
```
protected $casts = [
        'fieldName' => 'json'
    ];
```

If I drop it then it show correctly but we lose feature laravel casting json. Mya be we can implement something?

**Comment by mfn** [comment]
It's unrelated to this library and there's no plan for additional support at the moment; I would cite the same reason as given in https://github.com/webonyx/graphql-php/issues/129#issuecomment-309366803

To give you some directions:
- if you declare the field that way in `$casts` it means your "string json representation will be decoded" which in turn means, that particular field will be returned as array
- and exactly this is the reason you get this error: you typed your field as `String` but you return the (decoded) JSON === array !== string
- the possibilities of a JSON type itself **cannot** be fully mapped in GraphQL becaue it misses some essential properties; the most obvious one: GraphQL does not understand the concept of "maps" with keys=>values
- so the only way to do this is to transfer it as string but this also means:
  - you have to decode it on the client
  - you loose (GraphQL) type safety
- if you want to to have it `$casts` that way _and_ return the value as JSON encoded string, you need add a resolver for this particular field which basically encodes it again for the GraphQL part (or you sidestep this and simply return the raw attribute value, whatever you prefer)

**Comment by mfn** [comment]
Per your suggestion in Slack, there's https://github.com/mll-lab/graphql-php-scalars which perfectly fills the void if needed!
