### ISSUE TITLE
Reducing amount sql queries

### ISSUE THREAD

**Issue by websitevirtuoso** [rebing/graphql-laravel#436]
![image](https://user-images.githubusercontent.com/5112918/62165415-3fd0c180-b2d3-11e9-87a8-3244c98c2dc6.png)

Found that each very simple query request Count(*) from ***

I would like to implement noslq because it much faster and can hep reduce amount request to DB. 

I want to make request onlye once each x second with ttl time. 
Could you guide me where I should implement it?

**Comment by mfn** [comment]
Using pagination essentially means returning a `LengthAwarePaginator` from the respective query resolver, see this example from the readme:
```php
    public function resolve($root, $args, $context, ResolveInfo $info, Closure $getSelectFields)
    {
        $fields = $getSelectFields();
        return Post
            ::with($fields->getRelations())
            ->select($fields->getSelect())
            ->paginate($args['limit'], ['*'], 'page', $args['page']);
    }
```
But this is just an example: you can do anything as long as you return a `LengthAwarePaginator` which means you can return your own one which uses a cache for the `total`.

Let me know if this helps you.

**Comment by websitevirtuoso** [comment]
I will try. and share with experience and code.
My current project grows very fast and I would like to implement NoSQL to reduce amount queries. 
Thank you very much.
