### ISSUE TITLE
Nested filter

### ISSUE THREAD

**Issue by websitevirtuoso** [rebing/graphql-laravel#440]
![image](https://user-images.githubusercontent.com/5112918/62742408-5376d900-b9f3-11e9-8b4e-ed4b398daafa.png)

Having type
https://github.com/websitevirtuoso/graphql_demo/blob/feature/add_property_to_grapqhl/app/GraphQL/Types/Properties.php

Line 93. When trying to use nested filter or sorting it show me
Graphql error
```
"message": "Undefined property: GraphQL\\Language\\AST\\ObjectValueNode::$value",
      "extensions": {
        "category": "internal"
      },
```

**Comment by mfn** [comment]
Which version did you try?

**Comment by mfn** [comment]
Please don't disregard the issue template, it's there for a reason; thank you

**Comment by websitevirtuoso** [comment]
Sorry.
### Versions:
- graphql-laravel Version: v2.0.0-RC5
- Laravel/Lumen Version: 5.8.30
- PHP Version:7.3.1

I also upload whole my project to github
https://github.com/websitevirtuoso/graphql_demo/blob/feature/add_property_to_grapqhl/app/GraphQL/Types/Properties.php
Branch - feature/add_property_to_grapqhl

In first version it worked

**Comment by crissi** [comment]
#419 Pretty sure this solves it

**Comment by mfn** [comment]
#419 was just merged, hope it fixes it for you 🤞

**Comment by mfn** [comment]
[2.0.1 containing the fix was just released](https://github.com/rebing/graphql-laravel/releases/tag/2.0.1)
