### ISSUE TITLE
Get Illuminate\Http\Request within a Mutation?

### ISSUE THREAD

**Issue by ajanini** [rebing/graphql-laravel#444]
### Versions:
- graphql-laravel Version: 1.23.0
- Laravel/Lumen Version: 5.7.28
- PHP Version: 7.2.1

### Question:

How do I get the original `\Illuminate\Http\Request` within a GraphQL *mutation*?

Thanks

**Comment by mfn** [comment]
Although the library receives the `Request` in `\Rebing\GraphQL\GraphQLController::query`, it does not pass it on.

What this means is: the global `request()` helper is your best option at the moment.

**Comment by mfn** [comment]
Although there's the workaround I mentioned (others might say it's not event a "workaround" but correct), it think it should be possible to carry it along with the resolvers 3rd argument, the `$context`.

However for this to work the following is necessary:
- a custom controller extending `\Rebing\GraphQL\GraphQLController`
- override `queryContext`
- from it return what you want (either the `Request` directly or, preferable, some wrapper object where you put the request into it)

I implemented this suggestion in https://github.com/rebing/graphql-laravel/pull/450 : it annoys me that it's a) a breaking change b) adds yet-another-parameter to `queryContext` but I don't see a better way right now. Please give it a try.

**Comment by ajanini** [comment]
Thank you so much, @mfn.

I went with your first suggestion, using the global `request()` and it worked quite nicely for my needs.

I really appreciate your help.
