### ISSUE TITLE
`$getSelectFields()->getSelect()` Will return flatten fields array

### ISSUE THREAD

**Issue by PayteR** [rebing/graphql-laravel#445]
### Versions:
- graphql-laravel Version: 2.0.0
- Laravel/Lumen Version: 5.8.31
- PHP Version: 7.1.14

### Question:

Hi, I'm trying to get selected fields by `$getSelectFields()->getSelect();` but result array is flattened. I don't use Eloquent modules as DB storage but trying to get data by custom ElasticSearch query.

this is main type
```
    public function fields() : array
    {
        return [
            'ID' => [
                'type' => Type::nonNull(Type::int()),
                'description' => '',
            ],
            'post_type' => [
                'type' => Type::nonNull(Type::string()),
                'description' => '',
            ],
            'post_title' => [
                'type' => Type::nonNull(Type::string()),
                'description' => '',
            ],
            'post_name' => [
                'type' => Type::nonNull(Type::string()),
                'description' => '',
            ],
            'post_date' => [
                'type' => Type::nonNull(Type::string()),
                'description' => '',
            ],
            'post_author' => [
                'type'          => GraphQL::type('post_author_elastic_type'),
                'description'   => '',
                'resolve'       => function ($data) {
                    return $data;
                },
            ],
        ];
    }
```

this is `GraphQL::type('post_author_elastic_type'),` used in first type
```
    // define field of type
    public function fields() : array
    {
        return [
            'raw' => [
                'type' => Type::string(),
                'description' => '',
            ],
            'login' => [
                'type' => Type::string(),
                'description' => '',
            ],
            'display_name' => [
                'type' => Type::string(),
                'description' => '',
            ],
            'id' => [
                'type' => Type::int(),
                'description' => '',
            ],
        ];
    }
```
An when i try to get select field, it looks like this 
![image](https://user-images.githubusercontent.com/1248565/62987293-57658980-be3f-11e9-9e91-cc6fa97b3899.png)

which is wrong, the correct result should be there with hierarchy for post_author fields like `post_author.raw`, `post_author.login` etc... How to achieve this? thx

**Comment by mfn** [comment]
To me knowledge this is not supported.

How would the package know that I've to access `post_author.raw` instead of just `raw` in your example?

Would you have to signal that your model is meant for ElaticSearch and all and that sub-field resolving should happen with fully qualified names?

What about a 3rd level, like (just made it up) `post_author.display_name.language_en`?

**Comment by PayteR** [comment]
ElasticSearch data are hierarchical in the sense that one document (it's something like a row in relational DB) could handle hierarchical objects

![image](https://user-images.githubusercontent.com/1248565/63007878-d380c100-be81-11e9-8876-0c1940f44fad.png)

But every document is a large set of data and i want to retrieve just data that i want. There is a possibility to "select" just this data, and i just need an array with this fields. When i query this:

![image](https://user-images.githubusercontent.com/1248565/63009097-2196c400-be84-11e9-9383-bdb3a4777d04.png)

I want to get an array like 
```
$select['ID'] 
$select['post_title'] 
$select['post_author']['display_name'] 
$select['post_author']['id'] 
```


For your questions
1. no, i need that hierarchy
2. i want to retrieve just selected data from document
3. in my case there are max of 4 levels in document

**Comment by PayteR** [comment]
I figured easy solution for me 
```
$sourceFields = \Arr::dot($info->getFieldSelection($depth = 4));
```
https://laravel.com/docs/5.8/helpers#collection-method

![image](https://user-images.githubusercontent.com/1248565/63010211-40965580-be86-11e9-9056-184d35cdaf2c.png)

It's exactly what i needed, but i still think, that this should be the default behaviour, what do you think?

**Comment by mfn** [comment]
> that this should be the default behaviour

That would mean to always use Fully Qualified names for the database ... should work, I guess?

> in my case there are max of 4 levels in document

But that won't work for databases, right? So it would work for your case and break in others.

Hence my comment:
> Would you have to signal that your model is meant for ElaticSearch

Basically SelectFields is tailored for SQL and we want to behave it differently if non-relational DBs are used which changes how it works in a non-compatible way.

At least that's my assessment so far.

a) I'm not sure if it's smart to expand `SelectFields` in that way; it could become really messy
b) this definitely requires contribution form someone working that way; I'm using ElasticSearch but not mapped to Eloequent models that way

**Comment by PayteR** [comment]
Ok, i thought that this package will always return select fields hierarchically, even when an eloquent model is not mapped. Anyway, i found the solution that works for me, there is no need to rewrite package for this use-case, thank you for the support!
