### ISSUE TITLE
 MethodNotAllowedHttpException after Folkloreatelier branch

### ISSUE THREAD

**Issue by Sndan** [rebing/graphql-laravel#45]
I was using Folkloreatelier relay branch ...but I saw rebing and I wanted to use it 
after I remove Folkloreatelier  and it is confing file and installed rebing it did not work !

it gives me error after accessing graphql url -> MethodNotAllowedHttpException ...

> 

(1/1)                                         MethodNotAllowedHttpException
--
in RouteCollection.php (line 251)
at RouteCollection->methodNotAllowed(array('POST'))in RouteCollection.php (line 238)
at RouteCollection->getRouteForMethods(object(Request), array('POST'))in RouteCollection.php (line 176)
at RouteCollection->match(object(Request))in Router.php (line 546)
at Router->findRoute(object(Request))in Router.php (line 525)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HandleCors.php (line 34)
at HandleCors->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Request.php (line 111)
at Request->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

**Comment by rebing** [comment]
Can you show me the config file?

**Comment by Sndan** [comment]
For which graph ?
Already deleted previous config

**Comment by rebing** [comment]
Your current config

**Comment by Sndan** [comment]
`<?php
use example\Mutation\ExampleMutation;
use example\Query\ExampleQuery;
use example\Type\ExampleRelationType;
use example\Type\ExampleType;
return [

    // The prefix for routes
    'prefix' => 'graphql',

    // The routes to make GraphQL request. Either a string that will apply
    // to both query and mutation or an array containing the key 'query' and/or
    // 'mutation' with the according Route
    //
    // Example:
    //
    // Same route for both query and mutation
    //
    // 'routes' => 'path/to/query/{graphql_schema?}',
    //
    // or define each route
    //
    // 'routes' => [
    //     'query' => 'query/{graphql_schema?}',
    //     'mutation' => 'mutation/{graphql_schema?}',
    // ]
    //
    'routes' => '{graphql_schema?}',

    // The controller to use in GraphQL request. Either a string that will apply
    // to both query and mutation or an array containing the key 'query' and/or
    // 'mutation' with the according Controller and method
    //
    // Example:
    //
    // 'controllers' => [
    //     'query' => '\Rebing\GraphQL\GraphQLController@query',
    //     'mutation' => '\Rebing\GraphQL\GraphQLController@mutation'
    // ]
    //
    'controllers' => \Rebing\GraphQL\GraphQLController::class . '@query',

    // Any middleware for the graphql route group
    'middleware' => [],

    // The name of the default schema used when no argument is provided
    // to GraphQL::schema() or when the route is used without the graphql_schema
    // parameter.
    'default_schema' => 'default',

    // The schemas for query and/or mutation. It expects an array of schemas to provide
    // both the 'query' fields and the 'mutation' fields.
    //
    // You can also provide a middleware that will only apply to the given schema
    //
    // Example:
    //
    //  'schema' => 'default',
    //
    //  'schemas' => [
    //      'default' => [
    //          'query' => [
    //              'users' => 'App\GraphQL\Query\UsersQuery'
    //          ],
    //          'mutation' => [
    //
    //          ]
    //      ],
    //      'user' => [
    //          'query' => [
    //              'profile' => 'App\GraphQL\Query\ProfileQuery'
    //          ],
    //          'mutation' => [
    //
    //          ],
    //          'middleware' => ['auth'],
    //      ]
    //  ]
    //
    'schemas' => [
        'default' => [
            'query' => [
                'user' => \App\GraphQL\Query\UserQuery::class,

            ],
            'mutation' => [
' => App\GraphQL\Mutation\DischargeMutation::class,
            ],
            'middleware' => []
        ],
    ],
    
    // The types available in the application. You can then access it from the
    // facade like this: GraphQL::type('user')
    //
    // Example:
    //
    // 'types' => [
    //     'user' => 'App\GraphQL\Type\UserType'
    // ]
    //
    'types' => [
        'User' => 'App\GraphQL\Type\UserType',

        'Attachment' => 'App\GraphQL\Type\AttachmentType',

    ],
    
    // This callable will be passed the Error object for each errors GraphQL catch.
    // The method should return an array representing the error.
    // Typically:
    // [
    //     'message' => '',
    //     'locations' => []
    // ]
    'error_formatter' => ['\Rebing\GraphQL\GraphQL', 'formatError'],

    // You can set the key, which will be used to retrieve the dynamic variables
    'params_key'    => 'params',
    
];`

**Comment by Sndan** [comment]
this is ...the app file 

`'GraphQL' => Rebing\GraphQL\Support\Facades\GraphQL::class,`

` Rebing\GraphQL\GraphQLServiceProvider::class,`

**Comment by Sndan** [comment]
config paste 
https://pastebin.com/5bxwZrU3

**Comment by rebing** [comment]
Config looks okay. Which version of Laravel are you using? I think there's an issue with your `routes` file or `RouteServiceProvider`

**Comment by Sndan** [comment]
laravel 5.4
this is RouteServiceProvider
https://pastebin.com/r43Vz99k

i reinstalled Folkloreatelier/laravel-graphql

it worked with no issue

**Comment by rebing** [comment]
If you run `php artisan route:list`, do you see `graphql` in there?

**Comment by jasonhebert** [comment]
I have this same issue and from what I can tell it looks like only the POST routes for Query and Mutation are setup in the libraries routes.php. The exception thrown is because there is no GET method defined for this route. GraphiQL is also unusable for the same reason.

**Comment by rebing** [comment]
Added GET routes #49
