### ISSUE TITLE
Mutation class cannot access session using authorize method

### ISSUE THREAD

**Issue by kamdude** [rebing/graphql-laravel#462]
### Versions:
- graphql-laravel Version: 2.0.0
- Laravel/Lumen Version: 5.8.30
- PHP Version: 7.2.20

### Description:

Mutation class cannot access session using authorize method

### Steps To Reproduce:

* Create class FooMutation
```php
class FooMutation extends Mutation
{
    public function authorize(array $args): bool
    {
        return !Auth::guest();
    }
    // ... 
}
```
* Login as a valid user
* Post query and receives an Unauthorized exception
```
mutation updateFoo($bar: String) {
    foo (bar: $bar) {
        bar
    }
}
```
* Hard code authorize method to return value true and everything works.

**Comment by mfn** [comment]
I can't see a bug in the library here.

The `authorize` method is called like any other resolvers after all the middlewares have been processed; and they are responsible for setting up your session/auth user/etc.

I suspect your middleware configuration for the GraphQL part isn't correct, check `'middleware`' in your `config/graphql.php`.

**Comment by kamdude** [comment]
Well, I didn't put the 'auth' middleware in the `config/graphql.php` file, so I just tried to add it under default schema and outside schema key or both, 
it's still Unauthorized exception but this time, the request has been redirected to login makes graphql receive nothing. 
I've been frustrated to debug that in hours, all I found is that Authenticate middleware receives an empty guards array so it throws out the Unauthorized exception.
config/graphql.php
```
  'middleware' => [],
    'schemas' => [
        'default' => [
            'query' => [
                'foo' => \App\GraphQL\Queries\FooQuery::class,
            ],
            'middleware' => ['auth'],
            'method'     => ['get', 'post'],
        ],
    ],
```

do I miss something?

**Comment by mfn** [comment]
>  it's still Unauthorized exception but this time, the request has been redirected to login makes graphql receive nothing.

It seems you're using the web auth driver instead of api? Are you guards properly set up?

All the troubles you experience would the same if you would make a regular API endpoint and using the wrong middleware, so I'm not sure where it really goes off the rails for you here.

I suggest to read up on https://laravel.com/docs/5.8/api-authentication 🤷‍♀️
