### ISSUE TITLE
Expose field resolver depth parameter

### ISSUE THREAD

**Issue by shengslogar** [rebing/graphql-laravel#469]
### Summary
v2.0.1

Resolving query fields is hard-coded to a depth of 5. When exceeding this limit, non-intuitive SQL errors are thrown.

https://github.com/rebing/graphql-laravel/blob/edb88d6c5f46a1333dd02e287831d29703af00c3/src/Support/SelectFields.php#L44

### Use Case
I ran into this issue when creating a deep nested query and using eager loading on the `resolve` method [per documentation](https://github.com/rebing/graphql-laravel/blob/master/Readme.md#eager-loading-relationships).

### Possible Solutions
- Expose via instance variables in both `Field` and `SelectFields` classes to be overridden
- Expose via instance variable in `Field` class and optional parameter with `$getSelectFields` closure ([here](https://github.com/rebing/graphql-laravel/blob/master/src/Support/Field.php#L197-L199))
- Improve documentation to explain the limit and how to override it (there is a hint at it under the "eager loading relationships" section, but it wasn't clear to me)

Happy to look into making this work if pointed in a suggested direction.

**Comment by mfn** [comment]
I prefer to keep things _away_ from `Field`. If possible, only `SelectField` should be adapted.

How about adding a field to `SelectFields` and bump the default, e.g. `public static $depth = 9;` on `SelectFields`.

That way it can be adapted (read: bumped up even more) if necessary.

I imagine this would be done _once_ per boot of the ServiceProvider (and not dynamic depending on the query).

What do you think?

**Comment by mfn** [comment]
Please see https://github.com/rebing/graphql-laravel/pull/472 and let me know if it fixes your use case.

**Comment by mfn** [comment]
[The fix is part of 2.1.0 release](https://github.com/rebing/graphql-laravel/releases/tag/2.1.0)
