### ISSUE TITLE
"always" not working in a relation

### ISSUE THREAD

**Issue by patchbank** [rebing/graphql-laravel#473]
### Versions:
- graphql-laravel Version: 2.1.0
- Laravel Version: 5.8.34
- PHP Version: 7.2.21

### Description:
Imagine two models with the following fields:
```
User
- id
- username

Post
- id
- user_id
- title
```

With the following types:
```php
# UserType.php
[
    'id' => [
        'type'        => Type::nonNull(Type::int()),
        'description' => '...',
    ],
    'username'  => [
        'type'        => Type::nonNull(Type::string()),
        'description' => '...',
    ],

    # Relationships
    'posts'  => [
        'type'        => Type::listOf(GraphQL::type('Post')),
        'description' => '...',
    ]
]

# PostType.php
[
    'id' => [
        'type'        => Type::nonNull(Type::int()),
        'description' => '...',
    ],
    'title'  => [
        'type'        => Type::nonNull(Type::string()),
        'description' => '...',
    ],

    # Relationships
    'user'  => [
        'type'        => GraphQL::type('User'),
        'description' => '...',
    ]
]
```

And also the following query for users:
```php
class UsersQuery extends Query
{
    protected $attributes = [
        'name'        => 'users',
        'description' => 'Returns all users.',
    ];

    public function type(): Type
    {
        return Type::listOf(GraphQL::type('User'));
    }

    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        /** @var SelectFields $fields */
        $fields = $getSelectFields();
        $select = $fields->getSelect();
        $with = $fields->getRelations();

        $users = User::select($fields)->with($with);
        return $users->get();
    }
}
```

Now when querying the users-query with the `id` and `posts` fields, everything works fine. But when I'm removing the `id` field from the query, it will continue to include the `posts` field in the response, but it is just an empty array.

After further reading your README file, I noticed the `always` option I can add to my `posts`-field in the `UserType.php`. Unfortunately the result isn't changing. The response contains simply an empty array in the `posts`-field:
```php
'posts'  => [
    'type'        => Type::listOf(GraphQL::type('Post')),
    'description' => '...',
    'always'      => ['id']
]
```

When I move the `always` option to another field of my user, for example the `username`, and then include that field in my query, the `always`-option seems to work and also my `posts` field isn't empty anymore.

### Steps To Reproduce:

- Create a new Laravel 5.8.34 project on PHP 7.2.21.
- Install this library with `composer require rebing/graphql-laravel`.
- Create two models, types and also the one Query as described above, without the `always`-option.
- Query the `users` query with the `posts` field but without including the users-ID-field => The `posts` field is empty.
- Add the `id` field to your query => The `posts` field will contain all the posts.
- Add the `always` option to the `posts`-field in the `UserType.php` and remove the `id` field from the request => The response will contain an empty `posts`-field.
- Move the `always` to another field, such as the `username`-field, and include that in the query (without the `id`-field) => The `posts` will be returned again.

**Comment by patchbank** [comment]
I'm sorry, but I've just realized that this might be related to #369 (https://github.com/rebing/graphql-laravel/issues/369#issuecomment-508346229).

**Comment by mfn** [comment]
Are you using a "morph" type relation here?

**Comment by patchbank** [comment]
No, I'm using a simple hasMany / belongsTo relation.

**Comment by mfn** [comment]
Have you defined the `'model'` on your types?

Either way: I believe the test case `\Rebing\GraphQL\Tests\Database\SelectFields\NestedRelationLoadingTests\NestedRelationLoadingTest::testQuerySelectAndWith` exactly represents your scenario.

- query: `\Rebing\GraphQL\Tests\Database\SelectFields\NestedRelationLoadingTests\UsersQuery`
- user type: `\Rebing\GraphQL\Tests\Database\SelectFields\NestedRelationLoadingTests\UserType`
- post type: `\Rebing\GraphQL\Tests\Database\SelectFields\NestedRelationLoadingTests\PostType`

Please check the test for differences to your case; when I remove the `id` field there and re-run, ignoring the changed SQL, it still give me back the correct results (sans the removed field).

**Comment by patchbank** [comment]
> Have you defined the `'model'` on your types?

Oh no, I totally forgot that :(
Adding it did the trick. Now it works as expected.

**Comment by mfn** [comment]
Glad it worked!

People seem to miss it, but it's in the docs. Not sure what exactly do to improve this 🤷‍♀️
