### ISSUE TITLE
Middleware for classes

### ISSUE THREAD

**Issue by snurges** [rebing/graphql-laravel#474]
### Summary

Currently it seems that middleware is only possible on schema-level, like this:

```
    'schemas' => [
        'default' => [
            'query' => [
                'users' => 'App\GraphQL\Query\UsersQuery',
            ],
            'mutation' => [

            ],
        ],
        'user' => [
            'query' => [
                'profile' => 'App\GraphQL\Query\ProfileQuery',
            ],
            'mutation' => [

            ],
            'middleware' => ['auth'],
        ],
    ];
```

What I would like is to have middleware for classes as well, so it would look something like this
```
    'schemas' => [
        'default' => [
            'query' => [
                'some_query' => [
                    'class'      => SomeQuery::class,
                    'middleware' => ['some_middleware'],
                ],
            ],
        ],
    ];
```

**Comment by mfn** [comment]
> Currently it seems that middleware is only possible on schema-level

TBH I've never used this, does it really work? See below why. There are certainly no tests for it… 

> What I would like is to have middleware for classes as well, so it would look something like this

When we're talking about Laravel middleware, this is executed _before_ it hits the GraphQL controller.

From that point on, based on the "schema", it resolves the user provided query. Which means during GraphQL execution we know we're going to use `some_query` at which point we're long past Laravels middleware.

Not sure how this could work for Laravel middleware, but open for ideas.

**Comment by snurges** [comment]
> TBH I've never used this, does it really work? See below why. There are certainly no tests for it…
Yes, the schema-level middleware definitely works, I'm using it myself. But yeah it seems it is currently not possible to have middleware for specific classes.

**Comment by snurges** [comment]
> TBH I've never used this, does it really work? See below why. There are certainly no tests for it… <
Yes, the schema-level middleware definitely works, I'm using it myself. But yeah it seems it is currently not possible to have middleware for specific classes.

**Comment by mfn** [comment]
> > TBH I've never used this, does it really work? See below why. There are certainly no tests for it…
> 
> Yes, the schema-level middleware definitely works, I'm using it myself.

🤦‍♂️

Of course it works, I just realized why: the schema name is part of the route and the routing code takes that into account when building the routes and their middleware.

According to the docs it's possible within a controllers constructor to add middleware, wonder if that can be used: https://laravel.com/docs/5.8/controllers#controller-middleware

**Comment by snurges** [comment]
Hmm OK, thanks for the help :)

**Comment by mfn** [comment]
If you find a solution, please us know.

Because what I referred to is meant for controllers, but we don't have them. And I'm not familiar with how the controller pipes additional middlewares into the system.
