### ISSUE TITLE
Return Data type array 

### ISSUE THREAD

**Issue by Hieesu** [rebing/graphql-laravel#475]
How can i return data with type is array without use Type::listOf(...)

**Comment by mfn** [comment]
AFAIK it can also represent a "shape" of an object.

Example: if you want to return a `Comment` type, _usually_ you have an underlying Eloquent model to use.

But you don't, instead you can pass back an array with the appropriate data for it. The graphql-php (the underlying library) has a "default resolver" which takes care of this.

Does this answer your question?

If not, please be more specific!

**Comment by Hieesu** [comment]
Sorry if i dont understand your reply 

``'value' => [
                'type' => Type::string(),
                'description' => 'Data need resolve',
            ],

i have json data stored in my database and decode it with function resolveValueField()
key 'type' is required  so what type i must use to return my data

**Comment by mfn** [comment]
> i have json data stored in my database and decode it with function resolveValueField()

If you want to return your JSON _encoded_, just return the _raw_ data (i.e. string, as in your example):
```php
`resolve` => function ($model) {
  return json_encode($model->value);
}
```

If you want to return the _content_ of the JSON data, you need to adjust your `type` and return the decode version.

In which case you need what resolver depends also whether you've set up the fields in `$casts`.

There's also a package for such scalar types if needed: https://github.com/mll-lab/graphql-php-scalars
