### ISSUE TITLE
optional array of strings parameter is not recognized as optional

### ISSUE THREAD

**Issue by kfirufk** [rebing/graphql-laravel#478]
### Versions:
- graphql-laravel Version: ^3.0
- Laravel Version: 5.8.34
- PHP Version: 7.3.0

### Description:

I created a function that one of it's parameters requires an optional array of strings, which means it can be null too.

so in the function definition added a question mark before it, and in the PHPDoc I defined it as `@param string[]|null`. when I'm running my application and trying to execute a graphql command I get the following error:

`VM459:37 ERROR Error: GraphQL error: Variable "$destinations" of type "[String]" used in position expecting type "[String!]".`

in My angular-apollo application i'm defining the variable as `[String]` which represents an optional array of strings.

in any other variable that I made optional which is not array I didn't encounter any problem.

**Comment by mfn** [comment]
> graphql-laravel Version: ^3.0

🤔 This package latest version is 2.1.0 ... just mentioning it. Are you sure you are using this package? 😄 


> I created a function

Please paste all relevant code examples, thanks

**Comment by mfn** [comment]
Closing due to missing feedback; I'm happy to reopen if more information is provided in the future.
