### ISSUE TITLE
why and how is this different from https://github.com/nuwave/lighthouse

### ISSUE THREAD

**Issue by kunaldodiya** [rebing/graphql-laravel#480]
### Summary
Is there any plan to merge rebing/graphql-laravel with nuwave/lighthouse, the idea behind is to why to focus two different methods when the output is the same, and if it is merged, more and combined contributers will be there, more features will be there

**Comment by mfn** [comment]
Good questions :-)

I'm personally aware of lighthouse, they're doing a fabulous job.

Before coming to rebing I've been using https://github.com/folkloreinc/laravel-graphql which was abandon some time ago.

When I had to make a move on a project where I used folklore and I evaluated the libraries, the approach and philosophy used by lighthouse simply didn't find what the project needed. Also the cost of change was quite high, as there was already a schema in place having a count of > 100 which is non-trivial to port and verify.

Rebing is (more or less) compatible in many ways with the approach used by folkore ([we've an upgrade guide for those wanting to switch](https://github.com/rebing/graphql-laravel#migrating-from-folklore)) so there's that.

DSL first and the approach used with directives may be perfect fit for some but not for other projects. I guess this is the best description I can give 😄 

I certainly would have switched to lighthouse if at that time would I've been able to use the same techniques.

I feel that lighthouse has a much better / tighter integration with Laravel and also some more advanced features possibly (I'm not _that_ acquainted with all their feature set).

In contrast, Folklore/Rebing are a rather thin layer between the underlying webonxy graphql-php library, leaking through in some places; feels like more to the metal to me.

The tightest integration for Laravel which rebing features it the `SelectFields` helper class for optimized Eloquent queries. I don't think it's the best approach but works for many use cases. Sadly the "dataloader" approach more prominently used in the NodeJS graphql world is quite neglected but IMHO more preferred.

I guess it does answer some parts of your question but not all. Feel free to ask more.

As for the future of rebing: from my POV there are no specific visions currently, except fixing bugs and improving performance.

**Comment by kunaldodiya** [comment]
Great, thanks for answering, will look forward but I used lighthouse earlier and found it easy to pick up, but your library has also good features, so initially I was confused to try new one but let me go with lighthouse for time being, thanks again
