### ISSUE TITLE
i'm confused i dont' think is that Issue or a Feature . {graphql_schema?}

### ISSUE THREAD

**Issue by El-Mehdi-Abdi** [rebing/graphql-laravel#490]
hi, 
in my laravel application i use modules system for example i have seller module and buyer model 

i create in seller module config/schema.php and i merge the schema in the config/graphql.php

![Screen Shot 2019-10-13 at 12 39 12 PM](https://user-images.githubusercontent.com/55539600/66715040-87d19180-edb6-11e9-831b-f1714a6bd6e7.png)
 so the result is : seller injected to config/graphql.php at run-time

![Screen Shot 2019-10-13 at 12 41 06 PM](https://user-images.githubusercontent.com/55539600/66715101-16dea980-edb7-11e9-933c-469d7743b7b3.png)

and i update my config/graphql.php:

`'routes' => '{graphql_schema?}}',  to 'routes' => '{graphql_schema?}/{schema?}',`

the result of that small modification is  i can access to different modules.

if i want to query, mutation at seller model 
http://localhost.test/graphql/seller

if i want to query, mutation at default model 
http://localhost.test/graphql/default

if i want to query, mutation at buyer model 
http://localhost.test/graphql/buyer
....

issue :
Graphiql works only at : http://localhost.test/graphiql/default
at : http://localhost.test/graphiql/seller return 404 laravel not found.

**Comment by onurkose** [comment]
It's an old topic but I suggest you to try **php artisan route:list** command.

I am using the same approach and my graphiql locations works just fine.

![Ekran Resmi 2020-02-08 19 51 12](https://user-images.githubusercontent.com/139073/74088899-4fb03600-4aac-11ea-9f7b-4d9fee8a0f86.png)

If you can't see any of the graphiql routes there might be a problem of your setup.

**Comment by websitevirtuoso** [comment]
I have 2 schemas like with name api & api/public without any modifications. So I think we may close this question.

**Comment by mfn** [comment]
> I have 2 schemas like with name api & api/public without any modifications. So I think we may close this question.

Thanks, and I agree actually.

I'm (in the meantime) also using multiple schemas and they work as expected.

The config defaults are:
```php
    // The prefix for routes
    'prefix' => 'graphql',
…
    'routes' => '{graphql_schema?}',
```
This means:
- `/graphql` accesses the `'default'` configured schema
- `/graphql/nameOfSchema` accesses the schema named `'nameOfSchema'` etc.
