### ISSUE TITLE
A field implemented through Interface does not use the proper alias

### ISSUE THREAD

**Issue by EdwinDayot** [rebing/graphql-laravel#491]
### Versions:
- graphql-laravel Version: 2.1.1

### Description:

If a `Type` is implementing an `Interface` defining a field with an alias, and we try to overwrite it in the `Type`, the alias of the `Interface` will always be used.

### Steps To Reproduce:

```php
class InterfaceExample {
  public function fields() {
    return [
      'a_field' => [
        'alias' => 'an_alias' // This will be used
      ]
    ];
  }
}

class TypeExample {
  public function fields() {
    $fields = GraphQL::type('InterfaceExample');
    return $fields->getFields() + [
      'a_field' => [
        'alias' => 'another_alias' // Instead of this
      ]
    ];
  }
}
```

**Comment by EdwinDayot** [comment]
Interfaces are quite complex to handle, I think we should move everything handling Interfaces into Closures executed as needed so we have access to the _real_ type.

**Comment by mfn** [comment]
Would be great if you could add a test for the existing behaviour to master

**Comment by EdwinDayot** [comment]
Sure, I will

**Comment by EdwinDayot** [comment]
This bug has been reintroduced with version 5.0.0

**Comment by mfn** [comment]
💥 

How? Not pretending to understand where exactly :) thought things were covered in tests.

Can you check this and make a fix?

**Comment by illambo** [comment]
Strange, i remember the test [_testGeneratedInterfaceFieldInlineFragmentsAndAlias_ ](https://github.com/rebing/graphql-laravel/pull/607/commits/c0d12f709e211ef0238e5d9a688bac096295a653) covered the alias case.
Maybe I did something wrong ?

**Comment by illambo** [comment]
Mmm, yes cover the alias case but not exactly the current case.
I try to verify better with a specific unit test, sorry for that.

**Comment by illambo** [comment]
Ok, I try in local with specific test and seems works properly, I think the problem is in the use of "+" for array merge (better user array_merge), pls try with this: 

```php
class TypeExample {
  public function fields() {
    $interface = GraphQL::type('InterfaceExample');
    return array_merge($interface->getFields(), [
      'a_field' => [
        'alias' => 'another_alias' // Instead of this
      ]
    ]);
  }
}
```

**Comment by EdwinDayot** [comment]
I'll try this ! Thanks !
