### ISSUE TITLE
How to call TypeResolver from MutationResolver

### ISSUE THREAD

**Issue by jaimealv994** [rebing/graphql-laravel#495]
### Versions:
- graphql-laravel Version: ^2.1
- Laravel Version: 5.8.*
- PHP Version: 7.3.10

### Question:

I have a mutation CreateIngressedAccountsMutation, and I would like to pass the result through a type resolver

```
class CreateIngressedAccountsMutation extends Mutation
{
    protected $attributes = [
        'name' => 'createIngressedAccounts'
    ];

    public function type(): Type
    {
        return Type::nonNull(Type::listOf(GraphQL::type('IngressedAccount')));
    }

    public function args(): array
    {
        return [
            'accounts' => ['type' => Type::nonNull(Type::listOf(GraphQL::type('CreateIngressedAccountInput')))]
        ];
    }


    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {

        $result = collect($args['accounts'])->map(function ($accountInput) {
            $account = (new IngressedAccount())->fill($this->snakeObj($accountInput));
            $account->saveOrFail();
            return $account;
        });

        // pass result to a type resolver

        return $result;
    }
}
```

**Comment by mfn** [comment]
> pass the result through a type resolver

Can you be more specific what you mean with that or, what you goal is?

Is it about "code reuse", that you have some code in the types resolver you want to re-use here/

**Comment by jaimealv994** [comment]
That mutation has the following return type `Type::nonNull(Type::listOf(GraphQL::type('IngressedAccount')));`


And the IngressedAccountType is like this:
```
class IngressedAccountType extends GraphQLType
{
    protected $attributes = ['name' => 'IngressedAccount',];

    public function fields(): array
    {
        return [
            'id' => ['type' => Type::nonNull(Type::id())],
            'visitId' => ['type' => Type::nonNull(Type::id()), 'alias' => 'visit_id'],
            'createdBy' => ['type' => Type::nonNull(Type::id())],
            'name' => ['type' => Type::nonNull(Type::string())],
            'type' => ['type' => Type::nonNull(Type::string())],
            'geolocation' => ['type' => Type::nonNull(Type::string())],
            'createdAt' => ['type' => Type::nonNull(Type::string()), 'alias' => 'created_at'],
            'updatedAt' => ['type' => Type::string(), 'alias' => 'updated_at'],

            'visit' => ['type' => Type::nonNull(GraphQL::type('User'))],
            'comments' => ['type' => Type::nonNull(Type::listOf(Type::nonNull(GraphQL::type('Comment'))))]
        ];
    }

    protected function resolveCommentsField($root, $args)
    {
        return Comment::query()->where('entity_id', $root->id)->where('entity_name', 'ingressed_account')->get();
    }
}
```

And I would like to invoke those field resolvers, it would save me a lot of time because I'm facing the same problem in other mutations.

**Comment by mfn** [comment]
> `Type::nonNull(Type::listOf(GraphQL::type('IngressedAccount')));`

Unrelated to your question, but I noticed you're not having `Type::nonNull()` over the `GraphQL::type()`. This allows to have GraphQL accept `null` values with the list, which in most cases is not the developers intention.

To your question:
If I understand it correctly, your mutation returns a collection of `IngressedAccount`. And the mutations return type matches it.

This means in a mutation like this:
```graphql
mutation {
  createIngressedAccounts(...) {
    id
    comments {
      id
    }
  }
}
```
The method ` I would like to pass the result through a type resolver::resolveCommentsField()` will be called for each created IngressedAccount.

So I'm not sure what your exact problem is here. You say:
>  I would like to pass the result through a type resolver

but this is supposed to happen here. GraphQL sees that the return type is of IngressedAccountType  and the collection model you return is of type IngressedAccount, the `resolveCommentsField` will be called if you access each IngressedAccount comments that way.

Maybe I'm missing something, then I would more details (all types, actual mutations, clearer description of problem and expectations).

**Comment by jaimealv994** [comment]
yeah, you're right, I checked my code again and found a wrong alias name. This problem made me think that my "**resolve field**" functions were not being called.

Thanks for your help. I will close the issue.
