### ISSUE TITLE
Type relationship query never called

### ISSUE THREAD

**Issue by thomas4Bitcraft** [rebing/graphql-laravel#504]
### Versions:
- graphql-laravel Version: 2.1
- Laravel Version: 5.5
- PHP Version: 7.2

### Description:
Hello!
At first: Thank you for this amazing library!

I have a problem with the query on a relationship. Here the code:
```
public function fields(): array
    {
        return [
....
            'projects' => [
                'type' => Type::listOf(GraphQL::type('project')),
                'description' => 'Projects for service',
                'args'          => [
                    'limit' => [
                        'type' => Type::int(),
                    ],
                ],
                'query' => function ($args, $query) {
                    return $query->limit($args['limit']);
                }
            ],
        ];
    }
```
The problem is, that the query itself gets never called. I already tried do add `dd($args);` inside the query but nothing happens.  What am I doing wrong here?

Here the Request: 

```
FetchService{
  service(id:1){
    id,
    projects(limit:2){
      id
    }
  }
}
```

And the result:

`{"data":{"service":{"id":1,"projects":[{"id":1},{"id":2},{"id":3}]}}}`

**Comment by mfn** [comment]
How does the resolver of `FetchService` look like? Please paste the code

**Comment by thomas4Bitcraft** [comment]
Here the resolver:

```
public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        if (isset($args['id'])) {
            $service = Service::find($args['id']);
        }

        if (isset($args['slug'])) {
            $service = Service::where('slug', $args['slug'])->first();
        }

        return $service;
    }
```

**Comment by mfn** [comment]
I think what's missing is that you need to make use `$getSelectFields`; otherwise you just manually resolved a single service.

Have a look at https://github.com/rebing/graphql-laravel#eager-loading-relationships

Only if you use the `SelectFields` infrastructure will the custom `'query'`, etc. be used.

Also make sure you defined the Eloquent `'model'` on the respective GraphQL type

**Comment by mfn** [comment]
Closing due to lack of feedback
