### ISSUE TITLE
Extend validation functionality by adding withValidator function

### ISSUE THREAD

**Issue by tpetry** [rebing/graphql-laravel#506]
For HTTP requests with validation, the validation using rules can be extended by adding a withValidator function. This is especially useful for executing certain validations that are dependent on the input or because a custom rule should not be written for every small check.

It would be nice if an optional function `withValidator` on a Graphql mutation would be called, as is the case for validations on http requests.

**Comment by mfn** [comment]
I like the idea.

I think `\Illuminate\Foundation\Http\FormRequest::getValidatorInstance` would be a good start to think how to integrate it into `\Rebing\GraphQL\Support\Field::getResolver` so we would also get the flexibility of having the factory involved; basically refactoring the existing code for this.

**Comment by tpetry** [comment]
Yeah i like the idea, this would also enable anyone to solve #505. So basically all issues created by me could be solved with a custom validator instance method.
