### ISSUE TITLE
Add custom field names support to mutation validations 

### ISSUE THREAD

**Issue by tpetry** [rebing/graphql-laravel#507]
For Laravel form requests, a function `attributes()` can be specified to give new names to the fields used in all validation messages of a field (4th argument to `Validator::make`).

Currently, for graphql validations a new value has to be provided for each field and every validation to have custom field names in the error message. It would be nice to simplify this by simply adding an optional `validationErrorAttributes` function like the `attributes` function for form requests.

**Comment by mfn** [comment]
Incidentally, when I give my feedback at https://github.com/rebing/graphql-laravel/issues/506#issuecomment-546486817 I was thinking that this should be included; basically refactoring this part of the validation layer.
