### ISSUE TITLE
I'm not able to query from different schema

### ISSUE THREAD

**Issue by Artem-Schander** [rebing/graphql-laravel#509]
### Versions:
- graphql-laravel Version: ^3.1
- Lumen Version: 5.5
- PHP Version: 7.2

### Question:

Lake I already told in a comment of the pr #508
I'm migrating a project from folklore and almost everything works fine except for one thing.

I have two different schemas `default` and `secret`. Previously I was able to interact with the secret schema by using the corresponding route. I.e. `/graphql/secret?query=query+FetchSomeData...`
But now it does not work like that.
I'm not sure if this is a bug. I think it is more likely I missed something.
It seems like the additional schemas are not getting loaded.

<img width="908" alt="Bildschirmfoto 2019-10-27 um 16 49 42" src="https://user-images.githubusercontent.com/1243826/67637333-d82e1080-f8d9-11e9-8c52-79b078b4ccab.png">

If I change the `default_schema` to "secret" the query works.

It would be nice if someone could help me out. Thanks in advance.

**Comment by mfn** [comment]
We've had this in the past ...
- https://github.com/rebing/graphql-laravel/issues/204
- https://github.com/rebing/graphql-laravel/issues/236

Is only graphiql affected or also the actual API route?

> Lumen Version: 5.5

Really 5.5? That version is very ancient, also Lumen has no LTS ...

Can you try with the latest Lumen version, please?

**Comment by Artem-Schander** [comment]
The regular API is effected too. The graphiql screenshot is only for understanding / context.
You‘re right about the old lumen. I planned to update it after merging the graphql package. I will try to update it tomorrow and let you know if it worked. Thanks for the help.

**Comment by Artem-Schander** [comment]
I have ditched lumen for this project. So I cant tell if I will be able to find some time to tackle this.

**Comment by mfn** [comment]
I feel kinda relieved, TBH. Supporting Lumen is just a PITA 🤷‍♀️
