### ISSUE TITLE
HasMany with non-primary key does not automatically add the needed key to the select fields

### ISSUE THREAD

**Issue by ArturKp** [rebing/graphql-laravel#51]
I have a relation on a model to get all "neighbouring" models, with the same parent_id.

```
public function related()
{
    return $this->hasMany(self::class, 'parent_id', 'parent_id');
}
```

Both keys should most likely be added automatically to select, so Laravel can later join related models, but neither get automatically added.

First key on the base-model I could add like this:
```
'related' => [
    'always'        => ['parent_id'],
    …
]
```

The second key for the retrieved model doesn't get added automatically, so Laravel will eventually return an empty array of related objects.

---

I have narrowed down the issue to be somewhere around `SelectFields:176`. And for my current case I was able to fix it by adding a condition after `$field[$foreignKey] = self::FOREIGN_KEY;`:

```
    $field[$foreignKey] = self::FOREIGN_KEY;
    if( ! in_array($foreignKey, $select))
    {
        $select[] = $foreignKey;
    }
```

But with the lack of tests I am unsure if this is the correct solution or if it will break something else.

**Comment by ArturKp** [comment]
In case anyone else stumbles on the same problem. As a current workaround I will add both `'always' => ['parent_id']` and `'selectable' => false`, which seem to do the trick.

**Comment by rebing** [comment]
#52

**Comment by rebing** [comment]
Nevermind, the fix was not correct, as it breaks other relations...

**Comment by rebing** [comment]
Should be fixed by now
