### ISSUE TITLE
How to I use my own context?

### ISSUE THREAD

**Issue by milewski** [rebing/graphql-laravel#513]
Hi guys, by default the GraphQLController uses the "auth" user as the context, is there anyway I can override this behavior wihout having to create my own copy of GraphQLController::query?

```php
protected function queryContext(string $query, ?array $params, string $schema)
    {
        try {
            return $this->app->make('auth')->user();
        } catch (Exception $e) {
            return null;
        }
    }
```

**Comment by mfn** [comment]
>  wihout having to create my own copy of GraphQLController::query

The current system is designed that you override `GraphQLController::queryContext()` and register your controller in `config/graphql.php`.

Admitted, it's not a very good design. It would be better to have a dedicated factory class which a application an simple bind to their own implementation but this approach has been there for a long time so we're current doing it that way.
