### ISSUE TITLE
Specify Sub-Domain

### ISSUE THREAD

**Issue by WL1981** [rebing/graphql-laravel#514]
Is it possible to specify a sub-domain in addition to the route prefix?

**Comment by georgeboot** [comment]
No it currently is not. Feel free to add a pull request.

What you could do for the interim, is adding the route manually to your preferred routes file:

```php
Route::domain('subdomain.myapp.com')->group(function () {
    Route::post(
        'graphql',
        [\Rebing\GraphQL\GraphQLController::class, 'query']
    )->middleware('first', 'second');
});
```

**Comment by mfn** [comment]
I feel like the original question is kinda answered, PRs are always welcome, but IMHO we don't need an open issue for contributions!
