### ISSUE TITLE
Consider making GraphQL types macroable

### ISSUE THREAD

**Issue by paulomunky1** [rebing/graphql-laravel#518]
Consider making GraphQL type macroable

In my tests I often need to check whether a field exists on the GraphQL type declaration

For example:

```php
use App\GraphQL\Types\UserType;


public function test_that_company_id_attribute_is_included_on_type()
{
   $this->assertTrue($this->hasField('company_id', User::class));
}

protected function hasField($attribute, $graphQLType) {

        $query = app($graphQLType);

        if (!method_exists($query, 'fields')) {

            return false;

        }

        return array_key_exists($attribute, $query->fields());
}

```

In this example, I would like to be able to add the hasField method onto the Type using a Laravel Service Provider when the application boots up. If I could extend the class to include my own methods I could simply do the following in my test:

```php
public function test_that_company_id_attribute_is_included_on_type()
{
   $this->assertTrue(app(User::class)->hasField('company_id));
}
```

**Comment by websitevirtuoso** [comment]
I have this test
https://gist.github.com/websitevirtuoso/b4342d7cc55a15e813fd513f2b1da418

And also check existing field in but in height level. I dont check each type. May be helpful

**Comment by mfn** [comment]
My personal take is that I don't want to include Macroable.

The way macros work is quite magic and very hard to reason about when you've a certain piece of code in front of you and you try to understand how the flo wis.

I think the custom `hasField` method you added is a perfectly reasonable way to do this.

Out of curiosity: what's the use case to check for a field _on type_? (As opposed to the return value from a GraphQL query)

**Comment by paulomunky1** [comment]
Fair enough, I understand the reasoning

As for your question, my example above was a little contrived just to explain the issue - as my own tests are more complex. They go through all of my models and check that all attributes are included on their respective types.

This warns me if I've missed an attribute (I can also exclude attributes in my tests if I don't want them included on the type)

My tests makessure my models and types always have parity - something I find can be easily overlooked due to the fact there's no link between the fields on the graphql type and the fields on the model - saves me a ton of time and mistakes when I make changes to my models

**Comment by mfn** [comment]
Thanks for explaining!

Closing as per https://github.com/rebing/graphql-laravel/issues/518#issuecomment-551971842

**Comment by stevelacey** [comment]
@mfn I agree about Types, but do you feel the same about making `Rebing\GraphQL\GraphQL` macroable? There are loads of little bits of logic I'd love access to via the `GraphQL` facade.
