### ISSUE TITLE
Using flat array in query instead using Eloquent

### ISSUE THREAD

**Issue by websitevirtuoso** [rebing/graphql-laravel#519]
### Question:
I have Property type that has "term" type.
I could create graphql query that fetch all data
https://gist.github.com/websitevirtuoso/fe7290cb4ea43e7a5436fa1a904f10ce
In database property field "term" I store the only key to find all objects
But I also want When I fetch "term" from table property to find by "term" by name to show it
Does it possible to do?

https://gist.github.com/websitevirtuoso/8d5b9e15afb5748e2da0bc6eebe28ff4
https://gist.github.com/websitevirtuoso/96afc8e08d5ec06783ef119f1cb1ad7c
https://gist.github.com/websitevirtuoso/f9315650d0f9280c4f96531e3e576a06

**Comment by mfn** [comment]
>  I store the only key to fins all object

Sorry, what does "fins" mean?

> But I also want When I fetch "term" from table property to find by "term" by name

I apologize I don't exactly understand. I looked at the gists you provided but I'm none the wiser.

But inferring from the title "Using flat array in query instead using Eloquent":

To graphql-laravel it does not matter whether your return an Eloquent model or a plain array: as long as the data structure matches the GraphQL _shape_, it will work.

The reason this works it the _default resolver_ of the webonxy library, which:
- on objects, tries `$object->graphql_field`
- on arrays, tries `$array['graphql_field']`

Does this answer your question?

**Comment by websitevirtuoso** [comment]
Sorry for mistakes.
"find"

I just want to avoid to many eager loading queries. SO I thought to create a flat PHP array and use it as a relational eloquent model. 
But I think it is not possible because I spend a whole day to find a solution but couldn't.

Didn't want to create extra one table to store 10 records

**Comment by mfn** [comment]
> Didn't want to create extra one table to store 10 records

You can implement a custom `resolve` method for a field and simply return a static data shape there.

I do this for certain things which "(almost) never change", like drop down values for gender selection.

>  But I think it is not possible because I spend a whole day to find a solution but couldn't.

If you can provide a _small focused_ example I might be able to help you.

**Comment by websitevirtuoso** [comment]
https://github.com/websitevirtuoso/graphql_demo/tree/feature/add_property_to_grapqhl/app/GraphQL
Here my project. Example of gender is exactly what I am looking for.

There I have filters as well, For example, get only men or only women.
I really have a problem with this. Rely on you

**Comment by mfn** [comment]
Can you point specifically to the part giving you a hard time and what your expectation there would be?

**Comment by websitevirtuoso** [comment]
Yes sure.
https://github.com/websitevirtuoso/graphql_demo/blob/feature/add_property_to_grapqhl/app/GraphQL/Types/Users.php
This is type user here we create field gender

```
            'gender'         => [
                'type' => GraphQL::type('UserGender'),
            ],
```

In the same folder we create new type UserGender
location file
https://gist.github.com/websitevirtuoso/ac8fcfdce02fb323c2034c98e0b45cff

Extend user database migration by adding
```
 $table->string('gender')->nullable();
```
Extend graphql filter 
https://github.com/websitevirtuoso/graphql_demo/blob/feature/add_property_to_grapqhl/app/GraphQL/Types/Filters/UserFilter.php
Add
```
            'gender'  => [
                'name' => 'gender',
                'type' => Type::string()
            ],
```
**Also I should extend eluqient filter but I dont know how.** 
https://github.com/websitevirtuoso/graphql_demo/blob/feature/add_property_to_grapqhl/app/GraphQL/Filters/UserFilter.php

Here we should stoke only key. For example m, w
And when we run UserQuery
https://github.com/websitevirtuoso/graphql_demo/blob/feature/add_property_to_grapqhl/app/GraphQL/Queries/UsersQuery.php
We should receive gender object with name and description

In addition, we should have option filter by gender to get only men or women

**Comment by mfn** [comment]
>       'gender'         => [
>                 'type' => GraphQL::type('UserGender'),
>             ],

I'm not sure what your goal is here.

Is the idea if e.g. `users.gender = 'w'` that this GraphQL type should return the following?
```php
'gender' => [
  'name' => 'w',
  'description' => 'Woman',
],
```

**Comment by websitevirtuoso** [comment]
yes exactly. 'w' is like a foreign key.

**Comment by mfn** [comment]
Then everything I said in https://github.com/rebing/graphql-laravel/issues/519#issuecomment-550960804 still applies, specifically:
> To graphql-laravel it does not matter whether your return an Eloquent model or a plain array: as long as the data structure matches the GraphQL shape, it will work.

I.e., in your case your resolver for gender could look like:
```php
    'gender' => [
        'type' => GraphQL::type('UserGenderType'),
        'resolve' => function (User $user): ?array {
            $description = null;

            switch ($user->gender) {
                case 'w':
                    $description = 'Woman';
                    break;
                case 'm':
                    $description = 'Man';
                    break;
                default:
                    return null;

            }

            return [
                'name' => $user->dender,
                'description' => $description,
            ];
        },
    ],
```

**Comment by websitevirtuoso** [comment]
I got error
```
"debugMessage": "Call to undefined method App\\Models\\User::gender()",
      "message": "Call to undefined method App\\Models\\User::gender()",
```

Because my model doesnt have method gender

**Comment by mfn** [comment]
Please provide the full stack trace

**Comment by websitevirtuoso** [comment]
{
  "errors": [
    {
      "debugMessage": "Call to undefined method App\\Models\\Property::term()",
      "message": "Call to undefined method App\\Models\\Property::term()",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "trace": [
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
          "line": 36,
          "call": "Illuminate\\Database\\Eloquent\\Model::throwBadMethodCallException('term')"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
          "line": 1618,
          "call": "Illuminate\\Database\\Eloquent\\Model::forwardCallTo(instance of Illuminate\\Database\\Eloquent\\Builder, 'term', array(0))"
        },
        {
          "call": "Illuminate\\Database\\Eloquent\\Model::__call('term', array(0))"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/Support/SelectFields.php",
          "line": 181,
          "function": "call_user_func(array(2))"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/Support/SelectFields.php",
          "line": 173,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::handleFields(array(1), array(2), GraphQLType: users, array(12), array(1), null)"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/Support/SelectFields.php",
          "line": 94,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::handleFields(array(1), array(2), GraphQLType: UsersPagination, array(12), array(1), null)"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/Support/SelectFields.php",
          "line": 48,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::getSelectableFieldsAndRelations(array(1), array(2), GraphQLType: UsersPagination, null, true, null)"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/Support/Field.php",
          "line": 198,
          "call": "Rebing\\GraphQL\\Support\\SelectFields::__construct(instance of GraphQL\\Type\\Definition\\ResolveInfo, GraphQLType: UsersPagination, array(1), 5, null)"
        },
        {
          "file": "/var/www/app/GraphQL/Queries/UsersQuery.php",
          "line": 48,
          "call": "Rebing\\GraphQL\\Support\\Field::Rebing\\GraphQL\\Support\\{closure}()"
        },
        {
          "call": "App\\GraphQL\\Queries\\UsersQuery::resolve(null, array(1), null, instance of GraphQL\\Type\\Definition\\ResolveInfo, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/Support/Field.php",
          "line": 207,
          "function": "call_user_func_array(array(2), array(5))"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 632,
          "call": "Rebing\\GraphQL\\Support\\Field::Rebing\\GraphQL\\Support\\{closure}(null, array(1), null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 555,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1247,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Query, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 257,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: Query, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 158,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, null, array(0), null, null)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 90,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, '{\n  users(pagination: {take: 150}) {\n    data {\n      id\n      initiator\n      status\n      expire_at\n      available_at\n      created_at\n      updated_at\n      title\n      description\n      price\n      price_max\n      type {\n        id\n        name\n      }\n      gender {\n        name\n        description\n      }\n      city {\n        id\n        name\n      }\n    }\n  }\n}', null, null, array(0), null, null, null)"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/GraphQL.php",
          "line": 145,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, '{\n  users(pagination: {take: 150}) {\n    data {\n      id\n      initiator\n      status\n      expire_at\n      available_at\n      created_at\n      updated_at\n      title\n      description\n      price\n      price_max\n      type {\n        id\n        name\n      }\n      gender {\n        name\n        description\n      }\n      city {\n        id\n        name\n      }\n    }\n  }\n}', null, null, array(0), null, null)"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/GraphQL.php",
          "line": 123,
          "call": "Rebing\\GraphQL\\GraphQL::queryAndReturnResult('{\n  users(pagination: {take: 150}) {\n    data {\n      id\n      initiator\n      status\n      expire_at\n      available_at\n      created_at\n      updated_at\n      title\n      description\n      price\n      price_max\n      type {\n        id\n        name\n      }\n      term {\n        name\n        description\n      }\n      city {\n        id\n        name\n      }\n    }\n  }\n}', array(0), array(3))"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/GraphQLController.php",
          "line": 76,
          "call": "Rebing\\GraphQL\\GraphQL::query('{\n  users(pagination: {take: 150}) {\n    data {\n      id\n      initiator\n      status\n      expire_at\n      available_at\n      created_at\n      updated_at\n      title\n      description\n      price\n      price_max\n      type {\n        id\n        name\n      }\n      gender {\n        name\n        description\n      }\n      city {\n        id\n        name\n      }\n    }\n  }\n}', array(0), array(3))"
        },
        {
          "file": "/var/www/vendor/rebing/graphql-laravel/src/GraphQLController.php",
          "line": 49,
          "call": "Rebing\\GraphQL\\GraphQLController::executeQuery('public', array(3))"
        },
        {
          "call": "Rebing\\GraphQL\\GraphQLController::query(instance of Illuminate\\Http\\Request, 'public')"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(2))"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(2))"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Rebing\\GraphQL\\GraphQLController, 'query')"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 680,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 130,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/spatie/laravel-cors/src/Cors.php",
          "line": 28,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Spatie\\Cors\\Cors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 105,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 682,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 657,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 623,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 612,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 130,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/spatie/laravel-cors/src/Cors.php",
          "line": 28,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Spatie\\Cors\\Cors::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 105,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/public/index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        }
      ]
    }
  ],
  "data": {
    "users": null
  }
}
```

**Comment by mfn** [comment]
Please try adding `'selectable' => false,` to the GraphQL field, like this:
```php
    'gender' => [
        'type' => GraphQL::type('UserGenderType'),
        'selectable' => false,
        'resolve' => function (User $user): ?array {
…
```
Does that work?

**Comment by websitevirtuoso** [comment]
Yes awesome. It is working.
Finally good news. Thank you very much

**Comment by mfn** [comment]
👍
