### ISSUE TITLE
File upload methods

### ISSUE THREAD

**Issue by samuelhgf** [rebing/graphql-laravel#523]
Where is the documentation to handle with file uploads? Move them, change their name, staffs like that

**Comment by mfn** [comment]
File uploads are explained here: https://github.com/rebing/graphql-laravel#file-uploads

What is it you're missing?

**Comment by mfn** [comment]
Also, please use the issue template in the future, thanks.

**Comment by samuelhgf** [comment]
I knew about this. But, which are the methods availables to handle with the file?

**Comment by mfn** [comment]
In your resolver `dump($args)`, you will find the files there.

Should be called `UploadedFile` I believe and from there the documentation from https://laravel.com/docs/6.x/filesystem#file-uploads applies.

**Comment by mfn** [comment]
No feedback, assuming issue is solved
