### ISSUE TITLE
Access some arg inside the args method

### ISSUE THREAD

**Issue by samuelhgf** [rebing/graphql-laravel#526]
### Versions:
- graphql-laravel Version: 2.1
- Laravel Version: 5.8 
- PHP Version: 7.2

### Question:

I would like to know if it is possible to acces a arg inside the args method. I need to make a custom validation of a arg that depends the number putted in other arg.

**Comment by mfn** [comment]
In the resolver you should be able to access all `$args` given for the query.

If this isn't the case please provide more details (query, types, example, etc.)

**Comment by samuelhgf** [comment]
Solved! Just use the rules method that uses the args. And then make a custom rule using function, passing any of args I want.

Thank you!
