### ISSUE TITLE
Call the method authorize before resolve the args and validations

### ISSUE THREAD

**Issue by samuelhgf** [rebing/graphql-laravel#529]
### Summary

I'm trying to make a validation that ignores certain column passing the id of the row. But the id that I want to access is through the authenticated user, using the auth()->user() method, that returns me the model of the authenticated use. By then i can access any relation and id that a want.

But when the GraphQL makes the validation of the args, the authenticate method is not called yet, by so i do not have access to the authenticated user inside the args rules.

One solution: make the validation inside the resolve method

`$validator = Validator::make($args, [
            'email' => [
                'required',
                Rule::unique('user_login')->ignore($userLoginModel),
            ]
        ]);`

`if($validator->fails())
        {
            throw new ValidationException($validator);
        }`

**Comment by mfn** [comment]
Please read up on https://github.com/rebing/graphql-laravel/issues/481 for the current stance on why the order is the way it is.

There are no current plans to change it.

Another takeaway could be: if you need a custom workflow, don't use authorize but make a custom solution in your resolver.

**Comment by illambo** [comment]
Hi, you can use a simple trait like this where to turn over the order:

```
use Closure;
use Rebing\GraphQL\Error\AuthorizationError;
use Rebing\GraphQL\Error\ValidationError;
use Rebing\GraphQL\Support\SelectFields;

Trait PerformAuthorizeBeforeValidation
{
    protected function getResolver(): ?Closure
    {
        if (! method_exists($this, 'resolve')) {
            return null;
        }

        $resolver = [$this, 'resolve'];
        $authorize = [$this, 'authorize'];

        return function () use ($resolver, $authorize) {
            // 0 - the "root" object; `null` for queries, otherwise the parent of a type
            // 1 - the provided `args` of the query or type (if applicable), empty array otherwise
            // 2 - the "GraphQL query context" (see \Rebing\GraphQL\GraphQLController::queryContext)
            // 3 - \GraphQL\Type\Definition\ResolveInfo as provided by the underlying GraphQL PHP library
            // 4 (!) - added by this library, encapsulates creating a `SelectFields` instance
            $arguments = func_get_args();

            // Authorize
            if (call_user_func_array($authorize, $arguments) != true) {
                throw new AuthorizationError('Unauthorized');
            }

            // Validate mutation arguments
            $args = $arguments[1];
            $rules = call_user_func_array([$this, 'getRules'], [$args]);
            if (count($rules)) {

                // allow our error messages to be customised
                $messages = $this->validationErrorMessages($args);

                $validator = Validator::make($args, $rules, $messages);
                if ($validator->fails()) {
                    throw new ValidationError('validation', $validator);
                }
            }

            // Add the 'selects and relations' feature as 5th arg
            if (isset($arguments[3])) {
                $arguments[] = function (int $depth = null) use ($arguments): SelectFields {
                    $ctx = $arguments[2] ?? null;

                    return new SelectFields($arguments[3], $this->type(), $arguments[1], $depth ?? 5, $ctx);
                };
            }

            return call_user_func_array($resolver, $arguments);
        };
    }
}
```

**Comment by mfn** [comment]
The downside is, it copies the `getResolver()`

If you compare your version to the one from the `master` branch (no release yet), it's quite different due to new features (argument aliasing, dependency injection), so be aware of the downsides of this approach.

As mentioned, it's best to implement it _within_ your resolver.

**Comment by illambo** [comment]
@mfn thanks for the suggestion, could give me an example so as not to misunderstand ?
Thanks
