### ISSUE TITLE
Porting changes back to the original repository?

### ISSUE THREAD

**Issue by ArturKp** [rebing/graphql-laravel#55]
As @inxilpro also pointed out in #12 that it's a fork from the original laravel-graphql package. Maybe we can collaboratively port all of these changes back to the original and bigger repository? As I haven't had any experience with the original project I am not aware of all the differences. But it doesn't seem wise in the long run to develop two packages with a similar purpose before trying to combine efforts. 

Maybe we can start by listing all the differences in the two packages? Then we can analyze how difficult would it be to port these changes back to the original repo? Additionally are there any incompatibilities with these two repos or has the original implemented some breaking changes? For some differences maybe we can simply make the original repository somehow more extensible but to keep the main logic in one place. I would be more than happy to help with the PR-s to the "Folkloreatelier/laravel-graphql" but I would first like to understand all the differences.

Maybe @rebing (and also @dmongeau) can comment on this subject?

**Comment by rebing** [comment]
Sure, it would be nice, if the repositories were merged, but I feel they have diverged too much by now. Some features that this repository has and the main one doesn't:

- Authorization
- Privacy
- Advanced eager loading (SelectFields, that's a big one)
- Pagination
- Batching

Many of these are probably not even wanted by the main repository, but I use all those features, so I could not do without those.

**Comment by dmongeau** [comment]
Hello,
I'm always open to PR on the "original" repository. To be honest I was not aware that there was another package being developed proactively. Probably because I'm kind of busy these days. I would be happy to help on implementing the features you listed, since it was the idea in the first place (make it easy to use with laravel and have some extra laravel related features, such as the ones you listed). But, since this cannot rely entirely on me (I guess this is the reason you started this package), my opinion is that it should requires that I give control of the repo to other maintainers, which I'm willing to do.

What do you think?

Cheers

**Comment by rebing** [comment]
@dmongeau I don't have much time either, but if you think it would be okay to port all additional features from this repository to your, then I'd willing to contribute as much as I can. I see that you've also added test cases, so these should be created for the new features as well, which should make the transition easier.

**Comment by spamoom** [comment]
Perhaps we introduce the best of both worlds?

Maintain the original and "clean" repo - we then introduce some smaller repos, each providing plug-in opinionated functionality that is currently in this repo (ie, a [few ways](http://graphql.org/learn/pagination/) to implement pagination).

I was about to do the above for pagination as I wanted to use the Folkloreatelier package but the pagination from this one

**Comment by websitevirtuoso** [comment]
The main repo doesnt support anymore (lack new features and response to issues). I use this repo and it is very good.

**Comment by anolek** [comment]
@websitevirtuoso You are right, i agree with you, this repo has more features and is active.

**Comment by websitevirtuoso** [comment]
I would offer to create slack channel to ask, offer, discuss etc

**Comment by rebing** [comment]
I'll be happy to join, if you create a Slack workspace :)

**Comment by websitevirtuoso** [comment]
> I'll be happy to join, if you create a Slack workspace :)
I created slack, join 
[https://join.slack.com/t/rebing-graphql/shared_invite/enQtNTE5NjQzNDI5MzQ4LWVjMTMxNzIyZjBlNTFhZGQ5MDVjZDAwZDNjODA3ODE2NjdiOGJkMjMwMTZkZmNhZjhiYTE1MjEyNDk0MWJmMzk](url)

Add link to readme please
[![Get on Slack](https://img.shields.io/badge/slack-join-orange.svg)](https://join.slack.com/t/rebing-graphql/shared_invite/enQtNTE5NjQzNDI5MzQ4LWVjMTMxNzIyZjBlNTFhZGQ5MDVjZDAwZDNjODA3ODE2NjdiOGJkMjMwMTZkZmNhZjhiYTE1MjEyNDk0MWJmMzk)
