### ISSUE TITLE
New release: 3.2?

### ISSUE THREAD

**Issue by dnyg** [rebing/graphql-laravel#556]
There has been a lot of excellent work since the last release (which was 36 days ago).

Are there any plans for setting up a new release within a reasonable timeframe?

**Comment by mfn** [comment]
I just tagged https://github.com/rebing/graphql-laravel/releases/tag/4.0.0-rc1 (will usually wait a few days to gather feedback before non-pre release).

Unfortunately no more 3.x releases, as some of the changes break with semver.
