### ISSUE TITLE
Privacy attribute only utilized on root level type

### ISSUE THREAD

**Issue by GaryReckard** [rebing/graphql-laravel#565]
### Versions:
- graphql-laravel Version: 4.0.0
- Laravel Version: 5.5.43 
- PHP Version: 7.2

### Description:

When defining the `privacy` attribute in the `Type` definition, it doesn't seem to execute unless that Type is the root level type. 

So, for instance, I have a `ProductType`, and I add a `privacy` attribute for the `entry_id` field
```
'privacy' => function (array $args): bool {
         return false;
},
```
and that works as expected. I get 'null' when I query for that field _(see example query further down below)_

Then I have another field in the `ProductType`
```
'warehouse_items' => [
    'type' => Type::listOf(\GraphQL::type('warehouse_item')),
    'description' => 'The warehouse item.',
    'args' => [
        'warehouses'    => [
            'name' => 'warehouses',
            'type' => Type::listOf(Type::string()),
            'rules' => ['required']
        ]
    ]
],
```
and `WarehouseItemType` is its own type. In `WarehouseItemType`, I have added a `privacy` attribute on the `base_cost` field, same as the example above, but it never gets used. 

So, with that same `return false;` privacy attribute on the ProductType->entry_id, and WarehouseItemType->base_cost, this query still returns a value for `base_cost`:
```
{
    product(sku: "ABCD-123") {
        sku
        entry_id
        title
        description
        warehouse_items(warehouses: ["01","02","03"]){
		base_cost
        	fut_list_price
		avg_lead_time
        }
    }
}
```

If I were to just run a query on my `warehouse_items`, the `privacy` attribute would take effect...

### Steps To Reproduce:

_see description for simple example_

**Comment by mfn** [comment]
Are you using `SelectFields`? How does the product query resolver look like?

I checked the tests, I couldn't find a specific one for this case so I had to modify one quickly:
```diff
diff --git a/tests/Database/SelectFields/ValidateFieldTests/CommentType.php b/tests/Database/SelectFields/ValidateFieldTests/CommentType.php
index 0de7c65..5348082 100644
--- a/tests/Database/SelectFields/ValidateFieldTests/CommentType.php
+++ b/tests/Database/SelectFields/ValidateFieldTests/CommentType.php
@@ -25,6 +25,9 @@ class CommentType extends GraphQLType
                 'type' => Type::nonNull(Type::ID()),
             ],
             'title' => [
+                'privacy' => function () {
+                    return false;
+                },
                 'type' => Type::nonNull(Type::string()),
             ],
         ];
diff --git a/tests/Database/SelectFields/ValidateFieldTests/ValidateFieldTest.php b/tests/Database/SelectFields/ValidateFieldTests/ValidateFieldTest.php
index d717c5f..0e26e6a 100644
--- a/tests/Database/SelectFields/ValidateFieldTests/ValidateFieldTest.php
+++ b/tests/Database/SelectFields/ValidateFieldTests/ValidateFieldTest.php
@@ -37,6 +37,7 @@ class ValidateFieldTest extends TestCaseDatabase
     title
     comments {
       id
+      title
     }
   }
 }
@@ -49,7 +50,7 @@ GRAQPHQL;
         $this->assertSqlQueries(
             <<<'SQL'
 select "posts"."title", "posts"."id" from "posts";
-select "comments"."id", "comments"."post_id" from "comments" where "comments"."post_id" in (?) order by "comments"."id" asc;
+select "comments"."id", "comments"."title", "comments"."post_id" from "comments" where "comments"."post_id" in (?) order by "comments"."id" asc;
 SQL
         );
 
@@ -62,6 +63,7 @@ SQL
                         'comments' => [
                             [
                                 'id' => (string) $comment->id,
+                                'title' => 'comment title',
                             ],
                         ],
                     ],
```
If I run the test `\Rebing\GraphQL\Tests\Database\SelectFields\ValidateFieldTests\ValidateFieldTest::testSelectableFalse`, then it fails _beause_ I `return false` from the new `'privacy'` field. If I `return true;`, the test is green.

To me this looks like this works correctly?

**Comment by GaryReckard** [comment]
Hi there @mfn. I just found out that in my ProductQuery resolver, if I do NOT call the `Closure $getSelectFields`, as in `$fields = $getSelectFields();`, then the privacy attributes I set on my `ProductType` do not take effect.

If I do call that Closure, then the privacy attributes on my `ProductType` work.

My problem is, one of the fields in my `ProductType` is of type `WarehouseItemType`. How do I get GraphQL to process those privacy attributes on the `WarehouseItemType` fields when calling a `ProductQuery`?

**Comment by mfn** [comment]
>  I just found out that in my ProductQuery resolver, if I do NOT call the Closure $getSelectFields, as in $fields = $getSelectFields();, then the privacy attributes I set on my ProductType do not take effect.

Right, the whole `'pivacy'` setting only works with `SelectFields`.

> My problem is, one of the fields in my ProductType is of type WarehouseItemType. How do I get GraphQL to process those privacy attributes on the WarehouseItemType fields when calling a ProductQuery?

Ok, this I don't understand. It's like describing the oppositie of above.

The TL;DR is, you need to use `SelectFields` to make it work

**Comment by GaryReckard** [comment]
Hi again @mfn, and thank you for your help with this.

Ok, I didn't realize that `SelectFields` was a requirement for utilizing the `privacy` attribute feature. It doesn't specify that in the docs, I feel that should be made more clear. From reading the [docs](https://github.com/rebing/graphql-laravel#privacy), I assumed that that `privacy` function would get called regardless. 

And that (incorrect) assumption is why I was confused about the privacy attribute not being used in my WarehouseItemType, when that type was the return type of a field defined in my ProductType. 

Makes sense now, and I have an alternate route I can go to enforce field-level permissions. Thanks again!

**Comment by mfn** [comment]
I totally agree, the docs aren't doing a good job clearing up what parts are GraphQL intrinsic (i.e. part of the underlying webonxy library) and what parts are due to the optional `SelectFields` feature.
