### ISSUE TITLE
Specify relation that will not be included in `with`

### ISSUE THREAD

**Issue by JakeBooher** [rebing/graphql-laravel#567]
### Versions:
- graphql-laravel Version: 3.1.0
- Laravel Version: 6.7.0
- PHP Version: 7.3.8

### Question:

When defining the `model` attribute in my GraphQL type I'm able to use `with` to load some additional data via joins:

```
        $fields = $getSelectFields();
        $select = $fields->getSelect();
        $with = $fields->getRelations();
        $root->with($with);
```

However, this doesn't play super nice with some of my relations (specifically some `belongsToMany` relations I have that go through a pivot table) and I'd like to exclude these from being output in `$fields->getRelations()`. How would I go about doing this?

**Comment by mfn** [comment]
> exclude

Can you try if `'selectable' => false` works for you?

**Comment by crissi** [comment]
and is_relation = false

**Comment by mfn** [comment]
Closing due to no feedback
