### ISSUE TITLE
multiple schema on lumen not find query or mutation

### ISSUE THREAD

**Issue by amirhossein320** [rebing/graphql-laravel#568]
**i receive this error**

 **Cannot query field \"users\" on type \"Query\".** 

**middleware in admin schema work  but query and mutation not work**

**my schemas**

```
'schemas' => [
        'default' => [
            'query' => [
            ],
            'mutation' => [
            ],
            'middleware' => [],
            'method' => ['get', 'post'],
        ],
        'admin' => [
            'query' => [
                'users' => UsersQuery::class,
            ],
            'mutation' => [
            ],
            'middleware' => ['admin_auth'],
            'method' => ['get', 'post'],
        ],
    ],
```
my **url** request on postman 

**http://localhost:8000/graphql/admin**

```
query fetchUsers{
    
    users(limit:20,  page: 2) {
        data{
            id, profile{
                name
            }
        },
        total,
        per_page

    }
}
```

**Comment by mfn** [comment]
https://github.com/rebing/graphql-laravel/issues/509
https://github.com/rebing/graphql-laravel/issues/204

Contributions / fixes welcome!

**Comment by LuizVisnadi** [comment]
Having the same problem on Lumen, I've looked into this package's code and found the possible source of error.

https://github.com/rebing/graphql-laravel/blob/20349a5aa0997b996b799147362e8343134e1420/src/GraphQLController.php#L31-L34

On line 32, changing the comparison from **"> 1"** to **"> 0"** seems to fix the problem.

**Comment by Vespira** [comment]
I've experienced the same issue, and I think in this piece of code : 

```php
public function query(Request $request, string $schema = null): JsonResponse
    {
        $middleware = new GraphQLUploadMiddleware();
        $request = $middleware->processRequest($request);

        // If there are multiple route params we can expect that there
        // will be a schema name that has to be built
        $routeParameters = $this->getRouteParameters($request);
        if (count($routeParameters) > 1) {
            $schema = implode('/', $routeParameters);
        }
```

for some reason, Lumen does not fill the `$schema` arg, so when we have only one route depth, `$schema` is still null, hence only the **default_schema** work.
In case of error in the schema targeting, all queries and mutations are triggered on the default schema.

Anyway, @LuizVisnadi do you want to open a pull request to push this little change ?
This function works with only one route parameter, so I don't think it's impacting ? But mainteners have a wider understanding so, I hope someone could make us a feedback please :)

**Comment by mfn** [comment]
Multiple schemas work well in Laravel and there was a recent improvement done regarding types, see https://github.com/rebing/graphql-laravel/releases/tag/6.4.0 .

Lumen only brings headaches and has no proper unit test environment, I'm planning to remove support for Lumen entirely -> see https://github.com/rebing/graphql-laravel/pull/722
