### ISSUE TITLE
Nested filter on Polymorphic, Many-To-Many relationship

### ISSUE THREAD

**Issue by NickSeger** [rebing/graphql-laravel#569]
### Versions:
- graphql-laravel Version: 3.1
- Laravel Version: 6.9
- PHP Version: 7.2

### Question:

Hey,

Getting great results with this package but just running into a big of a wall with a polymorphic, many-to-many relationship for my user roles and permissions (using the Laratrust package).

I have no problem doing a simple query to get my users and the roles/permissions but if I try to setup a nested filter, for example to only get a list of users that have the role type **planner** associated to them I can't get it to filter the users, I can only seem to get the roles to filter, for example, in a very basic test I added this resolver function:

    public function resolveRolesField($query)
    {
        return $query->roles()->where('id', '=', 1)->get();
    }

This limits the roles correctly but users without that role just end up with empty objects. e.g.

    "data": [
            {
              "id": "1",
              "name": "Mr. Skye Lind",
              "employee_number": "i496472",
              "email": "emorissette@example.com",
              "created_at": "2019-09-14T12:52:05+00:00",
              "updated_at": "2019-09-14T12:52:05+00:00",
              "roles": [
                {
                  "id": "1",
                  "name": "planner",
                  "display_name": "Planner",
                  "description": "Involved in planning ROMs",
                  "created_at": null,
                  "updated_at": null
                }
              ],
            },
            {
              "id": "2",
              "name": "Louisa Corwin",
              "employee_number": "i673562",
              "email": "katherine16@example.com",
              "created_at": "2019-09-14T12:52:05+00:00",
              "updated_at": "2019-09-14T12:52:05+00:00",
              "roles": [],
            },
        ]

In that example user with record id: 2 shouldn't be returned as they don't have the planner role.

I thought about doing it in my Users query directly and had a bit of success but then faced the issue where I couldn't access the args from the nested filter in the closure of the Users query resolver.

Has anyone had any success with something similar, I'm thinking I might just have to do this on the front-end but would really love to limit the amount of data being pulled rather than hiding it on the client side.

Thanks,
Nick

**Comment by NickSeger** [comment]
So I figured this out however I'm worried that it's a bit hacky, going to leave my current solution here in case someone has a nicer way of solving this issue or if it might help someone else.

In the above example I've made the following changes to the User Type and the Users (plural) Query:

      //added the ID filter to the args
         'args' => [
               'filter' => [
                      'name' => 'id',
                      'type' => Type::listOf(Type::id()),
               ]
         ],
         'resolve'     => function($query) {
                        return $query->roles()->get();
         }

    //changed the resolve function and added a protected function to reduce repeated code
            $roles      = isSet($with[ 'roles' ]);
            $roleFilter = false;
            $roleArgs   = [];
            
            $permissions      = isSet($with[ 'permissions' ]);
            $permissionFilter = false;
            $permissionArgs   = [];
            
            if ($roles) {
                $roleStaticFilterData = $this->getClosureStaticVariables($with, 'roles');
                if (!empty($roleStaticFilterData)) {
                    $roleArgs   = $roleStaticFilterData[ 'id' ];
                    $roleFilter = true;
                }
            }
            
            if ($permissions) {
                $permissionStaticFilterData = $this->getClosureStaticVariables($with, 'permissions');
                if (!empty($permissionStaticFilterData)) {
                    $permissionArgs   = $permissionStaticFilterData[ 'id' ];
                    $permissionFilter = true;
                }
            }
            
            if ((empty($roleArgs) && empty($permissionArgs)) || (!$roleFilter && !$permissionFilter)) {
                return User::select($select)->with($with)->apifilter(new
                UserFilter
                ($args))->apiSortable($args)->paginate(Arr::get($args, 'pagination.take'), ['*'], 'page',
                    Arr::get($args,
                        'pagination.page'));
            } elseif ($roleFilter && $permissionFilter) {
                return User::select($select)->whereHas('roles', function ($query) use ($roleArgs) {
                    $query->whereIn('id', $roleArgs);
                })->whereHas('permissions', function ($query) use ($permissionArgs) {
                    $query->whereIn('id', $permissionArgs);
                })->apifilter(new
                UserFilter
                ($args))->apiSortable($args)->paginate(Arr::get($args, 'pagination.take'), ['*'], 'page',
                    Arr::get($args,
                        'pagination.page'));
            }
            
            $relation = 'roles';
            $filter   = $roleArgs;
            if (empty($roleArgs)) {
                $relation = 'permissions';
                $filter   = $permissionArgs;
            }
            
            return User::select($select)->whereHas($relation, function ($query) use ($filter) {
                $query->whereIn('id', $filter);
            })->apifilter(new
            UserFilter
            ($args))->apiSortable($args)->paginate(Arr::get($args, 'pagination.take'), ['*'], 'page',
                Arr::get($args,
                    'pagination.page'));
        }
        
        protected function getClosureStaticVariables($closure, $filter)
        {
            $closure                = $closure[ $filter ];
            $closureReflection      = new ReflectionFunction($closure);
            $closureStaticVariables = $closureReflection->getStaticVariables();
            return $closureStaticVariables[ 'requestedFields' ][ 'args' ];
        }

I'm going to try to find a way to clean this up as it means a lot of repeated code when adding a new nested filter, again, this is a pretty hacky way to get my result but if anyone has a better way would love to hear it.

Thanks,
Nick

**Comment by crissi** [comment]
Combining eager loading https://github.com/rebing/graphql-laravel#eager-loading-relationships and query params should do the trick, https://github.com/rebing/graphql-laravel#type-relationship-query

**Comment by NickSeger** [comment]
OMG! @crissi you're a legend... This has been killing me for the past few days and it was as simple as that. 

Thing is, one late night, I swear I tried exactly that but probably implemented it wrong and wrote it off. Thanks a bunch, massively cleans up the amount of effort, luckily I'd only been using the one use case so far. Thanks, again.

**Comment by NickSeger** [comment]
@crissi sorry to re-open this but I just realised why this wasn't giving me the right results when I tried it, doing the query in the relationship doesn't actually filter the users (in this example). It will filter the roles correctly but a user without that role just appears with an empty role object where as I'm looking for it to not be returned at all, which is what I got to occur doing the query upfront in the users query.

Thanks for any further assistance,
Nick

**Comment by crissi** [comment]
It would help if you posted your graphql query. 

You want the user not to be returned when you are filtering roles and it does not match?!?

**Comment by NickSeger** [comment]
Sure, here's the query:

    query usersPage($pagination: Pagination, $userFilter: UserFilter, $roleFilter: RoleFilter, 
    $permissionFilter: PermissionFilter) {
      users(filter: $userFilter, pagination: $pagination) {
        data {
          id
          name
          employee_number
          email
          created_at
          updated_at
          roles(filter: $roleFilter) {
            id
            name
            display_name
            description
            created_at
            updated_at
          }
          permissions(filter: $permissionFilter) {
            id
            name
            display_name
            description
            created_at
            updated_at
          }
        }
        total
        hasPages
      }
    }

And yes, my expected outcome would be to get the users based on which role I am filtering in that relationship, I am trying to limit the amount of data returned up front in the query rather than having to filter on the client side if I can help it.

**Comment by crissi** [comment]
If I understand correctly your usecase is a bit special, since you want a child type/relationship to affect the main type/query. I think this is generally should be avoided and instead add a user filter like only usersWithRoleIds.

but you can probably do like this in your resolve method to get child params:
$info is the resolveInfo object.

`$childArgs = (new ResolveInfoFieldsAndArguments($info))->getFieldsAndArgumentsSelection(5);`

**Comment by NickSeger** [comment]
@crissi got ya, have changed my approach and doing the filter on the users as you suggested but that's good to know how to get the child args in the query for future. Thank for the help.

**Comment by websitevirtuoso** [comment]
I also have the same problem, almost have the same query with nested filters, sorting etc etc.

```
query Listings {
    listings {
        total
        data {
            id
            media(filter: {is_primary: true}) {
                id
                uuid
                file_name
                mime_type
                size
                responsive_tag
                created_at
                updated_at
            }
        }
    }
}
```
I know how to use "resolver" but it created n+1 query problem
```
'selectable' => false,
'resolve' => function ($query, array $args): ?array {
```

I need In main gql query use "with" and apply where to get desired behaviour
```
public function resolve(mixed $root, array $args, $ctx, ResolveInfo $info, SelectFields $fields): LengthAwarePaginator
    {
//        $childArgs = (new ResolveInfoFieldsAndArguments($info))->getFieldsAndArgumentsSelection(5);
        $builder = Listing::select($fields->getSelect())->with($fields->getRelations())
//            ->with(['media' => fn ($q) => $q->where('collection_name', 'media')->where('order_column', 1)])
//            ->with(['media' => fn ($q) => $q->apiFilter(new ListingMediaFilter($args))->apiSortable(new ListingMediaSorter($args))])
//            ->with('media')
            ->apiFilter(new ListingFilter($args))
            ->apiSortable(new ListingSorter($args));

        $searchQ = Arr::get($args, 'filter.search');
        if ($searchQ) {
            $builder = Listing::search($searchQ)->constrain($builder);
        }

        return $builder->paginate(perPage: Arr::get($args, 'pagination.take'), page: Arr::get($args, 'pagination.page'));
    }
```

But for this I need to get child args. I have no Idea how to do this with latest lib.
I tried $childArgs = (new ResolveInfoFieldsAndArguments($info))->getFieldsAndArgumentsSelection(5); but class
ResolveInfoFieldsAndArguments doesn't exist.

Could you assis how to get childArgs?

@NickSeger 
@crissi

**Comment by websitevirtuoso** [comment]
Thanks For fas answer. But this class doesn't work.
I am getting error
```
"debugMessage": "Undefined property: GraphQL\\Language\\AST\\ObjectValueNode::$value",

            "trace": [
                {
                    "file": "/var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php",
                    "line": 250,
                    "call": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions::handleError(2, 'Undefined property: GraphQL\\Language\\AST\\ObjectValueNode::$value', '/var/www/app/Modules/Listing/GraphQL/Queries/ResolveFieldArgumentsUtil.php', 145)"
                },
                {
                    "file": "/var/www/app/Modules/Listing/GraphQL/Queries/ResolveFieldArgumentsUtil.php",
                    "line": 145,
                    "call": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions::Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined property: GraphQL\\Language\\AST\\ObjectValueNode::$value', '/var/www/app/Modules/Listing/GraphQL/Queries/ResolveFieldArgumentsUtil.php', 145)"
                },
                
                
                error in this method.
                
    /**
     * @return mixed
     */
    private function getValue(ArgumentNode $argumentNode)
    {
        $value = $argumentNode->value;

        if ($value instanceof VariableNode) {
            $variableName = $value->name->value;

            return $this->info->variableValues[$variableName];
        }

        return $argumentNode->value->value;
    }
```

I have relation MorphMany. From laravel spatie media lib. Trying to migrate media and reuse their functions.

My query has many fields and relations. 
```
query Listings {
    listings {
        total
        data {
            id
            media(filter: {is_primary: true}) {
                id
                uuid
                file_name
                mime_type
                size
                responsive_tag
                created_at
                updated_at
            }
            user {
                id
                email
                first_name
                last_name
                phone
                postal_code
                address
                notify
                status
                created_at
                updated_at
                email_verified_at
            }
            city {
                id
                name
                lat
                lng
            }
            type {
                id
                name
                description
            }
            features
            term {
                id
                name
                description
            }
            initiator {
                id
                name
                url
            }
        }
    }
}
```

I have no idea but I can't apply  filter to morhp many like this
```
'media'        => [
                'type'  => Type::listOf(GraphQL::type('ListingMedias')),
                'args'  => [
                    'filter' => ['name' => 'filter', 'type' => GraphQL::type('ListingMediaFilter')],
                    'sort'   => ['name' => 'sort', 'type' => GraphQL::type('Sortable')]
                ],
                'query' => static function (array $args, $query) {

//                    dd($query);
//                    return $query->get()->where('collection_name', 'media')
//                        ->where('order_column', 1);

//                    return $query->with(['media' => fn ($q) => $q->where('collection_name', 'media')
//                        ->where('order_column', 1)]);
//                    return $query;
                    return $query->apiFilter(new ListingMediaFilter($args))->apiSortable(new ListingMediaSorter($args));
                }
            ],
```

It just doesn't work and lead to errors. But I found a way that I can apply where and sorting options on main resolver
```
public function resolve(mixed $root, array $args, $ctx, ResolveInfo $info, SelectFields $fields): LengthAwarePaginator
    {
        $args = (new ResolveFieldArgumentsUtil($info))->getFieldSelection(2);
        dd($args);
//        $childArgs = (new ResolveInfoFieldsAndArguments($info))->getFieldsAndArgumentsSelection(5);
        $builder = Listing::select($fields->getSelect())->with($fields->getRelations())
//            ->with(['media' => fn ($q) => $q->where('collection_name', 'media')->where('order_column', 1)])
//            ->with(['media' => fn ($q) => $q->apiFilter(new ListingMediaFilter($args))->apiSortable(new ListingMediaSorter($args))])
//            ->with('media')
            ->apiFilter(new ListingFilter($args))
            ->apiSortable(new ListingSorter($args));

        $searchQ = Arr::get($args, 'filter.search');
        if ($searchQ) {
            $builder = Listing::search($searchQ)->constrain($builder);
        }

        return $builder->paginate(perPage: Arr::get($args, 'pagination.take'), page: Arr::get($args, 'pagination.page'));
    }
```
and it works and solve problem with n+1 problem.

I am using latest version of this package. I also can create small repo to reproduce the error

**Comment by websitevirtuoso** [comment]
Great. I had an error but could find error and fix it in method

    ```
    private function getValue(ArgumentNode $argumentNode)
    {
        $value = $argumentNode->value;

        if ($value instanceof VariableNode) {
            $variableName = $value->name->value;

            return $this->info->variableValues[$variableName];
        }

        return $argumentNode->value;
    }
    ```
    it was
   
        return $argumentNode->value->value;
        should be 
        
        return $argumentNode->value;
I think you should create a note about case like this one in the documentation
give example of how it can be solved
Place this class as a helper class.

Let me know about your thoughts
@mfn

**Comment by websitevirtuoso** [comment]
I had to change method getValue.
I will leave it here if somebody would like to use it

```
private function getValue(ArgumentNode $argumentNode): mixed
    {
        $value = $argumentNode->value;
        
        if ($value instanceof ObjectValueNode) {
            $v = [];
            foreach ($value->fields->getIterator() as $field) {
                $v[$field->name->value] = $field->value->value;
            }

            return $v;
        }

        return $argumentNode->value;
    }
```

**Comment by websitevirtuoso** [comment]
I could implement everything that I needed. I have no idea why I can't use my default filtering and sorting approach on MorphMany relationship.
```
"debugMessage": "Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\MorphMany::apiFilter()",
```
if somebody will fix it or do more elegant please let me know

Here example How I could do this. Some methods inside class just for illustration

```
<?php

namespace App\Modules\Listing\GraphQL\Queries;

use App\Modules\Listing\GraphQL\Filters\ListingFilter;
use App\Modules\Listing\GraphQL\Filters\ListingMediaFilter;
use App\Modules\Listing\GraphQL\Sorters\ListingMediaSorter;
use App\Modules\Listing\GraphQL\Sorters\ListingSorter;
use App\Modules\Listing\Models\Listing;
use Closure;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type as GraphqlType;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Rebing\GraphQL\Support\Facades\GraphQL;
use Rebing\GraphQL\Support\Query;
use Rebing\GraphQL\Support\SelectFields;

class ListingsQuery extends Query
{
    /** @var array<string, string> $attributes */
    protected $attributes = [
        'name'        => 'Listings Query',
        'description' => 'A query of listings'
    ];

    public function type(): GraphqlType
    {
        return GraphQL::paginate('Listings');
    }

    public function args(): array
    {
        return [
            'filter'     => ['name' => 'filter', 'type' => GraphQL::type('ListingFilter')],
            'pagination' => ['name' => 'pagination', 'type' => GraphQL::type('Pagination')],
            'sort'       => ['name' => 'sort', 'type' => GraphQL::type('Sortable')]
        ];
    }

    /**
     * @param mixed        $root
     * @param array        $args
     * @param mixed        $ctx
     * @param ResolveInfo  $info
     * @param SelectFields $fields
     *
     * @return LengthAwarePaginator
     */
    public function resolve(mixed $root, array $args, $ctx, ResolveInfo $info, SelectFields $fields): LengthAwarePaginator
    {
        $args = (new ResolveFieldArgumentsUtil($info))->getFieldSelection(1);

        $builder = Listing::select($fields->getSelect())->with($fields->getRelations())
//            ->with(['media' => fn ($q) => $q->where('collection_name', 'media')->where('order_column', 1)])
//            ->with(['media' => fn ($q) => $q->apiFilter(new ListingMediaFilter($args))->apiSortable(new ListingMediaSorter($args))])
            ->apiFilter(new ListingFilter($args))
            ->apiSortable(new ListingSorter($args));
        
        if(Arr::get($args, 'data.fields.media.args')) {
            $mediaArgs = Arr::get($args, 'data.fields.media.args');
            $builder->with(['media' => function ($builder) use ($mediaArgs) {
                $builder->where('collection_name', 'media');
                $this->construct($mediaArgs)->apply($builder);
//                if(isset($filterBy['is_primary'])) {
//                    $q->where('order_column', ($filterBy['is_primary'] ? '=' : '>'), 1);
//                }
//                    ->apiFilter(new ListingMediaFilter($filterBy));
//                $q = (new ListingMediaFilter($filterBy))->collectionFilter($q);
//                    ->apiSortable(new ListingMediaSorter($args))->where('order_column', 1)
            }]);
        }

        $searchQ = Arr::get($args, 'filter.search');
        if ($searchQ) {
            $builder = Listing::search($searchQ)->constrain($builder);
        }

        return $builder->paginate(perPage: Arr::get($args, 'pagination.take'), page: Arr::get($args, 'pagination.page'));
    }


    // filtering class ,tmp here
    protected $builder;
    // argument from graphql input object
    protected array $args = [];

    public function construct(array $args = [])
    {
        $this->args = $args;
        return $this;
    }

    /**
     * @param $builder
     */
    public function apply($builder) :void
    {
        $this->builder = $builder;

        if (isset($this->args['filter'])) {
            foreach ($this->args['filter'] as $field => $value) {
                $method = Str::camel($field);
                if (method_exists($this, $method)) {
                    $this->$method($value); // call method
                }
            }
        }
    }

    // filter
    public function isPrimary(bool $val) :void
    {
        $this->builder->where('order_column', ($val ? '=' : '>'), 1);
    }
}

```
