### ISSUE TITLE
Handling error on a mutation

### ISSUE THREAD

**Issue by tquiroga** [rebing/graphql-laravel#570]
## Versions:
- graphql-laravel Version: 3.1
- Laravel Version: 5.8
- PHP Version: 7.1.3

### Question:

Great package, I think we miss a bit of documentation about error handling. I've looked into GraphQL-php and cannot find how to implement it. A good example would be this example https://github.com/rebing/graphql-laravel#adding-validation-to-a-mutation Here what would happen if that email was already used in the user's organisation (just so that we don't talk about using `rules`). 

How would you handle the error? I've tried using `GraphQL\Error\FormattedError` but the mutation is expecting a type `User` so it will give me a `Cannot return null for non-nullable field User.id.`

**Comment by mfn** [comment]
>  but the mutation is expecting a type `User` so it will give me a

What did you try, exactly?

"GraphQL Error handling" is based on exceptions, which means you don't return it from your mutation but simple "throw something".

And if you want to have more control on "that something you threw" how it should be actually returned in the GraphQL response, you a custom `error_formatter` in your `config/graphql.php`.

If OTOH you want to "return something else", like your mutation can _actually_ return the model **or** something, then you need to use design your type system to take that into account.

From your description it's unclear what you're looking for exactly.

**Comment by tquiroga** [comment]
> "GraphQL Error handling" is based on exceptions, which means you don't return it from your mutation but simple "throw something".

Just what I needed to know. Thanks
