### ISSUE TITLE
insert more than one record with a mutation

### ISSUE THREAD

**Issue by Danhebanjin** [rebing/graphql-laravel#571]
Is it possible to insert more than one record just by running a mutation?
 
Example:;

>
mutation{
  createBrand(
    [
     {description: "abc",state: 1},
     {description: "def",state: 1}
   ]
  )
}

**Comment by mfn** [comment]
Yes, you just have to define your **input type objects** accordingly, e.g. 
```php
'args' => [
  'brands' => [
    'type' => GraphQL::listOf(GraphQL::type('BrandType')),
  ]
]
```

In your resolver you pick your brands from the args and insert them:
```php
foreach ($args['brands'] as $brand) {
  Brand::create($brand);
}
```

(this is over-simplified pseudo-code, you should get the idea)
