### ISSUE TITLE
Custom Validation Message inside inputObject

### ISSUE THREAD

**Issue by samuelhgf** [rebing/graphql-laravel#584]
### Versions:
- graphql-laravel Version: 2.1
- Laravel Version: 5.8
- PHP Version: 7.2

### Question:
Hi, it is possible to create custom validation messages inside a inputObject? I tried to put the function inside the class, but did not work. Also inside the migration was used the default message for each rule inside the inputObject. I guess that is not implemented, so here is my suggestion

**Comment by mfn** [comment]
Please see the readme, specifically https://github.com/rebing/graphql-laravel#adding-validation-to-a-mutation: you can define `validationErrorMessages`
