### ISSUE TITLE
Users_pagination Pagination error

### ISSUE THREAD

**Issue by thachp** [rebing/graphql-laravel#59]
I followed an example at https://medium.com/skyshidigital/easy-build-api-using-laravel-and-graphql-67e2c5c5e150

I'm getting the following error, can you help pinpoint where the issue is?

<img width="1580" alt="screen shot 2017-10-31 at 2 01 37 pm" src="https://user-images.githubusercontent.com/1495371/32250464-db63f480-be49-11e7-8155-9f870beb1ba8.png">

**Comment by rebing** [comment]
It looks like you're returning a pagination object, which means that the query should be wrapped within `data` as follows:

```
query FetchUsers {
    data {
        id
        email
    }
}
```

**Comment by thachp** [comment]
@rebing  Thanks for your help.   I got it now, the issue was in my query.

```
query FetchUsers {
    users {
      total,
      per_page,
      current_page,
      from,
      to,
      data {
        id,
        email,
        first_name,
        last_name
      },
    }
}
```
