### ISSUE TITLE
Interfaces for Input Types

### ISSUE THREAD

**Issue by tpetry** [rebing/graphql-laravel#590]
### Summary
Sharing interface fields is a real nice and efficient way to reduce code boilerplate in types because you can reuse these long field definitions. But when you create InputTypes for e.g. a create and update definition you have to repeat these fields as the GraphQL specification did not specify interfaces for input types.

It would be nice adding an `Support\InputInterfaceType`implementation which would:
* Allow reusing interface fields in input field definitions (works currently)
* Will not be exported in the schema (happens, but is useless because its an OutputType)

So it will be an implementation detail which will be hidden from the graphql schema but nevertheless drastically improve the code quality.

**Comment by mfn** [comment]
PRs welcome!

**Comment by mfn** [comment]
I'm closing this as I don't see traction of someone to work on this and PRs / features are always welcome, no matter if they've an issue or not.
