### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by naufalscofield** [rebing/graphql-laravel#606]
Hi i new with lumen, i use lumen and i'm tryin to use graphql with lumen, i install the package with `composer require rebing/graphql-laravel` but i get error like this

![image](https://user-images.githubusercontent.com/38066867/76842384-c2ab8a00-686c-11ea-924e-8f77821d5f87.png)
![image](https://user-images.githubusercontent.com/38066867/76842405-cd661f00-686c-11ea-9ccf-35b174b14acf.png)

please your support

**Comment by mfn** [comment]
There is full release yet for L7 but we've tagged https://github.com/rebing/graphql-laravel/releases/tag/5.0.0-rc2 , which works.
`composer require rebing/graphql-laravel:5.0.0-rc2` should do it
