### ISSUE TITLE
Query to return Array 2D

### ISSUE THREAD

**Issue by albertcito** [rebing/graphql-laravel#609]
### Versions:
- graphql-laravel Version: 4.0.0
- Laravel Version: 6.0
- PHP Version: 7.3

### Question:
I have a matrix in the DB, And I would like to return a Array 2D type. But as far as I know, I just can return a simple array, but not an array 2x2. This is the  `Cell`  type

```graphql
type Cell {
  row: number,
  col: number,
}
```

I can return it as an array of Cell, but I don't know if is possible to return a Array 2D like this one: 

```javascript
[
    [{row:0, col: 0}, {row:0, col: 1}, {row:0, col: 2}],
    [{row:1, col: 0}, {row:1, col: 1}, {row:1, col: 2}]
]
```

**Comment by albertcito** [comment]
Looks like GraphQL doesn't support it: https://github.com/graphql/graphql-spec/issues/423

**Comment by mfn** [comment]
Yes, this is one of the limitations. To emulate tuples you would need a separate type and give the fields names.

The other limitations is that you can't project a hash (in PHP: array with dynamic keys) either.
