### ISSUE TITLE
Timestamps return null

### ISSUE THREAD

**Issue by DiederikvandenB** [rebing/graphql-laravel#61]
I would like to return the `created_at` and `updated_at` timestamps of a model entry. In my GraphQL Type I have added the following fields:

``` php
[
    'created_at' => [
        'type' => Type::string(),
    ],

    'updated_at' => [
        'type' => Type::string(),
    ],
]
```

If I query those, I receive `null`. If I add custom resolve functions like this, it all works perfectly:

``` php
public function resolveCreatedAtField($root)
{
    return (string) $root->created_at;
}
```

Note the prefix `(string)` type, which is required.

Naturally I can add those two functions for every type I create, but this seems rather cumbersome. Is there something I am missing here, or is this a bug of some sorts?

**Comment by rebing** [comment]
I assume your `created_at` field is a Carbon object and is thus not properly resolved to string. I usually resort to _resolving_  all date and timestamp fields.

**Comment by DiederikvandenB** [comment]
Thank you for your response. Yes, I am indeed using Carbon. Good to know that I am not doing anything wrong.

Given the fact that many people will use Carbon as it is so integrated in Laravel I would suggest adding it to the readme. Other than that, thanks for your efforts!
