### ISSUE TITLE
Need support for Laravel 7.x 

### ISSUE THREAD

**Issue by zinnah1995** [rebing/graphql-laravel#610]

**Comment by mfn** [comment]
Duplicate of https://github.com/rebing/graphql-laravel/issues/600

Please use https://github.com/rebing/graphql-laravel/releases/tag/5.0.0-rc2 for now

**Comment by mfn** [comment]
https://github.com/rebing/graphql-laravel/releases/tag/5.0.0 has been released with L7 support!
