### ISSUE TITLE
Is there a way to have dynamic GraphQL support Type?

### ISSUE THREAD

**Issue by albertcito** [rebing/graphql-laravel#618]
### Versions:
- graphql-laravel Version: 4.0.0
- Laravel Version: 6.0.0
- PHP Version: 7.4
### Question:

Every time that I create a `Rebing\GraphQL\Support\Type` I have to add it to the `graphql.php`  config file. There are some way to do it dynamically without to add it to the `graphql` config file. I mean something like that:

```php
class UserQuery extends Query
{

    protected $attributes = [
        'name'        => 'UserQuery',
        'description' => 'A query to return a user',
    ];

    public function type(): Type
    {
        return new DynamicUsersType();
    }
  
    public function resolve($root, $args)
    {
        return User::all();
    }

}
```

I review the question [108](https://github.com/rebing/graphql-laravel/issues/108), but my idea is to do it like the `GraphQL\Type\Definition\InputObjectType`. This kind of Object Type don't requited to be registered in the `graphql` config file.

**Comment by mfn** [comment]
> This kind of Object Type don't requited to be registered in the `graphql` config file.

But it currently has to be, no? I'm not quite following you here.

> Every time that I create a `Rebing\GraphQL\Support\Type` I have to add it to the `graphql.php` config file

They have to be registered somehow (to the best of my knowledge).

I've expressed _something similar_ in https://github.com/rebing/graphql-laravel/pull/594#issuecomment-599187444 :
> I mean this could bet yet-another-things to consider: the GraphQL library suggests default paths/namespaces (app/GraphQL/…) so we would someone have to list all the types and mutations manually? Why wouldn't there be a mechanism which, like the console commands, can recursively load them all (if desired).
> 
> Certainly in my projects that would be welcome, my biggest has over 200 of such registered classes, all manually placed.

Types can be registered as different names but in the general use case, typed are registers with their name so automatic registered (walking the known directories, like Laravel does it itself with auto-registered all the commands).

Is this the direction you mean?

**Comment by albertcito** [comment]
Yes, that was the question. 

The [repository guide say](https://github.com/rebing/graphql-laravel#creating-a-query): If I want to create a query I need to create a  **_create a type_** and **_Add the type to the config/graphql.php configuration file_** or with the **_with the GraphQL Facade_**.

I would like to know if there are some way to avoid to add it. My idea is just to create a class without add it to the config or through Facade But looks that there are no way to do it. 

I did it with the [InputObjectType](https://webonyx.github.io/graphql-php/type-system/input-types/#input-object-type) (It's not in the graphql-laravel guide)  and I would like to do the same with the Type but looks that there are no way to do it.

**Comment by mfn** [comment]
No, currently not.

How did you do it with the InputObjectType? 😄

**Comment by albertcito** [comment]
In this way:

```php
class TagInput extends GraphQL\Type\Definition\InputObjectType
{
    public function __construct(string $typeName)
    {
        $fields = [
            'tag_id' => [
                'type' => Type::int(),
                'description' => 'Tag primary key',
                'rules' => [ 'exists:pgsql.generic.tag,tag_id'],
            ],
            'tag'   => [
                'type'  => Type::string(),
                'rules' => ['min:1'],
            ],
        ];

        parent::__construct([
            'name' => $typeName,
            'fields' => $fields,
        ]);
    }
}

```


And you can use it in any arg like: 

```php
public function args(): array
{
        return [
            'tags'   => [
                'type'  => Type::listOf(
                    new TagInput('imageTagsUpdate')
                ),
                'rules' => [
                    'required',
                    'array',
                    'min:1',
                ],
            ],
       ]
}

```

The required is that the `$typeName` must be unique in each query or mutation args.  It's useful if you need to customize nested input objects, when sometimes some values must be present or not.

**Comment by albertcito** [comment]
I was able to do it, with the [object-types](https://webonyx.github.io/graphql-php/type-system/object-types/)  


Solved ! I'm going to test it now.

**Comment by illambo** [comment]
Hi, usually I do something like this (see below) but maybe there are a better way, infact
in this scenario you "lose" the possible benefits of use _Rebing\GraphQL\Support\InputType_.
Suggestions ?

```
use GraphQL\Type\Definition\EnumType;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Facades\GraphQL;
use Rebing\GraphQL\Support\Query;

class ScheduledTasksQuery extends Query
{
    /**
     * @var array
     */
    protected $attributes = [
        'name' => 'scheduledTasks',
        'description' => 'A scheduled tasks query'
    ];

    /**
     * @return Type
     */
    public function type(): Type
    {
        return GraphQL::paginate('ScheduledTask');
    }

    /**
     * @return array
     */
    public function args(): array
    {
        return [
            'cursor' => [
                'name' => 'cursor',
                'type' => Type::nonNull(GraphQL::type('PaginationCursorInput'))
            ],
            'filter' => [
                'name' => 'filter',
                'type' => new InputObjectType([
                    'name' => 'ScheduledTasksFilterInput',
                    'fields' => function() {
                        return [
                            'search' => [
                                'name' => 'search',
                                'type' => Type::string(),
                            ],
                            'with_trashed' => [
                                'name' => 'with_trashed',
                                'type' => Type::boolean(),
                            ],
                        ];
                    },
                ]),
            ],
            'sort' => [
                'name' => 'sort',
                'type' => Type::listOf(new EnumType([
                    'name' => 'ScheduledTasksSort',
                    'description' => '',
                    'values' => [
                        'CREATED_AT_ASC' => 'CREATED_AT_ASC',
                        'CREATED_AT_DESC' => 'CREATED_AT_DESC',
                    ],
                ])),
            ],
        ];
    }

   // ..

}
```
