### ISSUE TITLE
->select() method return empty array with hasMany relationship

### ISSUE THREAD

**Issue by thachp** [rebing/graphql-laravel#62]
There appear to be an issue with the  ->select() method when used in Query type.
I have a User model having hasMany(Example::class) relationship.

This return empty examples array.
```
User::with(array_keys($fields->getRelations()))
            ->where($where)
            ->select($fields->getSelect())
            ->paginate();
```

But removing ->select($fields->getSelect()) return my entire examples array.

```
User::with(array_keys($fields->getRelations()))
            ->where($where)
            ->paginate();
```

The issue could be related to the Laravel :with() method, because adding specific columns in :with() also yield the same bug.

```
Route::get('/', function () {

    // examples return full array list.
    return App\User::with("examples")->where("id", 5)->first();

    // examples return empty array
    return App\User::with("examples:id,name")->where("id", 5)->first();

});

```

Platform
```
MacOS
Valet
Laravel Framework 5.5.19
rebing/graphql-laravel ~1.7
```

**Comment by rebing** [comment]
Try adding `user_id` (or whichever field references `user`) to the select. i.e:
```
user {
    id,
    examples {
        id,
        user_id,
        name
    }
}
```

**Comment by thachp** [comment]
Thank you! It works.
