### ISSUE TITLE
convert the mutation inputs to a data transfer object

### ISSUE THREAD

**Issue by crissi** [rebing/graphql-laravel#620]
I think it would be cool to able to receive the inputs to a mutation/query as a data transfer object  (https://github.com/spatie/data-transfer-object) instead of an array,  to make it even more safe to work with.

Not sure how to do this right now.

but maybe automatically get the args as data transfer object if the data transfer object is typed in the resolve-method

And then implement an artisan command to generate DataTransferObjects from a mutation

**Comment by mfn** [comment]
Intriguing idea!

I personally I _do love_ especially that library. It has such a simple _philosophy_.

> Not sure how to do this right now.

No idea either 🤷‍♀️
