### ISSUE TITLE
Privacy is not work 

### ISSUE THREAD

**Issue by dongkaipo** [rebing/graphql-laravel#626]
### Versions:
- graphql-laravel Version: 5.0
- Laravel Version: 7.0
- PHP Version: 7.3

### Question:
```
public function fields(): array
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::id()),
                'description' => 'id'
            ],
            'nickname' => [
                'type' => Type::nonNull(Type::string()),
                'description' => 'nickname'
            ],
            'telephone' => [
                'type' => Type::string(),
                'description' => 'telephone',
            ],
            'username' => [
                'type' => Type::string(),
                'description' => 'username'
            ],
            'email' => [
                'type' => Type::string(),
                'description' => 'email',
                'resolve' => function ($root) {
                    return Str::lower($root->email);
                },
                'privacy' => function () {
                    return false;
                }
            ],
];
}
```
The `privacy` is not work whatever the function return `true` or `false`. Where did i go wrong?

**Comment by dongkaipo** [comment]
![image](https://user-images.githubusercontent.com/1720338/80064550-e7310b00-856a-11ea-9eff-e631827abe64.png)
This is the request

**Comment by dongkaipo** [comment]
![image](https://user-images.githubusercontent.com/1720338/80067817-23676a00-8571-11ea-89ca-5f9812db2cd0.png)
This relation query is not working, it is seem `query` not be called.

**Comment by mfn** [comment]
I think you're not using `SelectFields`, which is required to make all this magic work. Can you show your resolver?

Check the readme, lots of SelectFields examples

**Comment by dongkaipo** [comment]
@mfn thank you very much, i got it.
It work fine now, thank you.
```
$fields = $getSelectFields();
        $select = $fields->getSelect();
        $with = $fields->getRelations();

        $builder = User::select($select)->with($with);
```
Those code must be write to `UserQuery.php@resolve'
