### ISSUE TITLE
Union type

### ISSUE THREAD

**Issue by DiederikvandenB** [rebing/graphql-laravel#63]
Another question. I was trying to build a search query that goes through multiple models. I was looking at this GraphQL Type: https://github.com/webonyx/graphql-php/blob/master/docs/type-system/unions.md

Is it possible to implement this using this package?

Basically, this is what I want to achieve:
https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d

Cheers!

**Comment by rebing** [comment]
I haven't worked with UnionTypes, but it _should_ already work, since this package is built on top of the webonyx package that you linked. Have you tried creating a UnionType and adding it as a field?

**Comment by DiederikvandenB** [comment]
Thank you for your response. I have tried the following:
https://gist.github.com/DiederikvandenB/1beee6e88d3671e72f2c639f17d10664

Note that I only register the `SearchQuery` in the `config/graphql.php`.

Attached to the gist is also the error message. What am I doing wrong?

Cheers!

**Comment by DiederikvandenB** [comment]
Months later I am revisiting this issue. Any points you could give me?

**Comment by jbbr** [comment]
@DiederikvandenB you can try my PR #91 
I added basic support for Unions to the Rebing Type class. It does work despite the WIP flag.

**Comment by jbbr** [comment]
Another hint @DiederikvandenB : I think you can't add raw webonyx types to the Facade/graphql config.
But you can indeed reference instances of your custom type in other types and queries or even defined inline.
e.g:

```php
'fields' => [
  'fieldOther' => [ 'type' => GraphQL::type('SomeRebingType')],
  'fieldUnion' => ['type' => new UnionType([ 'types' => [...]],
]
```

**Comment by jbbr** [comment]
@DiederikvandenB You can try the latest Version release 1.12.0, the PR has been merged.
There is also some documentation on https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#unions
