### ISSUE TITLE
error run application

### ISSUE THREAD

**Issue by coretmapp** [rebing/graphql-laravel#633]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException 

  Invalid argument supplied for foreach()

  at vendor/rebing/graphql-laravel/src/GraphQLServiceProvider.php:89
    85|      */
    86|     protected function bootSchemas(GraphQL $graphQL): void
    87|     {
    88|         $configSchemas = config('graphql.schemas');
  > 89|         foreach ($configSchemas as $name => $schema) {
    90|             $graphQL->addSchema($name, $schema);
    91|         }
    92|     }
    93|

      +11 vendor frames 
  12  app/Providers/AppServiceProvider.php:26
      Illuminate\Support\Facades\Facade::__callStatic()

      +8 vendor frames 
  21  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by mfn** [comment]
Can you please fill out the issue template fully, see https://github.com/rebing/graphql-laravel/issues/new?labels=bug&template=1_Bug_report.md

In case you haven't, can you please try the latest version? Did you follow the installation instructions?

**Comment by mfn** [comment]
Closing due to lack of details and feedback
