### ISSUE TITLE
Create a new type of exception which not reporting

### ISSUE THREAD

**Issue by vodrems** [rebing/graphql-laravel#636]
At the moment there are only two exceptions which won't be reported - **ValidationError** and **AuthorizationError**.

For ValidationError needs pass validator (it isn't always possible).

AuthorizationError - very fit for Auth exceptions, but not understandable for other errors (which should show error message as a response but should not be reported to logging system).

I suggest creating a new exception which shows error message but won't be reported to a logging system and will be universal in different cases.

rebing/graphql-laravel/src/GraphQL.php:376

```php
/**
     * @param  Error[]  $errors
     * @param  callable  $formatter
     * @return Error[]
     */
    public static function handleErrors(array $errors, callable $formatter): array
    {
        $handler = app()->make(ExceptionHandler::class);
        foreach ($errors as $error) {
            // Try to unwrap exception
            $error = $error->getPrevious() ?: $error;
            // Don't report certain GraphQL errors
            if ($error instanceof ValidationError
                || $error instanceof AuthorizationError
                || ! ($error instanceof Exception)) {
                continue;
            }
            $handler->report($error);
        }

        return array_map($formatter, $errors);
    }
`

**Comment by mfn** [comment]
From your description it's unclear:
- what kind of exception
- **who** should throw it

Also, not sure, the code you pasted feels to me differs more than just your suggestion, as the current one looks like this:
```php
    public static function handleErrors(array $errors, callable $formatter): array
    {
        $handler = app()->make(ExceptionHandler::class);
        foreach ($errors as $error) {
            // Try to unwrap exception
            $error = $error->getPrevious() ?: $error;

            // Don't report certain GraphQL errors
            if ($error instanceof ValidationError
                || $error instanceof AuthorizationError
                || ! (
                    $error instanceof Exception
                    || $error instanceof PhpError
                )) {
                continue;
            }

            if (! $error instanceof Exception) {
                $error = new \Exception(
                    $error->getMessage(),
                    $error->getCode(),
                    $error
                );
            }

            $handler->report($error);
        }

        return array_map($formatter, $errors);
    }
```
----

IMHO there needs to be clear goals / winning arguments changing `\Rebing\GraphQL\GraphQL::handleErrors`

However, did you know that you can customize it?

This is the `error_handler` as specified in your config:
```php
    /*
     * Custom Error Handling
     *
     * Expected handler signature is: function (array $errors, callable $formatter): array
     *
     * The default handler will pass exceptions to laravel Error Handling mechanism
     */
    'errors_handler' => ['\Rebing\GraphQL\GraphQL', 'handleErrors'],
```
The very goal is to customize it for application specific use cases!

**Comment by fsmonter** [comment]
@mfn I came by searching for this same issue. Sometimes I need to throw an `Error` message for the user, which could be a `ValidationError` but without a `Validator` instance. 

A use case could be when caching some application exceptions like this example:

```php
try{
  ...
} catch (PaymentFailedException $e) {
   throw new \GraphQL\Error\Error($e->getMessage());
} catch (NotEnoughTicketsException $e) {
   throw new \GraphQL\Error\Error('Not enough tickets');
}
```

Using the current `GraphQL\Error\Error` gets reported and a `ValidationError` is not usable since there's no `Validator` instance. 

In this case, what should be the approach? do you recommend a custom handler?

**Comment by mfn** [comment]
> do you recommend a custom handler?

Given:
> Sometimes **I need to throw** an 

I'd say, yes.

The default handler handles the cases covered in this library, not your application. You can override the handler for this very reason. Or call it from your code etc.

From all the feedback I could gather here, this is the recommended way; I'm therefore closing this request for enhancement at this point.

**Comment by vodrems** [comment]
@mfn Yes, I know about the custom handler. But if someone adds bear exception it will save much time 😄
