### ISSUE TITLE
Query function does not get it's own fields parameters

### ISSUE THREAD

**Issue by pushchris** [rebing/graphql-laravel#64]
I'm not sure if this is an issue or by design but I feel like the functionality should be slightly different. If you override the query for a relation field, the arguments that get passed are the parents, not that subqueries arguments.

Let's say I have the following GraphQL query:

```graphql
query {
    student(id: 10) {
        firstName
        lastName
        classes(week: "2017-10-07") {
            title
        }
    }
}
```

And have the following corresponding fields:

```php
//...
public function fields()
{
    return [
        // ...
        'classes' => [
            'type' => GraphQL::type('class'),
            'args' => [
                'week' => [
                    'type' => Type::string(),
                    'name' => 'week'
                ]
            ],
            'query' => function(array $args, $query) {
              // $args are the arguments for `student` not for `class`
            }
        ]
    ];
}
```

The arguments that are passed to the query are those for ```student```, not those for ```classes```.

However if instead I use a custom resolver like so:
```php
//...
public function fields()
{
    return [
        // ...
        'classes' => [
            'type' => GraphQL::type('class'),
            'args' => [
                'week' => [
                    'type' => Type::string(),
                    'name' => 'week'
                ]
            ],
            'resolve' => function ($root, $args) {
              // $args now pass in `week` correctly
            }
        ]
    ];
}
```

Then the ```$args``` variable correctly contains ```week```. Is there a reason why the two sets of arguments differ? I feel like if anything they should both contain both so that a resolver can get its parents arguments and its own. In my particular case the use case I want is to be able to add constraints to the relation for a date range based on the arguments passed in to ```classes```. Using the query builder is more efficient than having to use the resolver.

**Comment by rebing** [comment]
I have never used the arguments this way, so I didn't know to think about it. I think the query arguments are the ones that should be reworked. 

You can take a look at rows 80-84 in Field class: https://github.com/rebing/graphql-laravel/blob/master/src/Rebing/GraphQL/Support/Field.php

`$arguments[1]` and `$arguments[2]` should probably be merged, but I don't currently have time to look into it. You can create a PR, if you figure out the solution.

**Comment by ddeath** [comment]
@pushchris how did you get `query` key working? If I specify it in my type file, the callback is never called. Thank you

**Comment by pushchris** [comment]
@ddeath didn't have any issues getting the key to work, you just have to make sure there isn't also a resolve field. If you are asking about the arguments though I was never able to get that working, I believe its a shortcoming of how things are called in the underlying GraphQL implementation
