### ISSUE TITLE
[LUMEN] ErrorException on declaring class alias

### ISSUE THREAD

**Issue by LuizVisnadi** [rebing/graphql-laravel#640]
Hello,

Currently i'm having a small issue with this package under Lumen. When i launch my unit tests (with phpunit), the class GraphQLLumenServiceProvider throws a ErrorException because it tries to assign an alias to 'Illuminate\Routing\Controller' but it already exists.

https://github.com/rebing/graphql-laravel/blob/1606e9a8fa751f449d818a39fd74182c5cb669f5/src/GraphQLLumenServiceProvider.php#L23-25

When adding `&& !class_exists('Illuminate\Routing\Controller')` on the condition line 23. It seems to correct the issue.

**Comment by mfn** [comment]
Fixed via https://github.com/rebing/graphql-laravel/pull/508
