### ISSUE TITLE
field __typename is not available if I use $resolveInfo

### ISSUE THREAD

**Issue by apapilov-sc** [rebing/graphql-laravel#642]
Let's say we have this schema
```
{
	getCompanysInfo(id:234) {
		name
		location
                __typename
		emplyees {
			cars
			computers
                     __typename
		}
	}
}
```
if I use the code below in getCompanysInfo::resove(), then I can't query __typename field on employee. While ReactJs libraries which generates requests always adds "__typename" fields to any query.

```
$queryPlan = $resolveInfo
            ->lookAhead()
            ->queryPlan();
```

**Comment by mfn** [comment]
`ResolveInfo` is purely from the https://github.com/webonyx/graphql-php/ library, so you've to look there.

Try calling `getFieldSelection` for a start, I'm pretty sure you will get this field back.
