### ISSUE TITLE
Is there any way to tag request in Telescope?

### ISSUE THREAD

**Issue by hemratna** [rebing/graphql-laravel#649]
### Versions:
- graphql-laravel Version: ^5.0
- Laravel Version: 7.0
- PHP Version: 7.3

### Question:
Is there any way to tag request in Telescope?
The telescope provides a feature to assign [custom tag](https://laravel.com/docs/7.x/telescope#tagging) any request.
Currently in the telescope dashboard shows all the GraphQL query as `/graphql`. 
It is really hard to debug a particular query.

**Comment by mfn** [comment]
I don't use telescope so can't help much 🤷‍♀️

**Comment by illambo** [comment]
I use this:

```
Telescope::tag(function (IncomingEntry $entry) {
            if (($entry->type === EntryType::REQUEST) && (null !== ($operationName = request()->input('operationName')))) {
                return ['GraphQL:'.$operationName];
            }
            if (($entry->type === EntryType::REQUEST) && (null !== ($operationName = request()->header('x-apollo-operation-name')))) {
                return ['GraphQL:'.$operationName];
            }
            return [];
        });
```

**Comment by hemratna** [comment]
Thanks a lot, @illambo For code snippet.
I will try this way 🙂
