### ISSUE TITLE
alias function

### ISSUE THREAD

**Issue by crissi** [rebing/graphql-laravel#65]
```
    class CaseType extends GraphQLType {
        
        protected $attributes = [
            'name'          => 'Case',
            'description'   => 'A Case',
            'model'         => Order::class,
        ];

        public function fields()
        {
            return [
                'id' => [
                    'type' => Type::nonNull(Type::int()),
                    'description' => 'The id of the user',
                ],
                'case_number' => [
                    'type' => Type::nonNull(Type::string()),
                    'description' => 'An unique identifier for the case',
                    'alias' => 'number'
                ],
                'caseType' => [
                    'type'          => GraphQL::type('caseType'),
                    'description'   => 'type of case',
                    'alias' => 'type'
                ]
            ];
        }
    }
```

I would like to implement a alias function.

The output will send the alias instead of the key.

The input will receive the alias and convert it to the correct key value, so the queries will work correctly

Would you be interested in merging a pullrequest with that functionality?

**Comment by rebing** [comment]
What about using the `'name'` attribute instead?

**Comment by crissi** [comment]
![image](https://user-images.githubusercontent.com/3076578/34255565-99e1c28c-e651-11e7-81be-bb0d1d86347b.png)

I was looking at what your library is build on and it was using name and key interchangeable: http://webonyx.github.io/graphql-php/type-system/input-types/

But makes sense to use that instead, since we already have the the key for the internal name.
