### ISSUE TITLE
What is suggested approach to implement filters for Query?

### ISSUE THREAD

**Issue by hemratna** [rebing/graphql-laravel#650]
### Versions:
- graphql-laravel Version: ^5.0
- Laravel Version: 7.0
- PHP Version: 7.3

### Question:
Why learning the GraphQL with Laravel, I would like to implement filers as https://rickandmortyapi.com/graphql/ example schema

![image](https://user-images.githubusercontent.com/1333346/86357913-380c6080-bc8c-11ea-934d-f150dd2a4391.png)

I try to create a `FilterCharacter` as a `type` but it's not working (The GraphQL schema is not generating.) 
  
Is there any demo/open-source schema generate with this package that I can take a reference. 

Thanks a lot for the great package. 🙏

**Comment by illambo** [comment]
Have you tried with [input type object](https://github.com/rebing/graphql-laravel#input-object) ?

**Comment by mfn** [comment]
Yes, this concept is the InputObject which equally supported :)

I'm closing this as I feel the question is asked, but shouldn't stop from further questions/discussions!
