### ISSUE TITLE
Custom paginator class is not working

### ISSUE THREAD

**Issue by bjgajjar** [rebing/graphql-laravel#662]
### Versions:
- graphql-laravel Version: ^5.0
- Laravel Version: ^7.0
- PHP Version: ^7.2.5

### Description:

Custom paginator class is throwing the below error when executing the `GraphQL query`. 

```
Call to undefined method GraphQL\\Type\\Definition\\ObjectType::getWrappedType()
```

**Comment by mfn** [comment]
Can you please provide some code and a full stacktrace?

**Comment by bjgajjar** [comment]
Hey @mfn 

Thank you so much for your feedback. The issue was at my end only. 

Apologize for the inconvenience.

**Comment by mfn** [comment]
Sure np, would be great of you if you could share, for others to learn
