### ISSUE TITLE
Consider laragraph/laravel-graphql-utils

### ISSUE THREAD

**Issue by spawnia** [rebing/graphql-laravel#663]
I just finished up the first component, a rock solid request parser. It should be quite suitable for inclusion in this library.

https://github.com/laragraph/laravel-graphql-utils/blob/master/src/RequestParser.php

Its inclusion within Lighthouse went pretty well and allowed to remove a whole bunch of code: https://github.com/nuwave/lighthouse/pull/1424

I will release a stable version soon, but would like to gather some feedback before that. My plan for the project is to function as a library with solid building blocks, on top of which the more framework-esque integrations can be built.

**Comment by mfn** [comment]
I just landed it in master for the next major semver rel due to breaking changes this required; thanks @spawnia for this, really nice.

(still which `\Nuwave\Lighthouse\Support\Utils::applyEach` would be there too, but copypaste to `\Rebing\GraphQL\Helpers::applyEach` does it for now)

**Comment by spawnia** [comment]
Sweet! I will definitely consider moving over more functionality from Lighthouse there in the future 👍

**Comment by illambo** [comment]
Excellent cooperation, very good!
