### ISSUE TITLE
Unable to set query name with name attribute

### ISSUE THREAD

**Issue by ctadlock** [rebing/graphql-laravel#666]
### Versions:
- graphql-laravel Version: 5.1.2
- Laravel Version: 7.22.4
- PHP Version: 7.3

### Description:

The logic for determining the query name is only using the class name, it is not looking at the `name` attribute.

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/1539397/90722204-3f54f100-e26f-11ea-84cf-cb1b19e1aed6.png)

![image](https://user-images.githubusercontent.com/1539397/90722167-28160380-e26f-11ea-8943-dcf6aa6da9d6.png)

![image](https://user-images.githubusercontent.com/1539397/90722491-c0ac8380-e26f-11ea-890b-a8d353f6156b.png)

**Comment by ctadlock** [comment]
I think this is the fix. Not sure I understand all the logic here as Im new to this package, so didn't submit a PR.

```
protected function buildObjectTypeFromFields(array $fields, array $opts = []): ObjectType
{
    $typeFields = [];
    foreach ($fields as $name => $field) {
        if (is_string($field)) {
            $field = $this->app->make($field);
            $fieldName = $field->name;
            $name = is_numeric($name) || isset($fieldName) ? $fieldName : $name;
            $field->name = $name;
            $field = $field->toArray();
        } else {
            $name = is_numeric($name) ? $field['name'] : $name;
            $field['name'] = $name;
        }
        $typeFields[$name] = $field;
    }

    return new ObjectType(array_merge([
        'fields' => $typeFields,
    ], $opts));
}
```

**Comment by mfn** [comment]
> Unable to set query name with name attribute

This definitely works for me, I just tested it in a project of mine.

I see you `extend` another class `ProjectListQuery`, does this class maybe interfere somehow?

How are you "registering" the query in `config/graphql.php`?

**Comment by ctadlock** [comment]
OMG.. I didn't realize I had overridden the names in the config file. I switched the types over to just the class name, but forgot the queries. Not a bug; user error.

Thanks for the help.

![image](https://user-images.githubusercontent.com/1539397/90831374-67d4fd80-e2f8-11ea-9a75-1cde17a840a0.png)
