### ISSUE TITLE
Error while processing image 

### ISSUE THREAD

**Issue by mikev032** [rebing/graphql-laravel#669]
### Versions:
- graphql-laravel Version: dev-master
- PHP Version: 7.3.9

### Question:
Whenever I am trying to upload a file, I am getting this error:
`{
    "errors": [
        {
            "message": "Syntax Error: Expected Name, found <EOF>",
            "extensions": {
                "category": "graphql"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 71
                }
            ]
        }
    ]
}`

This is my query sending too GraphQL:

![afbeelding](https://user-images.githubusercontent.com/57143826/91703492-8fd72300-eb7a-11ea-8064-c1ca2a69bbe3.png)

`{"query":"mutation ($file: Upload!){ uploadMutation( file: $file ){ id }","variables": { "file": null }}`

**Comment by mfn** [comment]
> Syntax Error: Expected Name,

At first this looks like a "json decoding" error, is this possible? It's the only exception message I know which return this sparse "Syntax Error:" prefix 😄 

Please double check the payload you actually send is correct, the `locations` are decode in \Rebing\GraphQL\GraphQLUploadMiddleware::parseUploadedFiles , I would start debugging there

**Comment by mikev032** [comment]
The location is filled and the var is replaced with the attached file if I dump the request at the end of `parseUploadedFiles` function

Dump of the locations:
`array:1 [
  0 => "variables.file"
]`
