### ISSUE TITLE
Another language of mistakes

### ISSUE THREAD

**Issue by shevtsov-max** [rebing/graphql-laravel#677]
- graphql-laravel Version: 5.1.2
- Laravel Version:  7.26
- Lumen Version: -
- PHP Version: 7.3

### Question:
Hey. There is a task to translate system validation errors into another language. For example in the file "GraphQL\Validator\RulesValuesOfCorrectType" the method "badArgumentValueMessage". How can you solve this?

**Comment by mfn** [comment]
Not sure I understand.

Is your goal to provide a different message (i.e. translation?) when e.g. `\GraphQL\Validator\Rules\ValuesOfCorrectType::badArgumentValueMessage` is triggered?

**Comment by shevtsov-max** [comment]
Yes. For example in file ValuesOfCorrectType line 262.

**Comment by mfn** [comment]
No, it's currently not possible.

Also, this is actually a problem of the underlying GraphQL library we use, it's not code from this library. And there it's currently not supported. If it gets supported there, we might revisit this topic if any changes are needed for this library.

I suggest you contribute to any of these:
- https://github.com/webonyx/graphql-php/pull/713
- https://github.com/webonyx/graphql-php/pull/718
