### ISSUE TITLE
‌Passport auth: api not working in graphql

### ISSUE THREAD

**Issue by a-bahrami** [rebing/graphql-laravel#679]
### Versions:
- graphql-laravel Version : ~6.0
- Laravel Version: 7.^ 
- PHP Version: 7.4

### Description:

Hello friends .
I have a project , back-end with Laravel and graphql is used and the problem is that when I give the middleware api to graphql, it does not work, in the front-end side must be sent api-token to record or download information using mutation or query and This is how I activated middleware, but it still gives me information without giving it a token, and this is a problem. I wanted to know where the problem comes from?
I tested the front-end side and also tested the backend, I thought it was a problem with laravel-passport, I reinstalled it, but the same thing happened again.

**Comment by mfn** [comment]
> graphql-laravel Version : ~6.0

There is no 6.x release yet: which one are you exactly using? `composer show rebing/graphql-laravel | grep versions` might be enough`

Personally not using Passport so can't help.

I'm also reclassifying this as a support question unless we know we've specific bug somewhere, thanks!

**Comment by mfn** [comment]
Closing due to lack of feedback
