### ISSUE TITLE
Dynamic rules

### ISSUE THREAD

**Issue by mihkelallorg** [rebing/graphql-laravel#68]
Hey!

I couldn't find any documentation on dynamic rules. For example when as an argument I'm accepting a field as an array, I'd perhaps like to apply rules for the whole array. For that I would need to access `$args` in the `rules` method. Is there a way to do this now already or would it be something new?

Thanks for an awesome package boi.

**Comment by rebing** [comment]
I actually wanted to do this as well like a week ago, but didn't find a quick solution. I didn't spend much time on it, but it's probably fairly easy to change `Rebing\GraphQL\Support\Field@getResolver` to inject the arguments to `getRules`.

You can do a PR, if you figure it out

**Comment by rebing** [comment]
#70
