### ISSUE TITLE
Compress to gzip

### ISSUE THREAD

**Issue by shevtsov-max** [rebing/graphql-laravel#681]
### Versions:
- graphql-laravel Version: 5.1.2
- Laravel Version: 7
- PHP Version: 7.3

### Question:

Hello. There is a task to compress a large response into gzip. Can you give advice on how to solve this problem?

**Comment by mfn** [comment]
Can you set your web server to transparently do this?

**Comment by shevtsov-max** [comment]
Didn't quite understand your question. What does "transparent" mean?

I want to implement something like this scheme of work.
https://medium.com/dev-cafe/how-to-compress-the-large-api-responses-in-php-lumen-using-gzip-5df8aa0a9689

**Comment by mfn** [comment]
Seems this is best handled in the middleware group for your GraphQL request?

**Comment by shevtsov-max** [comment]
Are you talking about a proxy server? But this is not necessary. For simple projects, you can solve the problem within 1 server. The article describes the option as I see it approximately. I do not understand how convenient and correct it is to describe it using your library.

**Comment by mfn** [comment]
No, I'm talking about either compressing automagically in your webserver before sending to the client or adding a dedicated Laravel/Lumen middleware

**Comment by shevtsov-max** [comment]
Thank you, I will think.
