### ISSUE TITLE
Best way to automatically authorize on specific Types?

### ISSUE THREAD

**Issue by ChrGriffin** [rebing/graphql-laravel#684]
### Versions:
- graphql-laravel Version: 5.1.4
- Laravel Version: 7.20.0
- PHP Version: 7.4.3

### Question:

I'm struggling to come up with the _best_ way to approach a particular problem. The framework gives me plenty of options, which is sort of the problem ;) There's a lot of ways to approach this but they all have drawbacks.

Imagine a query like this:

```
query FetchProducts {
    products {
        id
        name
        orders {
            id
            user {
                 id
            }
        }
    }
}
```

As you can see, we have a product, which can have associated orders, and each order has a user.

_If_ the user making the query is the user who owns the product, then 'orders' should be populated with every order placed for their product. However, if the user making the query is a user who ordered the the product, then 'orders' should be populated only with _their_ order. If neither case applies, then 'orders' should be null.

My first instinct was to use the `privacy` callback on the relationship on the SongType class. However, I'm encountering issues with this callback as it seems in order to access the user ID of the order or the song inside the privacy callback, I need to add them as arguments to the query, which I don't want to do. Not only does the frontend making the query not KNOW the IDs of the orders its trying to retrieve, this should happen automatically.

I'm thinking now that the best way to handle this is within Laravel itself with a Global Eloquent scope, but I wanted to reach out and see if I was missing something obvious or approaching this is entirely the wrong way.

Thanks!

**Comment by crissi** [comment]
If I understand correctly, you should be able to use the query property: https://github.com/rebing/graphql-laravel#type-relationship-query

**Comment by mfn** [comment]
Closing as I agree with @crissi , when using `SelectFields` this should be doable to modify the query appropriately before it's being executed.
