### ISSUE TITLE
Sentry transaction name

### ISSUE THREAD

**Issue by illambo** [rebing/graphql-laravel#690]
### Versions:
- graphql-laravel Version: 5.1.4
- Laravel Version: 8.14.0
- PHP Version: 7.4.12

### Sentry:
- sentry/sentry: 3.0.4
- sentry/sentry-laravel: 2.2.0

### Question:
Like similar questions for Newrelic #670 and Telescope #649 I am looking for a little help to configure (rename) the transaction name for [Sentry](https://sentry.io).

I think it is useful for performance tracking tool.

I can tag the request but I haven't found a way to rename it yet.

```php
\Sentry\Laravel\Integration::configureScope(function (\Sentry\State\Scope $scope): void {
    //$scope->setExtra('character.name', 'Mighty Fighter');
    //$scope->setTag('example-tag', 'pippo');
});
```

I try with this, but maybe Sentry terminate middleware override the transaction name:
```php
\Sentry\configureScope(function (Scope $scope): void {
    $scope->getTransaction()->setName('Pippo');
});
```

I also tried with [before_send](https://docs.sentry.io/platforms/php/guides/laravel/configuration/options/#hooks) hook but it appears not to be triggered.

Do you have any suggestions for me?
Thanks!

**Comment by illambo** [comment]
I try to address request to getsentry/sentry-laravel#415 too.

**Comment by illambo** [comment]
My mistake, _before_send_ hook it works (see getsentry/sentry-laravel#415).

**Comment by aakarim** [comment]
Hi - since the removal of transaction name setting in `before_send` we need to use middleware like https://github.com/getsentry/sentry-laravel/issues/439 . Do you have any example code with this working?
