### ISSUE TITLE
Response returns string instead of json content prepended by the arguments of the query/mutation

### ISSUE THREAD

**Issue by jwjuele** [rebing/graphql-laravel#695]
```
"require": {
    "php": "^7.2.5",
    "ext-sqlite3": "^7.3",
    "actuallymab/laravel-comment": "^1.0",
    "cybercog/laravel-love": "^8.4",
    "fideloper/proxy": "^4.2",
    "fruitcake/laravel-cors": "^1.0",
    "guzzlehttp/guzzle": "^6.3",
    "intervention/image": "^2.5",
    "james-heinrich/getid3": "^1.9",
    "laravel/framework": "^7.0",
    "laravel/scout": "^8.0",
    "laravel/tinker": "^2.0",
    "laravel/ui": "^2.4.1",
    "league/flysystem-aws-s3-v3": "^1.0",
    "multicaret/laravel-acquaintances": "^3.3",
    "rebing/graphql-laravel": "^5.1",
    "spatie/laravel-permission": "^3.13",
    "spatie/laravel-sluggable": "^2.2",
    "stevebauman/purify": "^3.0",
    "teamtnt/laravel-scout-tntsearch-driver": "^8.3",
    "tymon/jwt-auth": "^1.0"
},
"require-dev": {
    "facade/ignition": "^2.0",
    "fzaninotto/faker": "^1.9.1",
    "mockery/mockery": "^1.3.1",
    "nunomaduro/collision": "^4.1",
    "phpunit/phpunit": "^8.5"
}
```
### My laravel graphql API randomly started to return a string instead of json which includes the arguments send with the query.

Since a few days im always getting a strange result from my laravel backend:

`"{\"query\":\"query Users{\\n  users(pagination: {offset: 0, limit: 1}) {\\n    items {\\n      id\\n    }\n}\",\"variables\":null,\"operationName\":\"Users\"}{\"data\":{\"users\":{\"items\":[{\"id\":53}]}}}"`

As you can see it's not JSON, but text/html and only contains a string. 
This string contains two json objects, while the first is the query and the arguments of the query itself.
The strange thing is, i could not find a way to consistently reproduce where this error came from.

If i would manually add an 
`echo json_encode($input);`
 in my rebing-graphql vendors at 
`GraphQLController:50`
i would get the same error in my response from laravel

I did NOT make an update of any vendors.
I did NOT add any additional output like "echo $args;" or similar.

The error only occurs on my remote server when my pipeline has run. I'm using a docker image php-fpm-alpine
On my local machine, the same docker image works fine.
There also isn't a specific task during the build process, which causes this behaviour.
After my deployment has setup the container, there is no error and everything works fine.
Sometimes during my database-seeding, sometimes just a day later, all queries start to return the args of the query itself before the actual valid response.
My Nginx log, and my php log do not give any output.

### EDIT:
it's been the first time today where i kindof experienced a first pattern of this behaviour.
It seems like it occurs on every second request i send. 
For testing i edited my laravel/public/index.php and added a exit("index.php"); right after the call of require __DIR__.'/../vendor/autoload.php'; . 
The strange thing is, that even here i will always get a string of json encode input arguments before the response closes with "index.php".

### Steps To Reproduce:
It may not be easy to reproduce this behaviour.
I'm using bachtRequests - so my frontend is sending multiple operations in an array. But if i send single requests via the GraphiQL interface, i get the same result.

It makes me desprrate and i do not know how to solve this issue.
Even resetting my application to an older state, where it has worked before, nor undoing recent composer updates resolves this issue.

One thing that was interesting is that a reboot of my server or my docker service seems to make this issue disappear TEMPORARILY! After making a few more requests the issue reoccures

**Comment by mfn** [comment]
> I did NOT make an update of any vendors.

My verdict here would be it's not a problem with the library.

Are you able to reproduce this in an isolated environment? Using less dependencies?

**Comment by jwjuele** [comment]
I was able to make some further investigation which may indicate that this issue is caused by the underlying server configuration of nginx. I  could not find a specific reaseon for this error. More details here:
https://stackoverflow.com/questions/64960375/api-prepends-response-with-post-request-params-as-json-string

**Comment by mfn** [comment]
I'm reclassifying this from bug to question; there's currently no clear indication it's the library.

> As you can see it's not JSON, but text/html and only contains a string.

I missed this when I read your initial description here but it stood out more in the stackoverflow question.

The library uses `->json` and never anything related to HTML https://github.com/rebing/graphql-laravel/blob/19ea3ed120b96c8c9b45398d0fb1ab1514860a4d/src/GraphQLController.php#L56

**Comment by mfn** [comment]
As I suggested on slack:
> can you publish a docker image which exhibits this problem, the library installed within and the script to reproduce?

**Comment by mfn** [comment]
I'm closing this due to lack of feedback. It's also my feeling that it's not related to the library.

Happy to reopen if you can provide more details.
