### ISSUE TITLE
Creating command Make:graphql:test

### ISSUE THREAD

**Issue by websitevirtuoso** [rebing/graphql-laravel#700]
Hello,

I just started to work on a new project and figure out that I need to write tests again)
I already used this package to write acceptance tests
https://github.com/marvinrabe/laravel-graphql-test

Would be great to write/use a helper like this to write tests easier.
Thanks

**Comment by mfn** [comment]
I think for the moment I'll go with other packages such features. I for one have different requirements for my application and couldn't use this package, aka it's in some way it's _opinionated_.

And that's perfectly fine! I just don't want to endorse a specific way of writing tests as being _the way_ to test them, when it's all about just sending a request.

We might however collect such useful tools to the readme to ease discovery for other, I'm open for PRs!

Thank you
