### ISSUE TITLE
"query" param not work

### ISSUE THREAD

**Issue by pLavrenov** [rebing/graphql-laravel#705]
```php
<?php

declare(strict_types=1);

namespace App\GraphQL\Types;

use App\Models\User;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Facades\GraphQL;
use Rebing\GraphQL\Support\Type as GraphQLType;

class DriverType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Driver',
        'model' => User::class,
    ];

    public function fields(): array
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::id()),
                'alias' => 'uuid',
            ],

            // ..........

            'shifts' => [
                'type' => Type::listOf(GraphQL::type('RentShift')),
                'args' => [
                    'limit' => [
                        'type' => Type::int(),
                        'defaultValue' => 25,
                    ],
                ],
                'query' => function(array $args, $query, $ctx) {

                    // NOT WORK

                    dd(12);
                    return $query;
                },
            ],

        ];
    }
}
```

### Versions:
- graphql-laravel Version: 6.1.0
- Laravel Version: 8.22.0
- PHP Version: 7.4.13

### Question:
"query" param not fire function

another files - default

**Comment by mfn** [comment]
@pLavrenov how does your GraphQL query look like?

This is a type so you need to have the arguments on the type.

**Comment by pLavrenov** [comment]
```php
{
    item: driver(id: "....") {
        id
        ....
        shifts {
             id
        }
    }
}
```

I am not the first one who faced such a problem, if you look in the issues. 
And there the question remained unanswered.

**Comment by crissi** [comment]
how does your resolve method look?

**Comment by pLavrenov** [comment]
This is all the type code, without some fields, it does not contain a "resolve" method and almost completely like the description
https://github.com/rebing/graphql-laravel#type-relationship-query

**Comment by mfn** [comment]
You are not providing arguments to `shifts`, you need to do this:
```graphql
  …
  shift(id: …) {
```

In older versions, top level query/mutation queries applied to all local queries but this was removed, as it just isn't the correct way and resulted in unpredictable behaviour.

**Comment by crissi** [comment]
Are you using SelectFields?

$select = $fields->getSelect();
$with = $fields->getRelations();

return User::select($select)->with($with);

?

**Comment by pLavrenov** [comment]
> Вы используете SelectFields в запросе?
> 
> $ select = $ fields-> getSelect ();
> $ with = $ fields-> getRelations ();
> 
> return User :: select ($ select) -> with ($ with);
> 
> ?

yes

```php
    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        $fields = $getSelectFields();
        $select = $fields->getSelect();
        $with = $fields->getRelations();

        return User::role('driver')
            ->with($with)
            ->filter($args['filter'] , DriverUserFilter::class)
            ->latest()
            ->paginate($args['limit'], ['*'], 'page', $args['page']);
    }
```

**Comment by Inurosen** [comment]
I had the same issue and after some debugging found out that `query` callback is called only for top level parameters

**Comment by mfn** [comment]
Yes, this is expected.

OP @pLavrenov can you confirm?

**Comment by mfn** [comment]
Closing as no further feedback was provided
