### ISSUE TITLE
Uploading multiple files get CORS error

### ISSUE THREAD

**Issue by kimthanh932000** [rebing/graphql-laravel#707]
Hi, I'm using Vue.js for front-end. 

It is ok to upload a single file but when it comes to multiple files, I always get `CORS `error with the following code:

```
const files = e.target.files
const bodyFormData = new FormData()
bodyFormData.set('operations', JSON.stringify({
'query': Query.UPLOAD_FILES,
'variables': {
    'files': files
}
}))
bodyFormData.set('operationName', null)
bodyFormData.set('map', JSON.stringify({'files': ['variables.files']}))
bodyFormData.append('files', files)
await axios.post('/', bodyFormData, {
  headers: {
  'Content-Type': 'multipart/form-data'
  }
  }).then(res => {
  console.log(res)
})
```

I tested on `Altair` and it's completely fine to upload multiple files. But I encounter `CORS` error at front-end.
The `graphql api` is provided by a back-end developer so I don't know where the problem comes from.

**Comment by mfn** [comment]
I closing this as I don't feel this is an issue with graphql-laravel itself: CORS is a setup entirely done outside this library, so it's your responsibility to properly set it up. Aka outside the scope of this package.
