### ISSUE TITLE
Support simplePagination

### ISSUE THREAD

**Issue by lamtranb** [rebing/graphql-laravel#709]
Hi guys, here is my environment:

### Versions:
- graphql-laravel: 6.1.0
- Laravel Version: 8.26.1
- PHP Version: 7.4

### Question:
How can I use PaginationType with simplePagination ? When I use, it throws error:

`Argument 1 passed to Rebing\\GraphQL\\Support\\PaginationType::Rebing\\GraphQL\\Support\\{closure}() must be an instance of Illuminate\\Pagination\\LengthAwarePaginator, instance of Illuminate\\Pagination\\Paginator given, called in /app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php on line 624`

Is there a workaround? 
Thanks.

**Comment by mfn** [comment]
Closing as https://github.com/rebing/graphql-laravel/pull/715#issuecomment-813608749 was merged and released!
