### ISSUE TITLE
upgrade to 1.8.2 got ERROR

### ISSUE THREAD

**Issue by minkbear** [rebing/graphql-laravel#71]
> Declaration of XX\GraphQL\Mutation\TestMutation::rules() should be compatible with Rebing\GraphQL\Support\Mutation::rules(array $args)

when rollback to1.8.0 there is no error.
please advice.

**Comment by rebing** [comment]
Latest update was a breaking change, because the `rules` function in Mutation changed to include a parameter. This means you must also change all existing `rules` functions to include the `array $args` as params.

**Comment by crissi** [comment]
to not make it break, setting it this would fix it

public function rules(array $args = [])

**Comment by rebing** [comment]
Good call, I implemented it #72
