### ISSUE TITLE
auth + graphiql

### ISSUE THREAD

**Issue by drmax24** [rebing/graphql-laravel#711]
Hi guys.
Do you use graphiql together with auth tokens somehow?

**Comment by mfn** [comment]
I don't: graphiql is only exposed in non-production environments and uses a `web` style middleware which is based on PHP sessions.

**Comment by drmax24** [comment]
Yes but you may need to debug your logged-in workflow locally

**Comment by mfn** [comment]
TBH I'm not really sure what exactly this question is about :)

GraphiQL integration supports defining a middleware, which can be anything you want.

Can you maybe clarify what you're looking for?

**Comment by mfn** [comment]
Closing due to lack of feedback; happy to re-open if more info is provided.
