### ISSUE TITLE
Query introspection for api-key guarded schema

### ISSUE THREAD

**Issue by drmax24** [rebing/graphql-laravel#712]
- Laravel Version: 6

### Question:
Hi! What would be the best way to allow query introspection for api-token guard-protected schema

Any suggestions of smth better than this security hole?

```
class GraphQLAuthenticate extends Authenticate
{
    public function handle($request, Closure $next, ...$guards)
    {
        $query = $request->request->get('query') ?? $request->query->get('query');
        if (strpos($query, 'IntrospectionQuery') !== false) {
            return $next($request);
        }

        if ($this->authenticate($request, $guards) === false) {

            return response()->json([
                'data' => null,
                'errors' => $this->getError()
            ], 403);
        }

        return $next($request);
    }
```

**Comment by mfn** [comment]
I wonder if this is related to https://github.com/rebing/graphql-laravel/issues/711

I'm not entirely sure what you are after. Your schema is auth protected? And only in case of an authenticated user you want to allow introspection? Or you want to allow introspection for all users, authenticated or not?

**Comment by mfn** [comment]
Closing due to lack of feedback; happy to re-open if more info is provided.
