### ISSUE TITLE
Namespaced type

### ISSUE THREAD

**Issue by fernandocoronatomf** [rebing/graphql-laravel#714]
Hey guys,

Firstly, I appreciate the package and it has been of great use.

I'd like to know if there is any way to display a type for a certain schema only?
My graphql.php has 3 different graphql endpoints that contain different queries and mutations from each other.
However, the types are shared across all 3 namespaces, which makes our life difficult to validate the schema against a schema file for each namespace. 

For example, 

``` 
'schemas' => [
    'default' => [
         'query' => ..., 'mutation' => ..., 'middleware'....
    ],
    'default2' => [
         'query' => ..., 'mutation' => ..., 'middleware'....
    ],
    'default3' => [
                 'query' => ..., 'mutation' => ..., 'middleware'...., **'types' => []**
    ],
],
'types' => [
    // this types are inherited for all the 3 above schemas
]
```

Thanks.

**Comment by mfn** [comment]
There's a PR for "per schema types" -> https://github.com/rebing/graphql-laravel/pull/658

Maybe this would help.

Unfortunately I currently lack time to properly review and test this though I would love to get the ball rolling there.

It's already quite outdated but maybe you find a way to test if this would work for you?

**Comment by fernandocoronatomf** [comment]
Actually, after writing the thread I decided to give it a try.

It is interesting though... I added 
```  'types' => [

            ], ```
in a certain schema and it worked. Also, the other schema did not get this specific type...
Wasn't that supposed to happen or am I missing something?

**Comment by fernandocoronatomf** [comment]
OK, actually it shows up on the schema when I load graphiql
![image](https://user-images.githubusercontent.com/1309374/108012452-845eb200-705d-11eb-864f-1a8eb206d442.png)

But when I try to use the type, it does not work.

`"message": "Type install not found.",`

**Comment by mfn** [comment]
Was this with master or did you try the PR I mentioned?

**Comment by mfn** [comment]
https://github.com/rebing/graphql-laravel/pull/658 has been merged and a new release has been tagged https://github.com/rebing/graphql-laravel/releases/tag/6.4.0
