### ISSUE TITLE
Middleware broken in Laravel 8

### ISSUE THREAD

**Issue by thomas-ecosurv** [rebing/graphql-laravel#725]
### Versions:
- graphql-laravel Version: 6.3.0
- Laravel Version: 8.33.1
- PHP Version: 8.0

After auto generating some middleware:
```
ArgumentCountError
Too few arguments to function App\GraphQL\Middleware\<Your middleware name here>::handle(), 2 passed in /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php on line 167 and exactly 5 expected
```

Makes custom middleware impossible to use.

**Comment by thomas-ecosurv** [comment]
Changed ./vendor/rebing/graphql-laravel/src/Support/Middleware.php to:
```
<?php

declare(strict_types=1);

namespace Rebing\GraphQL\Support;

use Closure;
use GraphQL\Type\Definition\ResolveInfo;

abstract class Middleware
{
    public function handle($request, Closure $next)
    {
        return $next($root);
    }

    /**
     * @see Field::getResolver()  Middleware is resolved in the field resolver pipeline
     */
    public function resolve(array $arguments, Closure $next)
    {
        return $this->handle(...$arguments, ...[
            function (...$arguments) use ($next) {
                return $next($arguments);
            },
        ]);
    }
}
```

seems to improve things

**Comment by mfn** [comment]
You mixed the "GraphQL middleware" with a "HTTP middleware"

I can see this because you changed `handle()` to remove the GraphQL specific arguments.

Please see the readme how to register them properly -> https://github.com/rebing/graphql-laravel#registering-middleware

**Comment by thomas-ecosurv** [comment]
Thanks for the quick reply and support :)
