### ISSUE TITLE
Could you clarify how to get custom fields?

### ISSUE THREAD

**Issue by ddeath** [rebing/graphql-laravel#73]
Hi there,

I would like to ask you what do you mean by:
`// Uses the 'scopeIsMe' function on our custom User model`

In your example in readme is `isMe` defined as boolean, but eloquent scope methods should always return queries. So how would you implement `scopeIsMe` on User model?

Thank you

**Comment by rebing** [comment]
That was a mistake in the ReadMe, I've fixed it now.

It should be `getIsMeAttribute` instead, which enables calling `is_me` or `isMe` as a magic attribute
