### ISSUE TITLE
Use single endpoint with middleware and non-middleware routes

### ISSUE THREAD

**Issue by priyalLimbani** [rebing/graphql-laravel#732]
Hello,

I want to use same endpoint like localhost/graphql for all routes but with different middleware .

Like for login don't want to use any middleware and for userprofile use auth middleware and also I am using tenancy concept of Stancl 

can you pls help me set Single endpoint with 1 schema but use middleware with some query .

Thank you.

**Comment by mfn** [comment]
> I want to use same endpoint like localhost/graphql for all routes but with different middleware .

This is not possible.

Laravels "HTTP middleware" can only be applied on the "schema" level which is equivalent to the "route level".

That is, assume you've a custom schema `/api/graphql/customschema` -> you can specify a "HTTP middleware" no matter if you call the GraphQL query `getUsers` or the mutation `assignTask`.

What the library does support is ["resolver middleware"](https://github.com/rebing/graphql-laravel#resolver-middleware): conceptional the same thing, but technically different:
- they are not compatible with HTTP middlewares (though look very similar)
- they indeed apply on the query/mutation level

If you want to manage some mutations like `login`, which I understand operate differently than e.g. `assignTask`, you have to use different schemas with different HTTP middlewares. You could make a default / internal schema for all your regular app interactions and a specific `public` schema, for mutations like `login`, `registerUser`, etc.

**Comment by priyalLimbani** [comment]
Thanks for answer.

The Problem is Android and IOS team need to download first static schema after then they can use that schema in app . 

if we are using passport auth at schema level its not allow first downloads schema or other word schema will not seen until we not provide required headers token.

can you please help for that.

**Comment by mfn** [comment]
I think you need an "out of band" way to generate the schema, like and endpoint which just provides the schema itself.

I suggest to look into `\GraphQL\Type\Introspection::getIntrospectionQuery` which provides such a query and then using something like
```php
        $result = app('graphql')->query($query, null, ['schema' => $schema,]);
```
To generate it and provide the resulting JSON in a way fit for your mobile apps.

Note: I think for this to work you need to have `graphql.security.disable_introspection` set to `false` (which is not necessarily recommended for production, btw).

HTH
