### ISSUE TITLE
PHP notices cause error responses.

### ISSUE THREAD

**Issue by nathanblogs** [rebing/graphql-laravel#735]
### Versions:
- graphql-laravel Version: 5.0
- Laravel Version: 7.0
- PHP Version: 7.4

### Description:

Due to how the error handlers are setup in larval a notice error will cause a query to fail.

This is due to all errors in laravel causing an ErrorException to be raised, this will break the code flow and return to ExecutionResult to handle the error.

Ideally errors that can be "ignored" would allow the code to continue execution

### Steps To Reproduce:

- add some code that creates a php notice to any endpoint
- get a response with an error from error_formatter

**Comment by mfn** [comment]
> Ideally errors that can be "ignored" would allow the code to continue execution

I am sorry, but I **strongly** disagree here. You have a bug in the code. You need to attend to it.

If that were supposed to be "ignored" then Laravels error handler would not have converted it into an actual exception.

Using this library is not different then any other like e.g. sentry, which catches `\Throwable` and reports everything too.
