### ISSUE TITLE
Error object with data object null

### ISSUE THREAD

**Issue by priyalLimbani** [rebing/graphql-laravel#736]
Hello,

I throwing error using graphql error

use GraphQL\Error\Error;
return new Error('credetial_wrong');

after this I will get error object in response but with data object like 

 "data": {
        "agentresetpassword": null
    }

I don't want send this data object while throwing error.

Can you pls help me.

**Comment by mfn** [comment]
Please provide more details:
- where are you throwing `Error` exactly (resolver? Which one?)
- does this also happen if you throw e.g. a simple `\RuntimeException`
- show the types where the error can be thrown (query/mutation , types involved)

**Comment by knshah2010** [comment]
Hi Look at the code which is written in Query . 

giving you some what more brief here we are trying to Authenticate user and if we did not match user/agent data we are returning error. but in this case error object is going as per expectation but additionally its adding data object with some null value  .
below is our entire query resolve snippet.
` public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields =null)
    {
     
        $agents=$this->model->getBycolname('contact_no',$args['contact_no']); 

        if (count($agents)>0 && Hash::check($args['password'], $agents[0]->password)){
            $agent=$agents[0];
            if($agent->country_code !== $args['country_code']){
                
                return new Error('countrycode_wrong');
               
               
            }
            $company_id=$agent->company_id;
            $userid=$agent->id;
            tenancy()->initialize($company_id);
                
            $agent=$this->model->getsingleRecord('company_id',$company_id);
            $agent->device_id=$args['device_id'];
            $agent->device_type = $args['device_type'];
            $agent->save();  
            $agent=$this->model->with('agentvehicles');
            //dd($agent->agentvehicles);
            $token=$agent[0]->createToken('Agent App',['agent'])->accessToken;
           // $agent->agentlivetracker=;\

            $agent[0]->token = $token;
            return $agent[0];

           // return ['token'=>$token, 'agentdetail' => $agent[0]];
    
        }else{
           return new Error('credetial_wrong');
           //return null
       }   
    }`

in response there is an errors array and it is as per desire requirement but in added to that we are getting below  data object 

` "data": {
    "login": null
  }`

in case of error we don't want data object. please guide us how we can achieve  the same.

**Comment by mfn** [comment]
Ah ok. For some reason it wasn't clear to me, but actually it is. This is expected and per the spec 🤷‍♀️

See https://spec.graphql.org/June2018/#sec-Errors

> If the data entry in the response is present (including if it is the value null), the errors entry in the response may contain any errors that occurred during execution.

Basically, because _during_ execution of your resolver the error happens, the "result" is resolved to `null` **with** `errors`.

It's also not something _this_ library does explicitly, it's the behaviour of graphql-php.

I you need to change this, you have to do something custom. You could add a middleware which changes the JSON and removes `data` if `errors` is present etc.
