### ISSUE TITLE
Call to undefined method GraphQL\\Type\\Definition\\ListOfType::getField()

### ISSUE THREAD

**Issue by channing-froom** [rebing/graphql-laravel#74]
When trying to pass array data through a type as a sub array i get the following exception

```Call to undefined method GraphQL\\Type\\Definition\\ListOfType::getField()```

Background : i have 2 types

- lookups
- options

i have a service that collects and formats an array for these types which look something like this 

```
[
   'title' => 'some title',
   'options' => [
        [
            'id' => 1,
            'title' => 'some option title'
        ]
   ]
]
```

the type objects

```
class LookupType extends GraphQLType {

    protected $attributes = [
        'name' => 'Lookup',
        'description' => 'Application Lookup',
    ];

    public function fields()
    {
        return [
            'title' => [
                'type' => Type::string(),
                'description' => 'Title',
            ],
            'options' => [
                'type' => Type::listOf(GraphQL::type('Options')),
                'description' => 'List of options for the current lookup',
            ],
        ];
    }
}

// --------------------------------------------------------------

class OptionsType extends GraphQLType {

    protected $attributes = [
        'name' => 'Options',
        'description' => 'The relational values for lookups',
    ];

    public function fields()
    {
        return [
            'id' => [
                'type' => Type::int(),
                'description' => 'Primary key / identifier for table'
            ],
            'title' => [
                'type' => Type::string(),
                'description' => 'Title'
            ]
        ];
    }
}
```

the query 

```
{
  lookups{
    title,
    options {
	title
    }
  }
}
```

Now generally adding a model to the type will resolve the data and identify it as a collection, But for this specific case there is no model for the data since its just a compiled array.

i have tried to add resolvers to both the types to attempt to resolve the objects while populating them. But the error actually pops up before any resolvers are reached, it seems the the listOf object cant identify the fields (or the assigned object :: GraphQL::type('Options'))

Iv gone through the documents from http://webonyx.github.io/ but nothing shows me a way to resolve this, unless im missing something ?? 

HELP

**Comment by channing-froom** [comment]
its almost like the ListOf object doesnt know how to resolve array data, and yes iv tried updating the arrays to collections in the hope that the core code targets collection rather than eloquent collections

**Comment by channing-froom** [comment]
@rebing So it seems that u are resolving all listOf objects as eloquent objects in `rebing/graphql-laravel/src/Rebing/GraphQL/Support/SelectFields.php` ... is there some sort of way to disable this so the package can treat the data as a collection or an array ?

**Comment by rebing** [comment]
Change the `OptionsType` so it will extend `GraphQL\Type\Definition\InputObjectType` instead and change the type to `Type::listOf(new OptionsType())`. There's probably a better solution, but this should work

**Comment by channing-froom** [comment]
@rebing no that doesnt work, Updated the extension and how it resolves the configs, but get the same error back. 

updated both the files too. still breaks,
moved them back to original files and updated the setting `$this->inputObject`

but still brings back same error.

**Comment by channing-froom** [comment]
This causes a lot of issues since most laravel architecture should be running off a service layer which doesnt always collect data from a eloquent model, 

our data comes from cached json objects, API calls or Elastic Search objects and we need to be able to map our types accordingly. So a solution would be great to avoid me writing a layer over webonyx package 😢

**Comment by rebing** [comment]
#83 This should have solved it

**Comment by SobiaNodesol** [comment]
sir, kindly resolve my issue
"message": "Type User not found. Check that the config array key for the type matches the name attribute in the type's class.",
    "exception": "Rebing\\GraphQL\\Exception\\TypeNotFound",
