### ISSUE TITLE
Please add the @defer feature

### ISSUE THREAD

**Issue by Rasool-deldar** [rebing/graphql-laravel#743]
This feature allows it to load the items that need to be loaded first and the items that need to be loaded later. 

Please click on [@defer](https://www.apollographql.com/blog/introducing-defer-in-apollo-server-f6797c4e9d6e/)

**Comment by illambo** [comment]
> The @defer directive is an experimental Apollo feature.

**Comment by Rasool-deldar** [comment]
So this feature is not added?

**Comment by illambo** [comment]
IMO I think it is not convenient to see the thing until it is stable and at least we need to first implement the directives that are not currently present.

**Comment by mfn** [comment]
Yep, as said we don't even support directives 😅

`@defer` is quite complex, as it requires to support streams which kind send patches/delta updates to the client after the initial response is sent.

@Rasool-deldar do you intend to work on this feature?

**Comment by Rasool-deldar** [comment]
> Yep, as said we don't even support directives 😅
> 
> `@defer` is quite complex, as it requires to support streams which kind send patches/delta updates to the client after the initial response is sent.
> 
> @Rasool-deldar do you intend to work on this feature?

Yes, I wanted to use it on my project, something interesting, now they said in the [roadmap](https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md#support-for-defer-live-and-stream) that they want to support it.

**Comment by mfn** [comment]
> If we can add this feature to the package, it will be great

@Rasool-deldar do you intend to add this feature to the library?

High level it would need:
- add support for directives in general (@illambo was working on this once in https://github.com/rebing/graphql-laravel/pull/703)
- add support for the defer directive
- add support for streams / chunked responses

**Comment by mfn** [comment]
> do you intend to add this feature to the library?

Closing issue, as I got no feedback here.

It's debatable whether this is just a question or a feature request, but I'm usually not a fan of keeping feature request issues around: there are just not that many contributors that we've a stampede of willing developers to implement everything.

OTOH if you want to add support here, PRs are the way to go!
