### ISSUE TITLE
Pre hook/middleware

### ISSUE THREAD

**Issue by crissi** [rebing/graphql-laravel#753]
Gives us the ability to change/check the query received before it is being parsed.

Cases:
 * detect unused variables ( mfn already implented this )
 * change a query type, ex. from int to string, without breaking the api for consumers
 * change variables to conform to the newest webonyx release (has more strict variable checking).

**Comment by mfn** [comment]
> Gives us the ability to change/check the query received before it is being parsed.

Any proposal as to how to do it?

> detect unused variables ( mfn already implented this )

Maybe an architecture which can incorporate the manual code I added; would be glad for that.

> change variables to conform to the newest webonyx release (has more strict variable checking).

Do you have more details?

**Comment by crissi** [comment]
I think it could be implemented a lot like the middleware already in existent, but since we dont have the query name ( i think) it would probably be in a global config.

_change variables to conform to the newest webonyx release (has more strict variable checking)._
Strict coercion of scalar types in https://github.com/webonyx/graphql-php/releases/tag/v14.0.0

**Comment by mfn** [comment]
The only worrying thing to me right now is to introduce yet another middleware/hook layer 😅

> _change variables to conform to the newest webonyx release (has more strict variable checking)._
> Strict coercion of scalar types in https://github.com/webonyx/graphql-php/releases/tag/v14.0.0

Oh, I remotely remember. What are you suggest here? A hook which is in fact able to relax the coercion strictness for input?

**Comment by mfn** [comment]
We would have three layers of middleware:
- http middleware (aka what we already have with Laravel)
- execution middleware (new feature?)
- resolver middleware (implemented)

All work similarly in concept but all have different signatures and serve different purposes.

I guess this "execution middleware" would work within _each_ result of a batch, distinctively ? https://github.com/rebing/graphql-laravel/blob/65270611e1c59c9303ecb31600a6267ddee68ff1/src/GraphQLController.php#L65-L70 and would be defined on the "schema level" (a bit like the http middleware but unlike the resolver middleware; though nothing would prevent from making the resolve middleware also on the schema level aka global possible etc.)

Basically around the notion of `executeQuery($schemaName, $operation)` we would have something in between

However we would need additional flexibility: I can imagine that the string GraphQL query might get parsed into its AST and then also worked with during that phase:
- The recently added `\Rebing\GraphQL\GraphQLController::handleAutomaticPersistQueries` already does this: it returns a named tuple with the query as string and optional the already parsed (i.e. retrieved from cache) query DocumentNode, so a re-parsing isn't necessary.
- Probably not just "detect unused variables" would be a middleware but also "automatic persist queries".
- Also even this call to `validateOperationParams` could be one https://github.com/rebing/graphql-laravel/blob/65270611e1c59c9303ecb31600a6267ddee68ff1/src/GraphQLController.php#L86
- Disable / enable batch support… .. not sure, this has to happen outside each `executeQuery`.
- Maybe also injecting/definig the "query context" could be a fit

Well basically I can up with a lot of creative ideas of all the parts which happen after we parsed the input via `\Laragraph\Utils\RequestParser` https://github.com/rebing/graphql-laravel/blob/65270611e1c59c9303ecb31600a6267ddee68ff1/src/GraphQLController.php#L38 until the point we pass it to `\GraphQL\GraphQL::executeQuery` in https://github.com/rebing/graphql-laravel/blob/8f189d53956b990ab659ced2bce8330cda877b1c/src/GraphQL.php#L151

The way arguments are passed to `\Rebing\GraphQL\GraphQL::query` with the `$opts` argument is a bit strange (it's kind of a temporary argument bag).

To a certain extend I'm not concerned about internal code refactoring / BC breaks: I already did some recently https://github.com/rebing/graphql-laravel/blob/ed40c371dfaab4cba5f194cdc9e5404d7da06aa0/CHANGELOG.md#breaking-changes in preparation for the next major version. Basically _now_ would be a good time to think about these things 😄 

Things to keep in mind, taken from https://github.com/rebing/graphql-laravel/issues/629#issuecomment-816471699
> Some time ago I tried to write down a PR #703 but I did not have the opportunity to continue and I found it complex

I.e. it would be important not to prevent an implementation of directive to happen or other stuff.

---
Lots of things possible 😬

However right now my focus, if I find time is rather:
- Performance, i.e. https://github.com/rebing/graphql-laravel/issues/390
- Compatibility with application servers (e.g. Octane)

I haven't done work in either direction, just what my current preference would be.

**Comment by crissi** [comment]
_Oh, I remotely remember. What are you suggest here? A hook which is in fact able to relax the coercion strictness for input?_
I am thinking the middleware receives query (parsed?) and the variables and you modify the variables to conform to the query. and the query and the variables are sent to the next middleware or end. 

"change a query type, ex. from int to string, without breaking the api for consumers" would require to modify the query and send the modified query along to the next.

Ex.
```
   public function handle($query, array $variables)
    {


        return $next($query, $variables);
    }

```
Never actually dug down in that part of the code, so this just my initial thought.

Wow lot of good points, I can try to put some time into creating a draft

**Comment by mfn** [comment]
> would require to modify the query and send the modified query along to the next.

I was actually only thinking/understand to act on the `$variables`, not the query? 🤔 If not, I think I then don't understand this part TBH.

**Comment by crissi** [comment]
https://chanind.github.io/2019/05/26/graphql-breaking-changes.html here is an example

**Comment by mfn** [comment]
Nice I think I got it now.

I wonder though how they manage to minimize the overhead of parsing the query in the middleware and pass the (modified?) result on. I briefly looked at the readme of https://github.com/graphql-query-rewriter/core and it says:
> Note that you need to specify bodyParserConfig: false in applyMiddleware() since express-graphql-query-rewriter already parses the graphQL body in order to rewrite it.

We would definitely need something similar.

Anyway, crazy scary stuff I've to say 😬

**Comment by crissi** [comment]
Just started to look into this, and came across /vendor/webonyx/graphql-php/src/Validator/DocumentValidator.php which has rules, it also has a **NoUnusedVariables** and was wondering what is the different between your implementation and this one, mfn?

**Comment by crissi** [comment]
can see that **change variables to conform to the newest webonyx release (has more strict variable checking).**

can be "fixed" by lessening graphql validations, so we could do:

![image](https://user-images.githubusercontent.com/3076578/116155207-16340c80-a6ea-11eb-99eb-bf8673aec29e.png)

to make it possible to set from the config, would you accept an pr on that?

**Comment by mfn** [comment]
Not sure I full understand so PR to discuss this LGTM!

**Comment by mfn** [comment]
PR merged, I'll make new RC soon-ish
