### ISSUE TITLE
does this support the current version of lumen?

### ISSUE THREAD

**Issue by codeitlikemiley** [rebing/graphql-laravel#76]
ive check folkloreatelier repo they support lumen,
and out of the box comes with a graphiql for making test of the query...

but this one got extra stuffs, like pagination which i think is best for large set of data...
if this is compatible with lumen i dont mind pulling in noh4ck package for the graphiql

**Comment by codeitlikemiley** [comment]
is there a way also to disables the artisan command register for production?
i want my production very lean of unnecessary commands for production...

coz in my lumen app in bootstrap/app.php
im declaringthis
```
//! Use Only During Development, Test and Staging For Performance
if (app()->environment('local', 'staging')) {
    $app->register(Laravel\Tinker\TinkerServiceProvider::class);
    $app->register(Flipbox\LumenGenerator\LumenGeneratorServiceProvider::class);
}

```
is there a way i can only register the file generator only on local or staging?

**Comment by codeitlikemiley** [comment]
I make a Pull Request to add a check on the using register Commands Can you Add it on the Repo?

**Comment by rebing** [comment]
I don't know about Lumen, I've never tried it with this repo
