### ISSUE TITLE
change header error code

### ISSUE THREAD

**Issue by asroapp1** [rebing/graphql-laravel#760]
### Versions:
- graphql-laravel Version: #.#.#
- Laravel Version: #.#.# 
- PHP Version: #.#.#

### Question:

I used this method for validation
But in case of error, it should give the code 422, but it should be sent in the code code 200
How can I fix this?
my rules:
    protected function rules(array $args = []): array
    {
        $v=[
            'Phone'=>['required','numeric',new ValidateUserPhone(),'unique:users'],
            'FirstName' => ['required' , 'string' ],
            'LastName' => ['required' , 'string'],
            'password' => ['required','string'],
            'ShopId' => ['required']
        ];
        return $v;
    }
header response:
200OK
121 ms
16.39 KB

**Comment by mfn** [comment]
The GraphQL spec is notoriously silent on this matter and it's basically "not defined", e.g. https://graphql.org/learn/serving-over-http/ does not even mention anything.

Therefore the most sensible option most libraries chose it to return 200; always.

There are forces on the way to make this eventually more explicit, see e.g. https://github.com/graphql/graphql-over-http

If you feel like you have to adapt this, you can look into overriding `\Rebing\GraphQL\GraphQLController::query` or providing a replacement controller (can be set in the config) and chose your own strategy.
