### ISSUE TITLE
8.0.0-rc3 is broken

### ISSUE THREAD

**Issue by tm1000** [rebing/graphql-laravel#792]
```
Failed to extract rebing/graphql-laravel: (9) unzip -qq  '/usr/src/vendor/composer/tmp-26badbb53984b3ef05ddd3ed558d5d24.zip' -d '/usr/src/vendor/composer/19409e4c'

unzip:  cannot find or open /usr/src/vendor/composer/tmp-26badbb53984b3ef05ddd3ed558d5d24.zip.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
```

**Comment by mfn** [comment]
Please provide the full command you tried, and, since this seems composer related, also the composer version. Best is to provide PHP version and composer version and full output.

(ps: I've installed RC3 since I released it, no issues)

**Comment by mfn** [comment]
Seems there was some composer related regression recently, e.g. I saw https://github.com/composer/composer/issues/9940 just now.

Please make sure you use the latest composer version too.

**Comment by tm1000** [comment]
@mfn all is well. I use Nexus Repository which supports Composer as a plugin. It also have a feature to proxy packagist and that never seems to work well... this case included. So I just put it back to packagist and solved.

Thanks!
