### ISSUE TITLE
Relation not working

### ISSUE THREAD

**Issue by ardani** [rebing/graphql-laravel#8]
hi @rebing 
i using Laravel Framework 5.4.19 for my project and use your package version dev-master
i try get relation with 
```php
public function resolve($root, $args, SelectFields $fields)
    {
        return User::with($fields->getRelations())->select($fields->getSelect())->get();
    }
```
`$this->getRelations()` not get join model but if i harcode with name join table it working
any solution for it?
thanks

**Comment by rebing** [comment]
Make sure you have _model_ defined in your UserType $attributes:

```
protected $attributes = [
    ...
    'model' => User::class,
];
```
