### ISSUE TITLE
APQ not working as described by Apollo documentation

### ISSUE THREAD

**Issue by gassius** [rebing/graphql-laravel#801]
### Versions:
- graphql-laravel Version: 7.2.0
- Laravel Version: v8.50.0 
- PHP Version: 8.0.8 | 7.4.*

### Description:

Trying to test the APQ functionality as described in the [Apollo Documentation](https://www.apollographql.com/docs/apollo-server/performance/apq/) (that is linked from this package README) results in an error. Running the first command described in th[e Command-line testing](https://www.apollographql.com/docs/apollo-server/performance/apq/#command-line-testing):
`curl -g 'http://localhost/graphql?extensions={"persistedQuery":{"version":1,"sha256Hash":"ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"}}'`
Results in an error not corresponding with the APQ specification:
```
{
    "errors": [
        {
            "message": "Syntax Error: Unexpected <EOF>",
            "extensions": {
                "category": "graphql"
            },
            "locations": [
                {
                    "line": 1,
                    "column": 1
                }
            ]
        }
    ]
}
```

A partial cause of the problem may be in the way the input is decoded [here](https://github.com/rebing/graphql-laravel/blob/1cad971c293ba4bf285f5c834bd2c1361ddae773/src/GraphQLController.php#L123) when the actual input is formated as

```
array:1 [
  "extensions" => "{"persistedQuery":{"version":1,"sha256Hash":"ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"}}"
]
```

### Steps To Reproduce:
1- Install a fresh Laravel instance (for example, using sail) `curl -s https://laravel.build/apq-issue-test | bash`
2- `cd apq-issue-test/`
3- `./vendor/bin/sail up -d`
4- Add `rebing/graphql-laravel` (using sail) `./vendor/bin/sail composer require rebing/graphql-laravel`
5- Publish conf `sail artisan vendor:publish --provider="Rebing\GraphQL\GraphQLServiceProvider"`
6- Enable APQ on `config/graphql.php:L227`
7- Execute: `curl -g 'http://localhost/graphql?extensions={"persistedQuery":{"version":1,"sha256Hash":"ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"}}'`
- …

**Comment by illambo** [comment]
Hi! Check this #780, I think it may be useful to you.

**Comment by gassius** [comment]
Thanks @illambo
After reading that thread I am glad that is working on RC, but I might not have the luxury of waiting for it. I patched the [suspected line](https://github.com/rebing/graphql-laravel/blob/1cad971c293ba4bf285f5c834bd2c1361ddae773/src/GraphQLController.php#L123) from now and it does work, and was about to put a PR with the patch but now reading that there is a solution coming in RC I would not dare (and also after reading that @mfn is on vacation, does not make sense)

**Comment by mfn** [comment]
Thanks @illambo for jumping!

I've added it to the milestone, but basically there's nothing actionable here except making that release.

**Comment by mfn** [comment]
The release is there https://github.com/rebing/graphql-laravel/discussions/857 !

Closing
