### ISSUE TITLE
Generating Graphql controllers

### ISSUE THREAD

**Issue by khorramk** [rebing/graphql-laravel#805]
Hello.

Would not be good if we generate Graphql controllers using stub from laravel?

something like :

`php artisan make:graphql:controllers`

currently I do not see any on the current version

Thanks

**Comment by mfn** [comment]
What's your use case in that you would see value in creating GraphQL _controllers_ easily?

**Comment by khorramk** [comment]
> What's your use case in that you would see value in creating GraphQL _controllers_ easily?

Currently Laravel use this command to make normal controllers:
`php artisan make:controller <name> <option>`

In the above command, you have to provide extra details such as the path and option.

Lets say if we did create a normal controller, it would be under `App\Http\Controller` namespace.
We have to then find and provide the `\Rebing\GraphQL\GraphQLController` in each controller manually to be used in controllers.

For separation of concern everything should be under `App\Graphql` namespace. As it is the case for middleware, queries and mutation.

**Comment by mfn** [comment]
I get that part, but _why_ do you need controllers so often that it needs a dedicated command?

In 99% of the cases, you don't really need a custom controller. And in the remaining 1% case I would argue in 0.99% of the cases you want to extend the existing one and override functionality, rather.

Thus my question: what's your use case that creating controllers for this library would benefit from having a command?

**Comment by khorramk** [comment]
> I get that part, but _why_ do you need controllers so often that it needs a dedicated command?
> 
> In 99% of the cases, you don't really need a custom controller. And in the remaining 1% case I would argue in 0.99% of the cases you want to extend the existing one and override functionality, rather.
> 
> Thus my question: what's your use case that creating controllers for this library would benefit from having a command?

ok. closing this issue since I have found a way around this.
