### ISSUE TITLE
how can i treat nested json_object

### ISSUE THREAD

**Issue by SZEth8** [rebing/graphql-laravel#82]
Hi! i have a records with one column that stores a json_object in relational database. 

|--uuid--|--attribute_one--|--attribute_two--|--json_data--|

Reading the doc's i have to create a Type of this Model, but i don't know how to treat the json_data attribute. 

I have defined the "Assessor" method in Eloquent of my Model, but this returns an array and throws an error. 

Sorry im new with this Library and im evaluating if we can design a new resource API with GrapQl. 

Thanks :D

**Comment by rebing** [comment]
Hi, how do you need the json data to be returned? You could use the resolve method on the field, for example:

```
public function resolveJsonDataField($type)
{
    return json_decode($type->json_data);
}
```

This will convert the json string to array every time, it's retrieved with the query. I'm not sure I understand your problem correctly though.

**Comment by SZEth8** [comment]
im trying to do this: 

{
  "uuid": 34c8d101-245b-46d6-af2c-4aa8a02ba998,
  "description": "some description", 
  "attributes": {
     "one": "data",
     "two": "data"
   }
}

The source of "attributes" is a stored in "json_data" in my model.

**Comment by rebing** [comment]
Have you tried creating a graphql AttributesType with the required Fields and adding a Field to the root object like this:

```
'attributes' => [
  'type' => GraphQL::type('attributes')
]
```

**Comment by SZEth8** [comment]
Yeahh! I have and error in the query: 

Field \"attributes\" of type \"AreaAttributesType\" must have a sub selection

But it's error of my Query: 
{"query": "query AreaQuery{area{data{id,uuid,attributes,description}}}"}

"attibutes" param has some other fields that i defined in "AttributesTypes" like: "one" or "two". This is the all code: 

`
class AreaType extends GraphQLType
{
    protected $attributes = [
        'name'          => 'Area',
        'description'   => 'Area Type',
        'model'         => Area::class,
    ];

    public function fields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::int()),
                'description' => 'the id'
            ],
            'description' => [
                'type' => Type::string(),
                'description' => 'the description'
            ],
            'uuid'  => [
                'type' => Type::string(),
                'description' => 'the uuid of the model'
            ],
            'attributes' => [
                'type' => GraphQL::type('AreaAttributes'),
                'selectable' => false
            ]
        ];
    }

    public function resolveAttributesField($type)
    {
        return $type->attributes;
    }

}


class AreaAttributesType extends GraphQLType
{

    protected $attributes = [
        'name'          => 'AreaAttributesType',
        'description'   => 'some other attributes',
    ];

    public function fields()
    {
        return [
            'one' => [
                'type' => Type::boolean(),
                'description' => 'the one attribute'
            ],
            'second' => [
                'type' => Type::boolean(),
                'description' => 'the second attribute'
            ],            
        ];
    }
}
`

It is correct?

Thanks. 

By the way, is there a way to get All data of attributes in query from this: 

{"query": "query AreaQuery{area{data{id,uuid,attributes,description}}}"}

Thanks again

**Comment by rebing** [comment]
`Field "attributes" of type "AreaAttributesType" must have a sub selection` means that you must select something with the "attributes" field (you must always specify `every` root field). So change your query from
`{"query": "query AreaQuery{area{data{id,uuid,attributes,description}}}"}`
to
`{"query": "query AreaQuery{area{data{id,uuid,attributes{one,two},description}}}"}`
