### ISSUE TITLE
"Unable to locate publishable resources." when running vendor:publish

### ISSUE THREAD

**Issue by armandojs** [rebing/graphql-laravel#821]
I'm probably missing something in my config or requirements.  Following the readme file, I got stuck on _publishing the configuration file_.

Every time I execute this statement:
`$ php artisan vendor:publish --provider="Rebing\GraphQL\GraphQLServiceProvider"` 
I get the following error:

> /var/www/app $ php artisan vendor:publish --provider="Rebing\GraphQL\GraphQLServiceProvider"
Unable to locate publishable resources.
Publishing complete.

Running `php artisan vendor`  brings up a list without the GraphQLServiceProvider.

I'm probably just going to copy the config file manually and register it in the app.php file.  I'd like to confirm if there are more steps required to configure this manually.

My dev environment:
Docker Compose
Containers
php, redis, arangodb, mysql, queue, scheduler, nginx

Project is Laravel Lumen with following packages:

- "dusterio/lumen-passport": "^0.3.4",
- "flipbox/lumen-generator": "^8.2",
- "guzzlehttp/guzzle": "^7.3",
- "laravel/lumen-framework": "^8.0",
- "laravelista/lumen-vendor-publish": "^8.0",
- "rebing/graphql-laravel": "^7.2",
- "triagens/arangodb": "^3.8",
- "webonyx/graphql-php": "^14.9"

**Comment by mfn** [comment]
That looks strange. I'm swamped right now but I hope I can take a look later this weekend 🤞 

(ps: maybe you can test `dev-master`? 7.* isn't really receiving updates anymore)

**Comment by armandojs** [comment]
Thanks for getting back to me on this. I ended up copying the config files, enabled the service provider and got it working.  

I haven't had time to check this issue, been more involved in figuring out how to implement graphql into my new project. I've been using REST up until now.  Good luck with everything!

**Comment by sforward** [comment]
@mfn I've tested this for 8.0.0-rc4 with Laravel 8, and it works as expected:

>$ php artisan vendor:publish --provider="Rebing\GraphQL\GraphQLServiceProvider"
>Copied File [/vendor/rebing/graphql-laravel/config/config.php] To [/config/graphql.php]
>Publishing complete.

**Comment by mfn** [comment]
Sorry I missed the part with Lumen.

Lumen ~is~ was a constant source of problems to support, such things as these probably too.

The upcoming version 8 of this library dropped Lumen support entirely, please see https://github.com/rebing/graphql-laravel/pull/722 . I'm therefore closing this as it won't be fixed anymore.
