### ISSUE TITLE
Easier (dis)connecting relationships

### ISSUE THREAD

**Issue by matsn0w** [rebing/graphql-laravel#859]
When I want to connect model A to model B through a mutation, I have to manually check a lot of things (Do you exist model B? What if not? What if...) and save the relationship manually as well. Now, the manual saving is not a big probllem but there is not really a best practice for handling the input.

Let's say we have two models: Author and Post. An Author can have multiple Posts. 

I have an Input Type that looks like this:

```php
// UpdateAuthorInput
...
'posts' => [
    'type' => Type::listOf(Type::id()),
],
...
````

How would I validate this properly? The rules are obvious: the given ID's must exist.

My main problem is checking for existing relations. Sometimes you want to overwrite ALL current relations, sometimes you want to add or remove relations to the current relations.

In Lighthouse, it is possible to easily connect relationships in a mutation using the so called '[Nested Mutations](https://lighthouse-php.com/5/eloquent/nested-mutations.html)'. It would be nice if this package also had a similar system.

Any ideas about this? Any best practices, examples? I'm struggling a bit to explain my issue clearly. Any help is appreciated!

**Comment by matsn0w** [comment]
Hey, thank you for your answer.

That certainly helps, but doesn´t solve my issue of making some sort of 'generic' connecting method that is able to differentiate between either syncing the relation ship or overwriting it entirely.

**Comment by mfn** [comment]
Yep, there's no such thing in graphql-laravel and also not planned.

The support for Eloquent is opt-in at resolver time of a query/mutation, I'm not even sure where to start adding support for such a thing.

The way I interpret the goal of this library: a thin convenience layer on top of graphql-php, but not a full blown Eloquent integrated solution.

**Comment by matsn0w** [comment]
That's a good point. Would be nice if there was some kind of Elloquentish extension. Any recommendations?
