### ISSUE TITLE
Validation not working for integers

### ISSUE THREAD

**Issue by leonardocustodio** [rebing/graphql-laravel#861]
### Versions:
- graphql-laravel Version: 8.0.0
- Laravel Version: 8.49
- PHP Version: 8.0.9

### Description:

In a query when setting args with Type::int() and a rule with min:X.
It considers the rule as if it were a String (counting the characters) instead of validating the number.

### Steps To Reproduce:

Example, use as args:

            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'rules' => ['min:1', 'max:20'],
                'defaultValue' => 20,
            ],

If you pass 0 or -1 or anything below 1 it will work.....
If you use as args:

            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'rules' => ['min:2', 'max:20'],
                'defaultValue' => 20,
            ],

And pass for example limit: 5

You will get an error:
```
"message": "validation",
"extensions": {
   "category": "validation",
   "validation": {
      "limit": [
         "validation.min.string"
       ]
    }
},
```

It should get from Type::int() that this is an integer rule. Instead we have to define in rules 'integer' as well.

Regards,

**Comment by mfn** [comment]
Heya 👋🏼 

"it's not a bug, it's a feature!"

Basically, there's no fancy magic currently deriving from the `type` to implicitly add something to `rules` so the system is working as intended/initially designed.

I can understand what you're saying, and my response is "PRs welcome!" but currently I'm not even sure it's a good idea.

`'rules'` is optional so implicitly adding the Laravels integer validation must only be done iff there are `'rules'` present.

Simply adding it sounds like a no-brainer, but unsure what are the implications and what about other types etc.; could get complicated.

For a "quick fix" I'd rather encourage adding something to the docs to clear this up.

WDYT?

**Comment by leonardocustodio** [comment]
I think adding to the docs would be great, as there is a sample of validation of an integer with min and max without using integer. So the docs mislead that it would work and doesn't even tells about adding the 'integer' option.

I will make a PR for the docs,
Thanks ;)

**Comment by mfn** [comment]
> as there is a sample of validation of an integer with min and max without using 'integer' as rule

ugh! 💥 

> I will make a PR for the docs,

Thank you, much appreciated 🙏🏼
