### ISSUE TITLE
this is code-first approach, can we also add schema-first ?

### ISSUE THREAD

**Issue by videni** [rebing/graphql-laravel#865]
please check [code-first-vs-schema-first-development-graphql](https://blog.logrocket.com/code-first-vs-schema-first-development-graphql/)

**Comment by mfn** [comment]
As the article puts it
> Finally, it may also affect which framework for some language we can use. For PHP, for instance, Laravel can choose from both options through Lighthouse (schema-first) and Laravel GraphQL (code-first),

This library is code-first by design and there are no plans for schema-first; lighthouse provides a great schema-first experience AFAIK.

Thank you

**Comment by videni** [comment]
thanks, good to know.
