### ISSUE TITLE
Access returned data before sending?

### ISSUE THREAD

**Issue by tankerkiller125** [rebing/graphql-laravel#88]
I have a unique use case where I want some fields to only be accessible by the the owner of that resource (for example user email). However I can't seem to find away to check the user_id field of the data returned to check with the authed user id. And I do not want to have to add the user_id field to every query. Is their any way to fix this?

**Comment by rebing** [comment]
There is the 'privacy' field, which can be used with query arguments: https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#privacy

But if you want to authenticate by using returned data, then I guess you could do something like this
```
...
'email' => [
  'type' => Type::string(),
  'resolve' => function($user)
  {
    return $user->user_id === Auth::id() ? $user->email : null;
  },
  'always' => ['user_id'], // This makes sure that the id field is always selected with query
],
...
```

**Comment by tankerkiller125** [comment]
That's actually seems perfect
