### ISSUE TITLE
Image upload issue - Laravel - Graphql

### ISSUE THREAD

**Issue by productstrioangle** [rebing/graphql-laravel#885]
I have get repeated errors on my laravel-graphql image upload functionality,

Please anyone can share the exact method of image upload

{
query: mutation($file: Upload!) { singleUpload(file: $file) { id } },
variables: {
file: File // a.txt
}
}

**Comment by mfn** [comment]
I've seen you opened the discussion at https://github.com/rebing/graphql-laravel/discussions/884 too, let's keep it there until we've a confirmed bug for an issue, thank you!
