### ISSUE TITLE
Can i use this with polymorphic relationship?

### ISSUE THREAD

**Issue by jeekymojica** [rebing/graphql-laravel#9]
How can we use this with laravel eloquent polymorphic relationship?

**Comment by rebing** [comment]
I haven't tried polymorphic relationships, so I assume they don't work? The Support/SelectFields.php class probably has to be modified, but I currently don't have time for it. You can submit a PR, if you want.

**Comment by rebing** [comment]
#10 I added MorphMany and MorphTo support, although I'm not sure how to create the MorphTo graphql Type (https://laravel.com/docs/5.4/eloquent-relationships#polymorphic-relations 'commentable' in this example).

The relation post -> comments should work now though

**Comment by hugomosh** [comment]
Do you have an example, please : )

**Comment by AdrianCarreno** [comment]
@rebing I also want to use this package with polymorphic relations. Do I need to use Union or are regular type and query enough?

**Comment by Traxo7** [comment]
> The relation post -> comments should work now though

That works as expected.  
But I can't make it work the other way round? Was that resolved?

**Comment by mfn** [comment]
@Traxo7 depends on when you last checked. Since March/April this year a lot has improved, lots of contributions especially to the `SelectFields` class. Not sure what exact nature you have, but please try it out, also look at the tests as a guide, and report any issues you find!

**Comment by Traxo7** [comment]
@mfn 

I checked `tests` and found for example a `Like` model https://github.com/rebing/graphql-laravel/blob/master/tests/Support/Models/Like.php 

So the case I was talking about would be how to query for `likes`, and then get `likeable` models along with those likes. In your example, `Post` and `Comment` are `likeable`.    

So I presume query would look something like the following  
```
likes() {
  uid
  createdAt
  likeable {
    __typename
    ...on Post {
      // ...
    }
    ...on Comment {
      // ...
    }
  }
}
```
But I'm not sure how to approach this? Can you point me to a relevant example if it exists?  

One of the uses cases for this would be for example get 10 latest likes by user.
