### ISSUE TITLE
Add the ability to specify custom error messages in the fields method in InputType

### ISSUE THREAD

**Issue by zabavnikov** [rebing/graphql-laravel#936]
As I understand it, custom error messages can only be specified in the validationErrorMessages method in the mutation itself. But in this case, I have to duplicate the code for UpdateTravelMutation or create a trait that will contain the validationErrorMessages method.

How do you look at the fact that in the fields method, you can add an array of messages for each field and list custom error messages for each rule in it.

Sorry for my English, I used a translator. 😊

CreateTravelMutation
```php
public function args(): array
{
    return [
        'input' => [
            'type' => GraphQL::type('TravelInput!')
        ]
    ];
}
```

UpdateTravelMutation
```php
public function args(): array
{
    return [
        'id' => [
            'type' => GraphQL::type('Int!'),
        ],
        'input' => [
            'type' => GraphQL::type('TravelInput!')
        ]
    ];
}
```

TravelInput
```php
public function fields(): array
{
    return [
        'place_id'  => [
            'type'  => GraphQL::type('Int'),
            'rules' => ['required', Rule::exists('places', 'id')->where(function ($query) {
                $query->where([
                    'type' => 'countries',
                ]);
            })],
        ],
    ];
}
```

Example TravelInput with custom error messages
```php
public function fields(): array
{
    return [
        'place_id'  => [
            'type'  => GraphQL::type('Int'),
            'rules' => ['required', Rule::exists('places', 'id')->where(function ($query) {
                $query->where([
                    'type' => 'countries',
                ]);
            })],
            'messages' => [
                'exists' => 'Страна не найдена'
            ]
        ],
    ];
}
```

**Comment by mfn** [comment]
> I have to duplicate the code for UpdateTravelMutation or create a trait

Personally I think I would go for some approach to have shareable code for `validationErrorMessages` between multiple mutations; doesn't have to be trait -> whatever suits you to get your translation key=>values into that method.

I'm not sure bolting another field there in is a good idea; I also wouldn't name it `messages`, rather `validationMessages`.

I would have to see an implementation to judge how much complexity this would add for maintenance.

**Comment by zabavnikov** [comment]
@mfn, thanks for the answer.

After sitting and thinking again, I came to the conclusion that the trait is quite suitable for solving this problem. Even more so, that this problem only occurred with creation and update mutations.

```php
<?php

trait ValidationMessages
{
    public function validationErrorMessages(array $args = []): array
    {
        return [];
    }
}
```
