### ISSUE TITLE
Laravel middleware ConvertEmptyStringsToNull does not work anymore

### ISSUE THREAD

**Issue by crissi** [rebing/graphql-laravel#938]
### Versions:
- graphql-laravel Version: 8.3
- Laravel Version: 9
- PHP Version: 8.1

### Description:
Laravel middleware does not work after implementation of: Integrate laragraph/utils RequestParser

![image](https://user-images.githubusercontent.com/3076578/187895850-8f988f62-b105-44b0-b04a-7041d772a301.png)

$request->getContent() is the raw request data.

using request->json() we will we get the data that has been though middleware.

### Steps To Reproduce:
use a mutation with variables:
{"someField":""} and see that it will not be converted to {"someField":null} 

If you send by header, application/x-www-form-urlencoded, then it actually get the data after it gone though the middleware, here they use $request->post();

**Comment by mfn** [comment]
I think I partially understand what you describe, but not fully…

Do you think you can make a PR with an test showing this problem, then I think it's easier to work on a fix.

**Comment by crissi** [comment]
let just close it!
