### ISSUE TITLE
GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"

### ISSUE THREAD

**Issue by GlauberF** [rebing/graphql-laravel#939]
### Versions:
- graphql-laravel Version: ^8.3.0
- Laravel Version: 8.x
- PHP Version: 8.1.9

### Description:
When upgrading from laravel 7.x and PHP 7.3.x to laravel 8.x and php 8.1.9 version, I started getting these error.

![Captura de Tela_selecionar área_20220905144202](https://user-images.githubusercontent.com/11314585/188496206-aeb2196f-dddc-47d3-937a-41db22297028.png)

**Comment by mfn** [comment]
That is coming from the underlying graphql-php library, we utilize this via `ValidateOperationParamsMiddleware`

How does the _actual_ request look like and why is it expected to work if neither `query` or `queryId` is present?

**Comment by GlauberF** [comment]
I was sending get method, it had to be post.
Sorry.

**Comment by akshaykmalik** [comment]
> I was sending get method, it had to be post. Sorry.

thank you so much. I was making the same mistake and wasted a lot of time on this.
